### ISSUE TITLE
Multiple Authors on a Notebook

### ISSUE THREAD

**Issue by cassandraoid** [observablehq/feedback#1]
**Describe the solution you'd like**
I'd like the option to choose co-authors or collaborators on a notebook to credit their assistance or contribution.

**Describe alternatives you've considered**
Other alternatives could be 'contributors' or option for one 'coauthor'.

**Comment by jrus** [comment]
How should this work with author RSS feeds?

**Comment by CobusT** [comment]
This was released on Dec 17, 2021. 🎉
See release note here: https://observablehq.com/@observablehq/release-notes#authors
