### ISSUE TITLE
Global find/replace in notebook, ideally with regular expression support

### ISSUE THREAD

**Issue by jrus** [observablehq/feedback#10]
**Problem:** Currently the only find/replace supported in the notebook UI is whatever the browser natively supports within a single cell editor view. But there are many programming and data manipulation tasks this can't handle. For example, changing the name of a cell and trying to update all of the cells which reference that one to the new name.

**Proposed solution:** Add a UI for notebook-global find/replace, ideally including a checkbox for interpreting the find and replace fields as regular expressions.

**Current workaround:** Open a notebook in safe mode, select all in the browser and copy, paste into an external text editor, perform the global find/replace operation there, then copy the updated cell content back into the notebook one at a time, possibly with reference to the diff from before/after the find/replace. This is cumbersome and error prone, but still better than pure manual update to the original notebook.

**Comment by jrus** [comment]
This could also be more pleasantly worked around if the platform had a documented read/write notebook API; then people could use their own preferred editor or other offline tooling for find/replace. https://github.com/observablehq/feedback/issues/6

**Comment by CobusT** [comment]
We now have Find and Replace in notebooks!
https://observablehq.com/@observablehq/release-notes#cell-957
