### ISSUE TITLE
textPath doesn't stay on path, animated circle doesn't start on notebook load

### ISSUE THREAD

**Issue by maxgraze** [observablehq/feedback#101]
**Describe the bug**
1. On the first spiral, the circle doesn’t start moving right away; you need to move the speed nob first.
2. The textPath isn’t directly on the path but goes over and under.

**Expected behavior**
I expect the textpath to be consistently above the line, as I coded, and the animated circle to start circling around the spiral without having to move the input.

For **Screenshots**, **To Reproduce** & **Desktop**
 Please see [this post](https://talk.observablehq.com/t/bug-or-code-problem/5108).

**Comment by CobusT** [comment]
Thanks for raising this. That is very strange indeed. Sorry we have not had a chance to look into this yet, but logging it here was a good plan so we can have it in our backlog.

**Comment by CobusT** [comment]
Still looking at your 2nd point but are you sure about the 1st point? I tried on a few different browsers and the circle moves on the spiral when the notebook loads...

**Comment by CobusT** [comment]
OK, I think we found the problem. There are too many spirals on that html document :slight_smile: Seriously though that is the actual problem. You are defining multiple #spiral ids on the page (looks like 4…).

When you make them unique (#spiral1, #spiral2 etc) that should fix the problem.
A better solution would be to call DOM.uid to generate an automatically-unique name for your ids.
