### ISSUE TITLE
Did you just change the context Cells are evaluated in?

### ISSUE THREAD

**Issue by somethingelseentirely** [observablehq/feedback#102]
**Describe the bug**
Up until recently (1-2 days?) cells were evaluated in their own tiny evaluation contexts,
through this I could get syntax highlighting in the debugger.

Not it seems like everything is loaded in a single blob, which confuses the chrome syntax highlighter end everything turns orange...

**To Reproduce**
1. Go to a large notebook with lots of markdown, code and stuff.
2. Enter the debugger.
3. Behold the orange.

**Expected behavior**
Proper syntax highlighting.

Alternate feature request:
An alternative way of solving this would be through the use of source maps.
Ideally everything would appear in a virtual folder hierarchy,
where each folder corresponds to an (imported) notebook,
and each file corresponds to a cell.

**Screenshots**

<img width="1414" alt="Screenshot 2021-06-02 at 12 52 45" src="https://user-images.githubusercontent.com/74891396/120468380-70875380-c3a1-11eb-9c60-5f7c703eb901.png">

**Desktop:**
 - OS: [MacOs]
 - Browser [chrome]
 - Version [Version 90.0.4430.212 (Official Build) (x86_64)]

**Comment by mbostock** [comment]
No, this was not changed. What you are seeing is an imported notebook, which are compiled to ES modules.

**Comment by somethingelseentirely** [comment]
Alright, sorry, my bad 😅 !

I think the source-map idea would still be neat, as it's often hard to know exactly where each piece of code is.
So the only good way currently is to add a `debugger` statement, which is a bit of a pain especially when loading multiple dependent notebooks with extremely long load times (we do some heavy computational stuff in some, but having everything inside a single notebook has also shown to be very hard to manage at a certain size).

**Comment by mbostock** [comment]
I filed a feature request for sourcemaps. Please upvote if you are interested in this feature. Thank you for the feedback!
