### ISSUE TITLE
observable_jupyter support external self hosted .js files

### ISSUE THREAD

**Issue by a10k** [observablehq/feedback#104]
**Is your feature request related to a problem? Please describe.**
1. https://github.com/observablehq/observable_jupyter is listed on the https://pypi.org/project/observable-jupyter/ page but is currently 404
2. The package allows embedding observable cell in Jupiter python notebooks but only the public ones hosted on observable, but not the ability to provide custom url for the import 

**Describe the solution you'd like**
Allow a url  as first parameter for embed
~~~py
embed('@mbostock/epicyclic-gearing', cells=['graphic'], inputs={'speed': 0.2})
~~~

**Describe alternatives you've considered**
Making a PR to the above repo myself if possible? workaround is to manually tweak the pypi package in the local folder to allow this currently.

**Additional context**
This feature will support importing from private notebooks with api keys, versioned notebooks, self hosted/modified after downloading,  etc.,

**Comment by a10k** [comment]
On a related note, there is also a minor issue with the current version:
1. The observable logo overlaps the scrollbar
2. On some cells there is an issue with the height getting updated, which adds scrollbars, which triggers an infinite loop of height changing and scrollbar getting removed and then height being updated again..
![scrollissue](https://user-images.githubusercontent.com/1458845/120894606-e526f000-c636-11eb-86f7-2f8c37a49880.gif)

**Comment by mbostock** [comment]
The observable-jupyter project was not an official project and is not supported by Observable. If we can help with using our [Embedding API](https://observablehq.com/@observablehq/downloading-and-embedding-notebooks), please let us know.
