### ISSUE TITLE
naming of markdown cells?

### ISSUE THREAD

**Issue by aaronkyle** [observablehq/feedback#105]
**Is your feature request related to a problem? Please describe.**
I often wish to embed Markdown cells without embedding all of a notebook.  Now that there's the new, easy to use Markdown cell type, it's a bit of a shame to have to switch back to a JS cell type and use md`` [the markdown template literal] when I wish to embed these cells in a partial notebook.

**Describe the solution you'd like**
I image this might get confusing, but if we could do something like `cell_name = ` for markdown cells (and HTML and TEX cells, for that matter), that'd be terrific!  (i imagine you're working on this and it's part of the reason embed isn't currently enabled in next?)

**Describe alternatives you've considered**
just using JS cells for everything, which is fine.

**Comment by CobusT** [comment]
related to #107

**Comment by CobusT** [comment]
This was just released today!
