### ISSUE TITLE
Allow creating named cells for non-javascript cell modes

### ISSUE THREAD

**Issue by JobLeonard** [observablehq/feedback#107]
![image](https://user-images.githubusercontent.com/259840/118365533-74436980-b59d-11eb-83a4-592777d6d97d.png)

![image](https://user-images.githubusercontent.com/259840/118365566-95a45580-b59d-11eb-966a-d6af296fd13c.png)

Currently only JavaScript cell modes allow for creating named cells. This limits the use of the other cell modes a bit. For example, I cannot create named paragraphs of markdown blocks, so I cannot (for example) create links to an appendix from the "main" part of the notebook and back, [like I did in my Seam Carving notebook for example](https://observablehq.com/@jobleonard/seam-carving-with-forward-energy-but-we-make-a-new-image-with). 

**Describe the solution you'd like**

I think the simplest solution would be to detect if the cell starts with an assignment, optionally including `{}`, just like how Observable JavaScript is different from regular JavaScript:

```js
someVariableName = {
 ...
}
```

If all cell modes supported this notation that would also make it the easiest to pick up for new users, since the logic would be consistent with any future cell modes too.

**Comment by CobusT** [comment]
We just released the feature to allow naming of all cell types! It is not the solution you requested, and it will go through some UI tweaks (possibly placing the cell name next to the cell) but the core functionality is now supported.

Let me know if you are ok closing this issue.

**Comment by JobLeonard** [comment]
Can you link to the notebook showing the new UI? I can't find it

**Comment by CobusT** [comment]
Check out the release note about 'Call naming' [here](https://observablehq.com/@observablehq/release-notes) where we show a small video of it in action.

**Comment by JobLeonard** [comment]
Ah, yeah interface design that works for me! :)
