### ISSUE TITLE
BOOKMARK position in cell

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#109]
When working on a notebook I often jump between the the cells output and where I am writing the code.

Getting back to the line that I am working on isn't always easy in long code blocks.

Adding bookmarks would really help with this navigation.  
I could drop a bookmarks on the line of the cell i'm working and another bookmark to see the cells output
and then jump between the two locations.

Would also help in navigating back from an  *alt double click* on  a variable to easily just recall the position where I was.

**Comment by mootari** [comment]
@hellonearthis Would this bookmark be for the line number? I.e., it doesn't shift with the code if you line breaks above it?

**Comment by hellonearthis** [comment]
@mootari just getting back to the cell would really help.  Classic version of Observable had an index of named cells and that was good.  Having it also recognize the line in the cell would be a bonus. BUT, just having it just to the cell (so it shows the cell output) would help productivity.

I guess my dream would be to assign a bookmark to a number key like ctrl+alt+1 to jump and ctrl+shift+alt+1 to set the currently active cell to the bookmark.

**Comment by mootari** [comment]
Observable recently added cell links that are derived from a cell's internal ID, thus allowing you to link to any cell:
<img width=300 src=https://user-images.githubusercontent.com/322014/127848977-d52cbdc7-2b5d-41b7-bc76-1c28af8bb5ef.png>

Does this solve the issue for you?

**Comment by hellonearthis** [comment]
It is almost there, but they would need a reload of the page.

**Comment by mootari** [comment]
I see, you want the link to be clickable so that you can update the tab's history.

For the record, you can do that for named cells, by clicking the first entry in the context menu:
<img width=300 src=https://user-images.githubusercontent.com/322014/127850469-0a004294-8b75-4aac-8021-951ccda1c3de.png>

**Comment by hellonearthis** [comment]
@mootari that's interesting navigation tip, thanks.

**Comment by CobusT** [comment]
> Classic version of Observable had an index of named cells and that was good.

I assume this is the 'mini map' on the right that you are referring to? That is still planned for the next editor...

**Comment by CobusT** [comment]
Does it make sense to close this, since there are a few solutions mentioned here and the mini-map is also addressing some of this?

**Comment by CobusT** [comment]
OK, let's keep this open as a feature request then. 
Minimap (visual dataflow) is scheduled for the team to work on soon, but I cannot commit to a timeline unfortunately.

**Comment by mootari** [comment]
Closing as outdated since the minimap was added a long time ago.
