### ISSUE TITLE
Page Up / Down,  is only acting like arrow keys and not scrolling screen to cell top.

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#111]
Pressing the *Page Down* key  when editing a cell,  the cursor only goes down one line and not one screen down in that cell.

But, if I have then bottom of the cell onscreen, then it jumps to the end of the cell and the *Page Up* only goes up by one line.

Also the *Page Up*  doesn't show/scroll to the top of the cell.  

The cell.
![image](https://user-images.githubusercontent.com/121805/112333006-17ef6680-8d1f-11eb-8cf9-af9ead3bb010.png)

Scrolling from in the cell:
![image](https://user-images.githubusercontent.com/121805/112333169-3c4b4300-8d1f-11eb-9261-10ec4bf107e1.png)

Where I end up after pressing *Page Up*
![image](https://user-images.githubusercontent.com/121805/112333301-5a18a800-8d1f-11eb-990e-fe73d14a825a.png)

The cursor is at the top of the cell but off screen.

**Desktop:**
 - OS: Windows 10 pro
 - Browser:  chrome
 - Version: 89.0.4389.90 (Official Build) (64-bit)

**Comment by CobusT** [comment]
This is in 'experimental features'/next.

**Comment by CobusT** [comment]
Tested this recently on Windows Chrome and this seems to be fixed. Please reopen if this is still not working for you.
