### ISSUE TITLE
Keyboard shortcuts listed in help that don't work on chrome / windows.

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#112]
I uses Chrome on Windows and have found some keyboard shortcuts listed in the help that don't work.

Toggle pin -> Ctrl Shift P  ( This opens the browser printer setup menu)

Swap characters before & behind the cursor -> Ctrl T ( Opens a new Tab in chrome)

Insert a literal tab character - Ctrl Alt Tab  (Open the windows task/application manager thing)
 
**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro
 - Browser:  chrome
 - Version: Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by CobusT** [comment]
Just want to summarize what is now working and what is still not working:

**Working:**
- `Ctrl-.` for pin/unpin (seems like you can also use `Ctrl-Shift-P`
- `Home`  Start of current line (updated from Shift Fn ←)
- `End` End of current line (updated from Fn →)

**Not working**
- `Ctrl-T` Swap characters before & behind the cursor ->  Opens a new Tab in chrome and edge
- `Ctrl Alt Tab` Insert a literal tab character - Open the windows task/application manager thing
- `Ctrl-F` doesn't open search/find when in a cell (Command-F works on Mac)

**Comment by CobusT** [comment]
Update:

- `Ctrl-T` This conflicts with new tab on Windows, so we removed that shortcut from the notebook and the help panel.
- `Ctrl Alt Tab` Removed from notebook and help panel
- `Ctrl-F` Clarified in the notebook that it doesn't work inside the editor (since it conflicts with the Emacs keybindings in Codemirror)
