### ISSUE TITLE
The description of action doesn;t match it's function. In the Help (?)

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#113]
Was looking through the help and saw this text.  Its description doesn't match the actual function.
Other editors that do this have wording like **select text using Column (box) selection.**

Fantastic feature BTW,  almost as good as multi cursors which are completely incredible! 
![image](https://user-images.githubusercontent.com/121805/111293519-3a91d780-86ae-11eb-8d16-9acf3f8e87b8.png)

**Comment by Fil** [comment]
On some (recent?) keyboards `alt` has become `option`.

**Comment by justin-nw** [comment]
Regarding Fil's comment: I believe the Keyboard Shortcuts notebook has code that detects whether the user is on Mac or non-Mac, and displays either "Alt" or "Option" appropriately.

**Comment by justin-nw** [comment]
@mootari, thanks for your comments. We are trying to cover both the Keyboard Shortcuts notebook and the Help panel in this issue (which is probably not obvious). I am making the changes to the Keyboard Shortcuts notebook and wanted to note that the notebook does have a way to detect whether MacOS or a non-MacOS (Windows or Linux) is being used. I do not know if the Help panel has a way to do this also. I have changed the wording of the notebook to address the suggestion from @hellonearthis, and now I will assign the issue to @CobusT for the Help panel portion.

**Comment by justin-nw** [comment]
Republished Keyboard Shortcuts (v452). Text now reads: 
Option/Alt-Drag: Clear the current selection, then select text using column (box) selection.
Option/Alt-Command/Ctrl-Drag: Without clearing the current selection, select text using column (box) selection.
Assigning issue to @CobusT for Help panel changes.

**Comment by CobusT** [comment]
> I do not know if the Help panel has a way to do this also.

It does. This is what it looks like on Mac (we show the key, not text):
<img width="325" alt="image" src="https://user-images.githubusercontent.com/10869236/127888677-9613f934-d70e-4023-a1ea-a9ee466c7c6e.png">
