### ISSUE TITLE
CTRL - x only cuts the text on the line and doesn't delete the line.

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#115]
Using the CTRL - x, it only cuts the text from the line but doesn't delete the line.

Which is nice but it's different to what it did before as it would cut/remove the line.
If more than one like is selected it works as it did by removing the lines.

Having see the way CTRL- x works,  I think it would be useful to keep  but assign that behavior to CTRL - X (shift x)

**Comment by CobusT** [comment]
I tested this and it seems to work for me in Next now. @hellonearthis please let us know if this is still not working for you.
