### ISSUE TITLE
Access level and history on new blank project return 501

### ISSUE THREAD

**Issue by bchartoff** [observablehq/feedback#117]
**Describe the bug**
After creating a brand new project, the access level icon and history icons both lead to an error page (501).

**To Reproduce**
1. From any page, click "+New"
2. Click either the  access-level icon ![image](https://user-images.githubusercontent.com/4662381/121373343-fb6dce00-c90c-11eb-9431-a76b8550a86d.png) or the history icon ![image](https://user-images.githubusercontent.com/4662381/121373460-16404280-c90d-11eb-9046-28f402d020df.png)

3. Both return an error page, screen shot below
4. Making any edit to the page content corrects this behavior

**Expected behavior**
Either these actions would open up the appropriate menu, or the two icons would not be available until an edit was made (similar to context menus)

**Screenshots**
![image](https://user-images.githubusercontent.com/4662381/121373945-7cc56080-c90d-11eb-8558-a28ef8c16187.png)

![image](https://user-images.githubusercontent.com/4662381/121374092-9c5c8900-c90d-11eb-8467-1ed352ed2e4e.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser: Chrome 
    - Version 90.0.4430.212
- Observable version: Next (but reproducible in Classic)

**Additional context**
Likely not a common use case for frequent users, I encountered error when checking to see what default access level was on blank project.

**Comment by CobusT** [comment]
Thanks for alerting us!

**Comment by CobusT** [comment]
I believe this is now fixed. Please let us know if you still experience a problem.
