### ISSUE TITLE
Next: Offline Attachment doesn't appear on UI 

### ISSUE THREAD

**Issue by radames** [observablehq/feedback#118]
**Describe the bug**

While you can upload an attachment on the classical Observable Notebook without forking it, on the next version, after uploading, the file attachment doesn't appear on the UI. However, you can still guess how to reference it.

Note that after attaching the file, the notebook reports one unsaved change.
___    

<img width="1000" alt="next" src="https://user-images.githubusercontent.com/102277/121450056-d9496f80-c94f-11eb-8d6b-575cac8b60e3.png">

You can still guess the attachment reference
___    
<img width="1000" alt="ref" src="https://user-images.githubusercontent.com/102277/121450073-de0e2380-c94f-11eb-9959-163a041d7acb.png">

Classic
____
<img width="1000" alt="one" src="https://user-images.githubusercontent.com/102277/121450039-d189cb00-c94f-11eb-8479-d4599eaf9368.png">

**To Reproduce**
1. Go to https://observablehq.com/@mbostock/electric-usage-2019?ui=next
2. Attach a file 
3. You won't be able to see it on the UI

**Expected behavior**

1. Go to https://observablehq.com/@mbostock/electric-usage-2019?ui=classic
2. Attach a file 
3. You will see the attachment on the UI

**Comment by CobusT** [comment]
Thanks for raising it!

**Comment by CobusT** [comment]
This is now fixed.
