### ISSUE TITLE
click on button in html form crashes the observablehq page

### ISSUE THREAD

**Issue by rudifa** [observablehq/feedback#119]
How to reproduce: 
- open the [demo  notebook](https://observablehq.com/@rudifa/click-on-button-in-html-form-crashes-the-observablehq-page) and click on the button `click to crash the page!`
- or, paste the following into an empty cell of a new observable notebook
```
html`
  <form>
    <button>click to crash the page!</button>
  </form>
`
```

The DevTools console displays this:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://observablehq.com') does not match the recipient window's origin ('https://rudifa.static.observableusercontent.com').
``` 

First seen in Chrome, but same crash occurs also in Safari, Firefox and Brave, all on a Mac Big Sur, and on iPad.

**Comment by Georift** [comment]
A `<button>` when placed inside `<form>` like that act as if they were a submit button to a form. So clicking it will attempt to reload the page that they are in. Have a look at the [first example here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#html) _"Form which will send a GET request to the current URL"_.

Observable runs your notebook code inside an iframe for safety reasons. Notice when you click the button your URL changes to https://rudifa.static.observableusercontent.com, that the domain of your iframe! The error message we're seeing here is shown when we try and open an iframe directly, I don't think this is related to the button. My guess is it's not a crash? What are you trying to do?

**Comment by rudifa** [comment]
_What are you trying to do?_

I want to group several inputs to a _<form>_ in a cell.
I realize now that I should use a simple `<div> `instead.
