### ISSUE TITLE
support URLs written using standard URL escape codes

### ISSUE THREAD

**Issue by jrus** [observablehq/feedback#120]
**Description:** Many URL validators throw an error when they get an `@` character (because `@` is a "reserved character"); unfortunately this prevents most Observable profile / notebook URLs from validating, which means that Observable profiles and notebooks cannot be successfully linked in many contexts, without jumping through hoops like linking a "url shortener" redirect site. It would be great if `%40` were supported as an alternative, e.g. https://observablehq.com/%40mbostock should resolve to https://observablehq.com/@mbostock

Cf. https://en.wikipedia.org/wiki/Percent-encoding

**Steps To Reproduce:** (1) Go to https://observablehq.com/%40mbostock

**Expected behavior:** The URL should either redirect to https://observablehq.com/@mbostock or directly render

**Actual behavior:** 404 page.

**Comment by galopin** [comment]
Actually, there is another way to specify a username in a URL.

Would it be possible for Observable to use the following scheme instead?

`mbostock`
~~~javascript
{
  yield new URL('https://mbostock@observablehq.com/').username;
}
~~~

The URL could then either redirect to https://observablehq.com/@mbostock or directly render!?

:warning: Sadly, versions of Internet Explorer that were released starting with the release of security update `832894` [no longer support handling usernames](https://learn.microsoft.com/en-US/troubleshoot/developer/browsers/security-privacy/name-and-password-not-supported-in-website-address) in HTTP and HTTPS. The assumption was that a malicious user might use this URL syntax to create a hyperlink that appears to open a legitimate website but actually opens a [deceptive/spoofed website](https://learn.microsoft.com/en-US/troubleshoot/developer/browsers/security-privacy/steps-to-identify-and-protect-from-spoofed-web-sites). However Internet Explorer 11 will be permanently disabled on certain versions of Windows 10 as part of the February 2023 Windows security update ("B") release scheduled for February 14, 2023.

**Comment by galopin** [comment]
@mootari Granted but in days of yore — if I remember it correctly — nothing prevented you to hijack this for a different purpose using rewrite or redirect rules…  That said, it looks like latest browsers do strip out the username part in the URL. Well, forget it! 😶

**Comment by galopin** [comment]
BTW, https://observablehq.com/%40mbostock no longer trigger a 404 error…

**Comment by galopin** [comment]
BTW, https://observablehq.com/%40mbostock no longer triggers a 404 error…

**Comment by mootari** [comment]
> BTW, https://observablehq.com/%40mbostock no longer triggers a 404 error…

@galopin Good catch, thanks!
