### ISSUE TITLE
observable-database-proxy self-hosted proxy Postgresql query request does not complete

### ISSUE THREAD

**Issue by johnoscott** [observablehq/feedback#121]
**Describe the bug**
I have installed and configured `observable-database-proxy` and a self-hosted proxy to connect to my local postgresql server as per instructions and when I run a call with a `client.query(..)` call the request just hangs. 

I can see in the browser's Dev Tools that the request is `pending`

![image](https://user-images.githubusercontent.com/291958/122774158-4fed5200-d2ec-11eb-808e-8b0e7a00fa3e.png)

**To Reproduce**
1. Configure the self-hosted proxy (I tried with and without SSL option)
2. Create notebook with code :
  ```
  client = DatabaseClient("localssl")
  ```
  and another cell with:
  ```
  product_count = client.query(
  `select count(*) from products`
)
  ```
3. query does not complete

**Expected behavior**
I expected the query to be proxied to the db server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 Catalina
 - Browser: Chrome 
 - Version 91.0.4472.106 (Official Build) (x86_64)

**Comment by CobusT** [comment]
I just tried doing this from scratch, following the instructions [here](https://observablehq.com/@observablehq/self-hosted-database-proxies) on my Mac and it all worked (no SSL, using Chrome).

A few questions:
- Can you share the credentials you used in your proxy setup? I used `postgresql://testuser:qwerty@127.0.0.1:5432/testdb` (fyi)
- Did you verify that your database was running? `psql testdb`

**Comment by johnoscott** [comment]
I tried again using your steps and I am experiencing the same problem - the query response from the browser just stalls.

Here is the postgres connect string i am using (same as yours):

```
postgresql://testuser:qwerty@127.0.0.1:5432/testdb
```

and here is the request the browser is making (when i right-click > copy as CURL in the Network tab of Chrome Developer Tools

```
curl 'http://127.0.0.1:2899/query' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'Authorization: Bearer eyJvd25lciI6InJvdW5kcmVjdCIsIm5hbWUiOiJyb3VuZHJlY3QyIiwidHlwZSI6InBvc3RncmVzIiwib3JpZ2luIjoiaHR0cDovLzEyNy4wLjAuMToyODk5IiwiZXhwIjoxNjI0NDUxMzMzNzI4fQ==.pft0diTVHUR88jtnFo1oWkz9NJJ9sC23maDcoP/APeA=' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Origin: https://roundrect.static.observableusercontent.com' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-raw '{"sql":"select count(*) from toys"}' \
  --compressed
```

I can confirm that the connection to the database is working (using both `psql` from the command-line and a GUI client Postico for Mac)

I also tried the following to no avail:
* different versions of node (I was using v14, now using v16) and the symptom is the same.
* I tried again on a different Mac (installing homebrew, node and postgres from scratch)
* I tried using a fresh Observable account

**Comment by CobusT** [comment]
Here is my request (which works):
```
curl 'http://127.0.0.1:2899/query' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'Authorization: Bearer eyJvd25lciI6ImNvYnVzIiwibmFtZSI6InRlc3RkYiIsInR5cGUiOiJwb3N0Z3JlcyIsIm9yaWdpbiI6Imh0dHA6Ly8xMjcuMC4wLjE6Mjg5OSIsImV4cCI6MTYyNDQ2MDg5OTkwM30=.RRf6FYC6R8SiwKTh0UTmXH4lUP230uRhKdq24xce45w=' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Origin: https://cobus.static.observableusercontent.com' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-raw '{"sql":"select * from users"}' \
  --compressed
```

I am honestly not sure why your results are different. I guess you changed to the non-SSL connection (original screenshot had https but the curl command here shows http). So that should work! 

I assume your connection settings (in Observable) look like this?
<img width="500" alt="Screen Shot 2021-06-23 at 8 05 23 AM" src="https://user-images.githubusercontent.com/10869236/123121243-dba0d480-d3f9-11eb-9632-3b4dcddd4881.png">

**Comment by johnoscott** [comment]
Yes thats right, I dropped SSL and went for the defaults. 

I also turned on logging for the local postgresql server and there are no query requests logged.

I think I should try to step through the proxy code. Is there any logging / verbose mode I can use ?

**Comment by CobusT** [comment]
I assume just doing 
`client.describe()`
also hangs?

**Comment by visnup** [comment]
Can you check your macOS firewall settings? Maybe possibly disable it and see if that works?
![image](https://user-images.githubusercontent.com/10444/123337545-3b7fa400-d4fc-11eb-9c64-50430208b551.png)

And if that works, then you'd want to check Firewall Options… on that tab and see if node is been allowed:
![image](https://user-images.githubusercontent.com/10444/123337659-64079e00-d4fc-11eb-9f9c-369cc685fccc.png)

**Comment by visnup** [comment]
And one other quick thing I'd check is to use "127.0.0.1" instead of "localhost" though for Chrome that should always be the same, no matter how your computer is configured.

**Comment by johnoscott** [comment]
Visnu, yes I checked Firewall. It turned OFF for me.

**Comment by johnoscott** [comment]
@CobusT yes `client.describe()` also hangs

**Comment by johnoscott** [comment]
So after further investigation it doesn't matter what the configured `postgres://` url is, the result is the same : the query (and describe) calls just hang.

**Comment by johnoscott** [comment]
any ideas on how I can resolve this ? I have been able to review this on 2 seperate Macs

**Comment by johnoscott** [comment]
Also fails on Windows 10 for me with exactly the same symptoms (query request in browser hangs as "pending").

This is now a blocker for me (I thought I could workaround the issue on my Mac by using Windows 10).

**Comment by CobusT** [comment]
John, 
Can we set up some time with you to screen share? Please reach out to support@observablehq.com with some time slots that would work for you. This is very strange, indeed.
Thanks.

**Comment by johnoscott** [comment]
OK I will email support. Thanks

**Comment by CobusT** [comment]
John, just wanted to close the loop for others here. After investigating, the fix was to downgrade the node version to v.12.16.1 which worked fine. We will fix the repo to use an updated pg module so that the proxy will work with more recent node versions.
