### ISSUE TITLE
Dropdowns on the Notebook page are cutoff by bottom of the page.

### ISSUE THREAD

**Issue by andrew-primer-e** [observablehq/feedback#122]
**Describe the bug**
On my Notebooks page (https://observablehq.com/@username?tab=notebooks), the dropdown menu for the last notebook extends beyond the bottom of the screen and I am unable to click on the final option.

**To Reproduce**
1. Go to your personal Notebooks page (https://observablehq.com/@username?tab=notebooks)
2. Click on the three dots below the last notebook tile in order to open its dropdown menu.
3. Notice that the "Move to trash" option is partially faded out.
4. Click on the "Move to trash" option, which has no effect.

**Expected behavior**
I expect to be able to use all options in the final notebook's dropdown menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/25675095/122835667-efd6ca00-d344-11eb-9e53-a4f26671e59a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 89.0.1 (64-bit)

**Comment by CobusT** [comment]
Thanks, Andrew. I am classifying this as a bug.

**Comment by visnup** [comment]
Fixed and change should be deployed soon.
