### ISSUE TITLE
Search seems to exclude "@observablehq"

### ISSUE THREAD

**Issue by JobLeonard** [observablehq/feedback#123]
**Describe the bug**

I was looking for a refresher on how the [file attachments](https://observablehq.com/@observablehq/file-attachments) worked, because I forgot how to create a `Uint8Array` out of a binary file. So I searched for the notebook and it did not produce any results with these queries:

https://observablehq.com/search?query=%40observablehq%20file%20attachments
https://observablehq.com/search?query=%40observablehq%20file
https://observablehq.com/search?query=%40observablehq%20attachments
https://observablehq.com/search?query=%40mbostock%20file%20attachments
https://observablehq.com/search?query=%40mbostock%20file
https://observablehq.com/search?query=%40mbostock%20attachments

(And no worries, eventually I did find [the original notebook](https://observablehq.com/@observablehq/file-attachments) but that's not really the point of this bug report, right?).

Now, it looks like this applies to `@observablehq` in general, but it also is kind of odd that it excludes `@mbostock`, since he originally wrote the notebook.

**To Reproduce**

1. Open the search input
2. Use any of the keyword combinations I linked above
3. Do not see the *File Attachments* notebook among the results

**Expected behavior**

If a given `@user` has published a notebook with `[name]`, then searching for `@user [name]` should produce a produce a result.

**Screenshots**

![image](https://user-images.githubusercontent.com/259840/122998368-3b24c300-d3ad-11eb-8bf6-5fe1a77270fb.png)

![image](https://user-images.githubusercontent.com/259840/122998104-ed0fbf80-d3ac-11eb-9af3-448d0031510a.png)

![image](https://user-images.githubusercontent.com/259840/122998054-de290d00-d3ac-11eb-9d30-adcf8d896f43.png)

**Comment by mootari** [comment]
Note that that this problem has existed since at least 2021-06-05.

**Comment by CobusT** [comment]
Thanks for logging this. That seems like a pretty nasty bug! That is great info, @mootari.

**Comment by CobusT** [comment]
We changed a setting that should now make this work again. Sorry for the inconvenience!
