### ISSUE TITLE
[Next] Set Custom Preview Image Generates Distorted Thumbnail.

### ISSUE THREAD

**Issue by radames** [observablehq/feedback#133]
**Describe the bug**

Using the new publish dialog to set a preview image from notebook generates a stretched thumbnail

**Setting preview image from notebook dialog (no zoom applied)**

![Screen Shot from ](https://user-images.githubusercontent.com/102277/125364376-35285f00-e327-11eb-95fb-1fadb42cb9dd.png)

**Setting preview image from dashboard ... menu (no zoom applied)**

![Screen Shot from notebook](https://user-images.githubusercontent.com/102277/125364375-348fc880-e327-11eb-9d2d-f94c17b53268.png)

The original image file

![untitled.png](https://user-images.githubusercontent.com/102277/125365078-79682f00-e328-11eb-879a-3fc6064f9c15.png)

**Desktop (please complete the following information):**
 - OS: OSX 11.4
 - Browser: chrome
 - Version: 91

**Comment by mootari** [comment]
Yeah, that dialog looks very wrong. A thumbnail's aspect ratio is 1.6 (640x400), and the preview canvas has the correct size. But the masked area should have been added to the canvas, not subtracted from it.

(Aside: Rounding the corners of the mask to match the Observable layout may have been a good idea on paper, but the corner radius does not match the layout, and thumbnails can also be displayed outside of Observable, where the image may be shown in full.)

**Comment by mootari** [comment]
This regression was reported five days ago. Given that many users do not notice the problem in time, it seems unwise to let this bug linger.

I can already see several examples of distorted thumbnails in https://observablehq.com/recent.

**Comment by CobusT** [comment]
A fix is coming...

**Comment by CobusT** [comment]
This should now be fixed.

**Comment by mootari** [comment]
@CobusT Can you determine at what date the bug was introduced, so that we can narrow down the the notebooks that may need to be checked?

**Comment by CobusT** [comment]
It was there since around 4/26 it seems although it was only a bug in next so only people who created custom thumbnails through the notebook menu in next would have run into this problem.
