### ISSUE TITLE
[Next] Add Visibility option "unpublished" to Publish settings

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#135]
**Is your feature request related to a problem? Please describe.**

The publish modal in Next provides a central place to set both a custom URL and a thumbnail for a notebook. But in order to apply one or the other, the notebook needs to be published.

**Describe the solution you'd like**

When a notebook is unpublished (private), add a third option "Unpublished" to the Visibility settings in the Publish modal, so that both the thumbnail and slug can be set without publishing the notebook.

It may be justifiable to only provide this third option while the notebook is still unpublished, to prevent accidental unpublishing.

**Describe alternatives you've considered**

For private notebooks, the URL can still be set via `Settings > Set URL ...`. However, there is no equivalent option for the thumbnail (see https://github.com/observablehq/feedback/issues/27#issuecomment-879424449). An alternative might be to provide a dedicated modal, similar to "Set URL", for the thumbnail.

**Comment by CobusT** [comment]
I think the new sharing modal handles this.
