### ISSUE TITLE
Offer sort options on any user's list of notebooks 

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#137]
**Is your feature request related to a problem? Please describe.**

A recent update added sort options for one's own notebook list as well as the search. However, these sort options are missing when viewing another user's list of notebooks, e.g. https://observablehq.com/@observablehq?tab=notebooks

**Describe the solution you'd like**

When viewing another user's list of published notebooks, offer additional sort options, similar to the ones on my own notebook listing.

**Describe alternatives you've considered**

Workaround: Perform a search by the user's handle, e.g. https://observablehq.com/search?query=%40observablehq

**Additional context**

The above workaround suggests that there is no technical limitation that would prevent these options from being added.

**Comment by CobusT** [comment]
Try it now! :-)
We reduced the sort options for another user's notebooks (no edited or created sorts) since that view is for published notebooks only and we don't want to 'leak' information about unpublished edit times or create times.
Enjoy!
