### ISSUE TITLE
[Next] Missing social media / open graph metadata tags

### ISSUE THREAD

**Issue by radames** [observablehq/feedback#139]
**Describe the bug**
It seems like the metadata for social media sharing / open graph is missing

Testing on both Twitter validator https://cards-dev.twitter.com/validator and FB https://developers.facebook.com/tools/debug/

<img width="1023" alt="fb" src="https://user-images.githubusercontent.com/102277/126263734-ddd2356e-768b-4210-a5e1-f1ac2a2c5763.png">

![twitter](https://user-images.githubusercontent.com/102277/126263730-bb84dd89-07b9-44e5-9cd9-e84d112da261.png)

On Twitter It works if you pass param `ui=classic` 

Test URL:

`https://observablehq.com/@neocartocnrs/paris-by-road-osrm?ui=classic`
vs
`https://observablehq.com/@neocartocnrs/paris-by-road-osrm`

**Comment by mootari** [comment]
Observable recently switched the UI for guest users to Next (I vaguely recall a comment along those lines by @visnup, but can't find it right now). My guess is that this regression is caused by the switch.

**Comment by CobusT** [comment]
That is correct. Thanks. We are aware of this bug and the team is working on a fix.

**Comment by radames** [comment]
Thanks @CobusT. Sorry for the repetition.

**Comment by CobusT** [comment]
No worries! Thanks for the detailed bug report.

**Comment by visnup** [comment]
Partially fixed to include title and image in social cards. Description support is close.

**Comment by visnup** [comment]
And f'real fixed and deployed now. Mind you, description parsing is done statically, so can't be as good as the notebook can accomplish right now.

**Comment by visnup** [comment]
An example of missing text is your face charts one @radames. We can't interpolate so the externalLink text gets lost. 😢  

> Inspired by ProPublica latest investigation The Secret IRS Files (if you haven't read it yet, you should!). One of the graphics created by Agnes Chang encodes financial information of super-rich, the face waffles.
> 
> I thought it could be a fun project to try to replicate it in my journey learning Plot.

becomes

> Inspired by ProPublica latest investigation (if you haven't read it yet, you should!). One of the graphics created by encodes financial information of super-rich, the face waffles. I thought it could be a fun project to try to replicate it in my journey learning . How it works Start with an image. I...

**Comment by radames** [comment]
hi @visnup, thanks for the fix! Yes, I see your point now. In the future might be helpful to have a notebook metadata description for social sharing and SEO optimization. Right now, do you know how does google crawler index notebooks? Is the google search snippets coming from the metadata or their GoogleBot rendering the js notebook content?

**Comment by visnup** [comment]
> hi @visnup, thanks for the fix! Yes, I see your point now. In the future might be helpful to have a notebook metadata description for social sharing and SEO optimization.

Yeah, there's an old idea to be able to explicitly set a "description" field which could be used for many of these instances. And to treat that description similarly to title, with the ability to use the iframe worker to render the last value automatically, which would be able to handle your notebook's description.

> Right now, do you know how does google crawler index notebooks? Is the google search snippets coming from the metadata or their GoogleBot rendering the js notebook content?

From our experience, it uses the full js notebook content to index. I believe it uses the description for display purposes in search results though. There's some other previous [json-ld structured data](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data) work we need to migrate too, but it's hard to tell how well that was working.
