### ISSUE TITLE
Dashboard: After deleting a notebook via "Recent notebooks", the wrong number of entries is displayed

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#140]
**Describe the bug**

The Observable dashboard (https://observablehq.com/ when viewed while logged in) includes a section "Recent notebooks", which displays up to 4 authorable notebooks in descending order of edit date. Deleting one of these notebooks via its context menu reloads the section, this time displaying up to 12 notebooks.

Internally, both times the route `https://api.observablehq.com/user/continue-editing?unified=true` is queried.

**To Reproduce**
1. Ensure that you have more than four combined notebooks in your personal and team accounts.
2. Create a new notebook
3. Visit https://observablehq.com/
4. Within the section "Recent notebooks", delete the notebook via its context menu

**Comment by mootari** [comment]
The same thing happens when forking a notebook from its context menu within Recent notebooks.

**Comment by CobusT** [comment]
This should be fixed now...
