### ISSUE TITLE
Reverting to a the current version results in error message.

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#146]
**Describe the bug**

I wrote up the description in the forum https://talk.observablehq.com/t/cannot-revert-current-version-in-notebooks/5371 with screenshots

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 92.0.4515.107 (Official Build) (64-bit)
  

TL;DR:
The UI allows you to "revert" to the current revision. However doing so results in an error message.

Either:
Make the error message more descriptive ( "you cannot revert to the same current revision" ) or make the "revert" element not clickable for the "currently used" revision.

**Comment by CobusT** [comment]
This should now be fixed. We remove the 'revert' link when you are viewing the latest version.
