### ISSUE TITLE
[Next] New notebooks can no longer be opened in a new tab

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#148]
**Describe the bug**

In Classic, the "New" button opens a modal that lists the accounts one has access to. Each modal entry is a link that can be opened in a new tab.

In Next, it is no longer possible to force new notebooks to open in a separate tab.

**Additional context**

I frequently create new notebooks from within other notebooks. In Next this is no longer possible without going through a different page first.

**Comment by jzhang621** [comment]
This has been fixed.

**Comment by cpietsch** [comment]
On Windows (Chrome) I need to hold the windows-key to have the "New" button open a new tab.
It should be the the crtl key. Maybe it is listening on the wrong KeyboardEvent.keyCode ?

For "create notebook" the ctrl key works.
