### ISSUE TITLE
Change default Team notebook permission to internal rather than private?

### ISSUE THREAD

**Issue by martgnz** [observablehq/feedback#15]
**Is your feature request related to a problem? Please describe.**
When you're working on a team you want your work to be shared with your colleagues by default to enhance discovery and collaboration. Right now the setting is set to "private" inside a team. As a result if you create a new notebook no one from your team will see it.

**Describe the solution you'd like**
Organisations have a setting to change the default permission for new notebooks. By default it should be "internal".

**Comment by CobusT** [comment]
I think that is a great setting to add! Thanks for suggesting it.

**Comment by afeierman** [comment]
+1 for this!

**Comment by CobusT** [comment]
We now have an option for a team owner (on the team's settings page) where they can set the default for the team to be either the individual on the team (default 
<img width="727" alt="Screenshot 2022-10-31 at 5 06 54 PM" src="https://user-images.githubusercontent.com/10869236/199131781-a112185a-c6e4-47e0-92e9-cbdc775ca37a.png">
default) or team-shared.
