### ISSUE TITLE
[Next] Some error markers are never cleared

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#150]
**Describe the bug**

Under some circumstances error markers on commas don't get removed.

**To Reproduce**

1. In Next, create a JS cell with a syntax error: `(,1)`
2. Change code to: `(1,1)`

**Expected behavior**

Error marker is cleared.

**Workaround**

Retype the comma.

**Additional context**

The buggy behavior appears to be tied to the comma: As long as the character isn't replaced (or the notebook reloaded), the marker will stick to it, even if it changes position.

**Comment by CobusT** [comment]
@mootari I think this is now fixed. Can you please retest and close if it is working for you?
