### ISSUE TITLE
[Next] Sticky safe mode notice blocks large area on narrow screens

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#152]
**Describe the bug**

In Next, when a notebook is viewed in a narrow viewport (e.g. mobile displays), the sticky Safe mode notice blocks out a large portion of screen.

**Screenshots**

<img width=300 src=https://user-images.githubusercontent.com/322014/127738562-44c1d6b8-f66a-418f-998f-e4d084974aec.png>

**Suggested solution**

Hide the description once the notice becomes sticky.

<img width=300 src=https://user-images.githubusercontent.com/322014/127738755-faae3e11-d4da-4f17-964c-74611fcbeda6.png>

**Additional context**

In Classic the notice scrolls with the page.

**Comment by CobusT** [comment]
Should be fixed now.
