### ISSUE TITLE
[Next] Cmd+Left on empty line moves cursor to cell's first line

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#153]
**Describe the bug**

When pressing <kbd>Cmd</kbd>+<kbd>←</kbd> on an indented line, the cursor position toggles between the start of the line and the start of the indented code.

However, when pressing the same shortcut while on an empty line, the cursor jumps to the start of the cell.

**Expected behavior**

When pressing <kbd>Cmd</kbd>+<kbd>←</kbd> on an empty line, the cursor remains on that line.

**Browser**

- Chrome 92 on macOS 10.13 and macOS 11.4

**Additional context**

Firefox and Safari are not affected.

This problem has been around for a while and was first reported on 2021-05-19 via Slack.

**Comment by CobusT** [comment]
I think this is on Windows, <kbd>Ctrl</kbd>+<kbd>←</kbd>? Or are you seeing this on Mac also? I could reproduce on Windows but not Mac, which is actually the  <kbd>Fn</kbd>+<kbd>←</kbd> keys...

**Comment by mootari** [comment]
On macOS <kbd>cmd</kbd>+<kbd>←</kbd> moves the cursor to the start of a line, and <kbd>cmd</kbd>+<kbd>→</kbd> moves it to the end.

I've added an "Expected behavior" section for clarification.

Here's a screencap of bug:
<img width=400 src=https://user-images.githubusercontent.com/322014/128093310-54381b21-6fb7-450e-9380-0427736f3eb6.gif>

**Comment by mootari** [comment]
Turns out this bug is only present in Chrome. I've updated the description.

**Comment by mootari** [comment]
I can reproduce the behavior on https://github.com/codemirror/codemirror.next. CodeMirror defines the same behavior for `Cmd+ArrowLeft` and `Home`. When pressed on an empty line, `moveSel()` will return `false`.

I suspect there may be some Chrome-specific handler further down the line. Unfortunately hard to debug in the browser, because the editor loses focus when interacting with the debugger.

**Comment by mootari** [comment]
This appears to be a Chrome bug. I could reproduce the behavior in a native textarea.

Related Chromium issues:
- [Issue 1184730: Pressing home/end key does not follow mac DefaultKeyBindings.dict](https://bugs.chromium.org/p/chromium/issues/detail?id=1184730)
- [Issue 1210250: command-backspace on empty line deletes everything prior to cursor in textarea](https://bugs.chromium.org/p/chromium/issues/detail?id=1210250)
