### ISSUE TITLE
[Next] "Move to trash" within notebook has no effect

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#154]
**Describe the bug**

Attempting to delete the currently viewed notebook via its context menu has no effect.

**To Reproduce**

1. Open owned notebook in Next
2. Click context menu > Delete > Move to trash
3. In the confirm modal, click "OK"

No network request gets sent, and the notebook is still present.

**Expected behavior**

The notebook has been deleted.

**Additional context**

The notebook can still be deleted via the classic UI, or via the context menu in listings.

**Comment by sydneypalumbo** [comment]
hey @mootari, thanks so much for reporting this 🙏 just pushing a fix now so it should be working again shortly... I'll verify in production before closing the issue 👍
