### ISSUE TITLE
[Next] 404 pages display wrong login status

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#155]
**Describe the bug**

When an inaccessible notebook URL (protected or non-existant) is viewed in the Next UI, the top bar displays "Sign in" / "Sign up" even when logged in.

**To Reproduce**

1. Log into Observable.
2. Ensure that Next is active by default.
3. Open https://observablehq.com/@does-not-exist/does-not-exist

The top bar shows the buttons "Sign in" and "Sign up" instead of the "New" button and the account's profile image.

**Additional context**

https://observablehq.com/@does-not-exist/does-not-exist?ui=classic shows the correct status.

**Comment by CobusT** [comment]
Yup. We noticed that too. We have an internal bug logged for that. Linking it here.
