### ISSUE TITLE
"New notebook" modal: Buttons difficult to access in mobile viewports < 480px width

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#156]
**Describe the bug**

When the "New notebook" modal is viewed in viewports below 480px width, the buttons are positioned sticky at the bottom of the viewport. However, the positioning does not account for the browser's address bar, causing the buttons to be hidden below the viewport. To access the buttons, a user has to ensure they scroll the whole page, by:
1. either touch-scrolling within the Owner section until the address bar disappears,
2. or scrolling _past_ the bottom of the templates list.

**Smartphone (please complete the following information):**

 - Chrome 92 on Android 10 (Sony Xperia XZ2 Compact)

**Comment by mootari** [comment]
![Screenshot_20210801-154001](https://user-images.githubusercontent.com/322014/127773016-250c300b-61ad-4f64-a362-804ab91bd5aa.png)
![Screenshot_20210801-154018](https://user-images.githubusercontent.com/322014/127773018-6aff3301-9b50-45fb-8fc9-1c24500fda7d.png)

**Comment by jzhang621** [comment]
@mootari I just put in a fix for this. Can you confirm?

**Comment by mootari** [comment]
@jzhang621 Buttons are fixed, but now there's a large gap at the top (will attach screenshot in edit).

**Comment by jzhang621** [comment]
The gap should be fixed now

**Comment by mootari** [comment]
@jzhang621 Not quite, the gap just moved to the bottom ...

![Screenshot_20210824-001739](https://user-images.githubusercontent.com/322014/130526760-55264246-c1b3-4dbc-9251-b634575f679d.png)

**Comment by mootari** [comment]
Btw, you can easily test this yourself by resizing the viewport to a width < 480px.

**Comment by CobusT** [comment]
@mootari please let me know if it works for you now. thanks!

**Comment by mootari** [comment]
@CobusT Looks good now, thanks!
