### ISSUE TITLE
OpenSearch discovery fails in Chome

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#157]
**Describe the bug**

Chrome does not discover Observable's OpenSearch integration.

**To Reproduce**

1. In Chrome, create a new user profile (to get a default configuration and blank history)
2. Open chrome://settings/searchEngines in window A to monitor new search engines in real time. The section "Other search engines" should be empty.
3. Open a new window B alongside window A.
4. In window B, visit https://github.com/ and observe that the search engine gets added immediately.
4. In window B, visit https://observablehq.com/

**Expected behavior**

Observable is listed as a search engine.

**Additional context**

Documentation around OpenSearch is rather poor. However, [Chromium's dev guide](http://dev.chromium.org/tab-to-search) describes the attribute `method="get"` for the `<Url>` element in its minimal configuration example. This attribute appears to absent in [the spec](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md). The attribute is also missing in Discoure's integration and may not be the deciding factor.

Other notable differences:
- ~~Observable does not use the name `opensearch.xml`~~ *So does WIkipedia*
- ~~Observable serves the description from a different subdomain.~~ *ruled out by @Fil*
- ~~excessively long path / file name~~ *ruled out by @Fil*

Detection appears to work in Firefox.

**Comparison of integrations**

<details>
<summary>Observable</summary>

https://observablehq.com/
~~~html
<link rel="search" type="application/opensearchdescription+xml" href="https://static.observablehq.com/opensearch.f0edf865a33006c06bc1209351327a653cf57027d34785baf9b056374b56b85f.xml" title="Observable search">
~~~

https://static.observablehq.com/opensearch.f0edf865a33006c06bc1209351327a653cf57027d34785baf9b056374b56b85f.xml
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>Observable</ShortName>
  <Description>Search Observable for notebooks</Description>
  <Url type="text/html"
       template="https://observablehq.com/search?query={searchTerms}"/>
</OpenSearchDescription>
~~~
</details>

<details>
<summary>GitHub</summary>

https://github.com/
~~~html
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
~~~

https://github.com/opensearch.xml
~~~xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                      xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>GitHub</ShortName>
  <Description>Search GitHub</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image width="16" height="16" type="image/x-icon">https://github.com/favicon.ico</Image>
  <Url type="text/html" method="get" template="https://github.com/search?q={searchTerms}&amp;ref=opensearch"/>
  <moz:SearchForm>https://github.com/search</moz:SearchForm>
</OpenSearchDescription>
~~~
</details>

<details>
<summary>Discourse</summary>

https://talk.observablehq.com/
~~~html
<link rel="search" type="application/opensearchdescription+xml" href="https://talk.observablehq.com/opensearch.xml" title="The Observable Forum Search">
~~~

https://talk.observablehq.com/opensearch.xml
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>The Observable Forum Search</ShortName>
  <Description>Search for posts on The Observable Forum</Description>
  <Tags>discourse forum</Tags>
    <Image type="image/png">https://aws1.discourse-cdn.com/standard14/uploads/observablehq/optimized/1X/ecca8b59c5e8abc6a5559c853e5c63dabdd3e195_2_32x32.png</Image>
  <Url type="application/opensearchdescription+xml" rel="self" template="https://talk.observablehq.com/opensearch.xml"/>
  <Url type="text/html" template="https://talk.observablehq.com/search?q={searchTerms}"/>
  <Query role="example" searchTerms="search term"/>
</OpenSearchDescription>
~~~
</details>

<details>
<summary>Wikipedia</summary>

https://en.wikipedia.org/wiki/Main_Page
~~~html
<link rel="search" type="application/opensearchdescription+xml" href="/w/opensearch_desc.php" title="Wikipedia (en)"/>
~~~

https://en.wikipedia.org/w/opensearch_desc.php
~~~xml
<?xml version="1.0"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
  xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>Wikipedia (en)</ShortName>
  <Description>Wikipedia (en)</Description>
  <Image height="16" width="16" type="image/x-icon">https://en.wikipedia.org/static/favicon/wikipedia.ico</Image>
  <Url type="text/html" method="get" template="https://en.wikipedia.org/w/index.php?title=Special:Search&amp;search={searchTerms}" />
  <Url type="application/x-suggestions+json" method="get" template="https://en.wikipedia.org/w/api.php?action=opensearch&amp;search={searchTerms}&amp;namespace=0" />
  <Url type="application/x-suggestions+xml" method="get" template="https://en.wikipedia.org/w/api.php?action=opensearch&amp;format=xml&amp;search={searchTerms}&amp;namespace=0" />
  <moz:SearchForm>https://en.wikipedia.org/wiki/Special:Search</moz:SearchForm>
</OpenSearchDescription>
~~~

**Comment by Fil** [comment]
I’ve made a controlled experiment on visionscarto.net: when I put “static.visionscarto.net” as the domain of the opensearch.xml link, it doesn’t get added; when I put “visionscarto.net” it gets added. There is no other difference.

**Comment by Fil** [comment]
Same issue with Chromium

**Comment by mootari** [comment]
@Fil was able to narrow it down to an encoding issue. The solution may be to:
- either remove the `encoding` attribute from the XML declaration
- or serve the file with the proper content-type header: `content-type: application/xml; charset=utf-8`

**Comment by Fil** [comment]
Fixed by removing the `<?xml version="1.0" encoding="UTF-8"?>` which was somehow incompatible with the server's headers. Thank you Fabian!

**Comment by mootari** [comment]
As discussed on Slack there's still a minor issue in Firefox due to a mismatch between the link title and the description shortName. However Chrome discovery has been fixed, so I'm closing this issue.

**Comment by Fil** [comment]
the firefox issue is solved too
