### ISSUE TITLE
[Next] Pasting text as guest prompts login

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#159]
**Describe the bug**

As an unauthenticated user, pasting text into a notebook cell opens the login dialog with the prompt "Please sign in to upload files.".

**To Reproduce**

1. Open https://observablehq.com/@observablehq/demo or any other notebook
2. Copy or cut text from the first cell
3. Paste text back into the first cell

The text will be inserted, but is immediately followed by the login modal.

**Additional context**

It makes no difference wether pasting is done via the keyboard or menu.

**Comment by mootari** [comment]
@wiltsecarpenter Has the fix been deployed yet?

**Comment by wiltsecarpenter** [comment]
Yes, fix is deployed now.
