### ISSUE TITLE
Static properties on classes are currently not supported

### ISSUE THREAD

**Issue by JobLeonard** [observablehq/feedback#160]
**Describe the bug**

No worries, I know there's a simple workaround for now (just add the property to the prototype after the class definition), but still: this is technically a bug

The following snippet [comes straight from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#static_methods_and_properties) and uses the correct class syntax to initialize a static property:

```js
class Point {
  constructor(x, y) {
    this.x = x;
    this.y = y;
  }

  static displayName = "Point";
  static distance(a, b) {
    const dx = a.x - b.x;
    const dy = a.y - b.y;

    return Math.hypot(dx, dy);
  }
}
```

However, the observable compiler currently trips over this (it does work for static methods though).

Example: https://observablehq.com/d/bffd1e6e498d8879 (screenshot below for future reference)

**To Reproduce**

1. Type the above class into a javascript cell

**Expected behavior**

Class syntax being in line with official class syntax.

**Screenshots**

![image](https://user-images.githubusercontent.com/259840/128178719-79d6f05d-f8d7-4bc4-affa-35a8ebdaad09.png)

**Comment by mootari** [comment]
Aside: Acorn [added support](https://github.com/acornjs/acorn/pull/1026) in version 8.2.0.

**Comment by mootari** [comment]
Note that the parser also chokes on [private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) which are now supported [in all major browsers](https://caniuse.com/mdn-javascript_classes_private_class_fields).

**Comment by tomlarkworthy** [comment]
it's a bit weird because static functions do seem to work.

**Comment by mbostock** [comment]
This is covered by https://github.com/observablehq/parser/issues/64.
This will be fixed by https://github.com/observablehq/parser/pull/205.

**Comment by mbostock** [comment]
This should be live in a few minutes. Thanks for the feedback!
