### ISSUE TITLE
[Next] Open search page from search modal when pressing Enter

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#161]
**Is your feature request related to a problem? Please describe.**

Observable recently updated the search in the Next UI to display a modal on focus. The modal results update on every keypress.

However, to open the results in a new page, a user has to click a link at the bottom of the modal.

**Describe the solution you'd like**

When a user presses Enter in the modal's search box, redirect to the search page.

**Additional context**

The search box in Classic also displays result suggestions, but opens the results page when pressing Enter. It could be argued that the behavior in Next is a regression.

**Comment by mootari** [comment]
An additional annoyance here is that users have to wait for the first results to appear before they can click the link "View all N results" – where they'll again have to wait for the same results to load before they can perform any meaningful interaction.

**Comment by mootari** [comment]
@CobusT What's the current status of this issue?

**Comment by CobusT** [comment]
We have been looking at this along with designing a new search results page to improve the search experience, but don't have an estimate yet.

**Comment by mootari** [comment]
Would it be possible to resolve this particular issue (namely switching to the results page via enter, without having to wait for the results to load), independently of a redesign of the overall search experience? Implementation wise this seems like a simple fix.

**Comment by CobusT** [comment]
I think that is a good idea. Will update here.

**Comment by CobusT** [comment]
We implemented this. Please let us know if this works for you, too!

**Comment by mootari** [comment]
@CobusT Works beautifully, thank you! A very minor nitpick: The progress bar at the top disappears way too early. Imo it should stay there at least until the page actually changes (even if it's just a full blue bar).

Demo, with network throttled to "fast 3G":

https://user-images.githubusercontent.com/322014/145886668-5dec3f52-92e2-4c95-90e8-9082d6c84e34.mp4

**Comment by CobusT** [comment]
We are switching from Next to Classic at that point (the Search page is still in Classic). When we have the Search page migrated to Next, I think that will behave differently (better).

**Comment by mootari** [comment]
There's a stray 404 request that only happens when pressing enter. First two requests below are in-modal queries, third and fourth get triggered when pressing enter:
![image](https://user-images.githubusercontent.com/322014/145889016-0f6bdf95-dbaf-401c-a105-ae0c07fe33e6.png)

**Comment by visnup** [comment]
That's Next.js attempting to do a client-side navigation to that page and then failing because the search results page is still handled by Classic. It then navigates to Classic using a full page navigation. There's not really any way to suppress that for now until we move the search results page to Next.
