### ISSUE TITLE
Snippets Search Box scrolls offscreen when scrolling for lower snippets

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#162]
**Describe the bug**
There is a search box at the top of the snippets panel. It scrolls offscreen and is not usable if you scroll to get a lower snippet.
**To Reproduce**
1. create  a new notebook
2. click the snippets icon
3. observed the panel -  Search is at top
4. scroll within the panel
5. search scrolls off screen 

**Expected behavior**
Search box should be a "sticky header" which  persists even if user scrolls down.

**Screenshots**
Before scroll
<img width="382" alt="Screen Shot 2021-08-04 at 1 59 52 PM" src="https://user-images.githubusercontent.com/8691/128254385-7baed816-9efa-45bf-afda-e71a2d6f220b.png">

After scrolling a bit
<img width="390" alt="Screen Shot 2021-08-04 at 2 02 47 PM" src="https://user-images.githubusercontent.com/8691/128254478-84c79811-da17-4f9e-9534-920f65189562.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome 
 - Version - latest, doesn't matter

**Additional context**
Inconsistent with other dialogs like  "new notebook" which has a persistent header.

**Comment by CobusT** [comment]
I believe this is now resolved because we don't have a snippets panel anymore :-) 
It has been replaced by the new Add cell menu.
https://observablehq.com/@observablehq/adding-cells
