### ISSUE TITLE
Keep sort criteria when resubmitting search form within results page

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#163]
**Is your feature request related to a problem? Please describe.**

Resubmitting the search form on Observable's [search results page](https://observablehq.com/search?query=notebook) drops the active sort criteria and order.

**Describe the solution you'd like**

Keep the query parameters `sort` and `direction` when resubmitting a search form within a search results page.

**Additional context**

When I change the search phrase within an active search, I do so to refine the results. I still want to maintain the previously selected order (e.g. popularity a.k.a likes).

**Comment by CobusT** [comment]
Ah interesting! Makes sense.

**Comment by CobusT** [comment]
@mootari Please let us know if this is working for you!

**Comment by mootari** [comment]
@CobusT Thanks, looks good!
