### ISSUE TITLE
Accessibility: Tab focus rings inconsistent in header

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#164]
**Describe the bug**
When you tab to focus elements in the header, their  "focus" behavior is inconsistent. Some elements turn blue,  others get a focus ring

**To Reproduce**
1) Go to https://observablehq.com/@observablehq/community-survey
2) click on some whitespace to clear focus.
3) start pressing tab key to focus on header elements
4) observe how 
 - Observable logo : gets a focus ring
 - "Explore" : just turns blue  ? **not consistent behavior**
 - "Learn" : just turns blue ? **not consistent behavior**
 - "Community" : gets a focus ring
 - "Search"  : doesn't get focus at all? **Seems like a significant bug  here.**
 
5) Go to Observable Home page https://observablehq.com/  (logged in)
6) click whitespace to lose focus
7) hit tab a few times
8) Observable logo : gets focus ring
9) **"Explore" and "Learn" are skipped !!**
10) "Community" : gets focus ring
11) "search" : gets focus  and cursor in search box as you would expect (  **Different from Notebook  behavior** !)  

**Expected behavior**
All header link elements should be able to be focused, and have  consistent behavior.
Homepage should not skip elements
Notebook search box should be focusable via tab.

**Screenshots**
<img width="712" alt="Screen Shot 2021-08-04 at 2 23 50 PM" src="https://user-images.githubusercontent.com/8691/128256841-73ba8d5a-0eb4-40f4-a40c-46e9379b9915.png">
<img width="654" alt="Screen Shot 2021-08-04 at 2 24 31 PM" src="https://user-images.githubusercontent.com/8691/128256898-ec7fa6f8-256b-429e-bc0e-dec35dc8436c.png">
Explore is focused here ... it's just blue
<img width="686" alt="Screen Shot 2021-08-04 at 2 25 14 PM" src="https://user-images.githubusercontent.com/8691/128257002-289d8f35-6b47-4336-a963-2a1e7bc9bc5e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Latest

**Additional context**
Seems odd that headers would 1) behave so differently between pages and 2) between elements in the header.

**Comment by triptych** [comment]
Heh, both are busted he he

**Comment by triptych** [comment]
Thanks so much for taking a look!

**Comment by CobusT** [comment]
@triptych This should now be better, but not perfect yet. We will have to look at accessibility across the site more holistically, but thought this particular Bug was worth addressing separately. Please let us know if this works for you.
