### ISSUE TITLE
Require confirmation for "Publish" action

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#17]
**Is your feature request related to a problem? Please describe.**

The notebook action "Enable link sharing" is guarded by a confirmation modal that displays the following warning:

> Enabling link sharing for this notebook will make it visible to anyone with the URL.

The Publish action however is a one-click action, making accidental publishing of internal information possible. Even after immediate unpublishing, the notebook can remain listed and accessible for up to 30 seconds.

**Describe the solution you'd like**

When "Publish" is clicked, display a dialog to confirm that the action is intended.

**Comment by CobusT** [comment]
In Next, we now have a Publish modal that should cover this. We are not planning on adjusting Classic. Please re-open if this solution (in Next) doesn't solve this request.
