### ISSUE TITLE
Search: Inconsistent results for attributes "published", "linkshared" and "private"

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#171]
**Describe the bug**

The publishing related [search attributes](https://observablehq.com/@observablehq/searching-on-observable#cell-2) `is:published`, `is:linkshared` and `is:private` yield inconsistent results.

**To Reproduce**

Tested for my account `@mootari`. Reference counts for each publishing status ("Shared" notebooks were counted manually to exclude other owners):

| Published<br>status | Access:<br>"You" | Access:<br>"Shared" | Total
| - | - | - | -
| "Published" | 146 | 0 | 146
| "Link shared" | 153 | 3 | 156
| "Not published" | 186 | 9 | 195
| "All" |  485 | 12 | 497

Query results:

| authentication | query | results | expected | matching
|-|-|-|-|-
| guest | `owner:@mootari is:published` | 143 | 146 | ❌ 
| guest | `owner:@mootari is:linkshared` | 0 | 0 | ✅
| guest | `owner:@mootari is:private` | 2 | 0 | ❌ 
| guest | `owner:@mootari -is:published` | 2 | 0 | ❌ 
| guest | `owner:@mootari -is:linkshared` | 145 | 146 | ❌ 
| guest | `owner:@mootari -is:private` | 143 | 146 | ❌ 
| owner | `owner:@mootari is:published` | 144 | 146 | ❌  
| owner | `owner:@mootari is:linkshared` | 147 | 156 | ❌ 
| owner | `owner:@mootari is:private` | 200 | 195 | ❌ 
| owner | `owner:@mootari -is:published` | 347 | 351 | ❌ 
| owner | `owner:@mootari -is:linkshared` | 344 | 341 | ❌ 
| owner | `owner:@mootari -is:private` | 291 | 302 | ❌

**Comment by CobusT** [comment]
@mootari Thanks for this in-depth analysis. I tried to do a similar exercise with my notebooks and I do think there are a few bugs (some known and some not...) that needs to be ironed out.
One thing to note (that may explain some of these differences) is that we are not showing forked notebooks with 0 edits in the search results... but they do show up in your notebook listing. That may explain the cases where the actual is less than the expected.

**Comment by CobusT** [comment]
One thing that would be very helpful is if you could look at the` owner:@mootari is:private` case... would it be possible (I know it is a lot to ask!) to try and identify the 5 notebooks that are showing up in search that are not in your notebook listing? In particular, I have a suspicion that they may be team-owned notebooks that somehow show up in the search even though you have owner:@mootari...

**Comment by CobusT** [comment]
@mootari we fixed the document indexing problem.  Would you mind testing this again?

**Comment by mootari** [comment]
@CobusT It's *almost* correct. The notebook https://observablehq.com/@mootari/side-by-side-editor-and-tabs-for-observable is still completely missing from the public search, but is listed when I do an authenticated search for "owner:mootari is:published".

**Comment by CobusT** [comment]
There is something wrong with the search vector for that notebook, which explains why it is not showing up in search, but does show up in your notebook listing. Investigating.

**Comment by CobusT** [comment]
Please let me know if you still see discrepancies.  It should be fixed now.
