### ISSUE TITLE
<style> in embedded notebook stretches document, causes horizontal scrollbar

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#179]
**Describe the bug**

When an embedded notebook contains a `<style>` element as the top-level element of a cell, and any of the element's lines exceeds the viewport width, it will cause a horizontal scrollbar to appear for the document.

**To Reproduce**

1. Create an HTML cell with a `<style>` element, add a long line of text inside the element.
2. Link-share notebook.
3. Open Export > Embed cells (ensure that "Entire notebook" is selected).
4. Note horizontal scrollbar at the bottom of the embed preview. Entire embedded notebook can be scrolled horizontally.

**Expected behavior**

No horizontal scrolling.

**Additional context**

The embed stylesheet is missing rules that are present in the editor sandbox stylesheet:
```css
.observablehq>style:only-child { overflow-x: auto }
```

**Comment by mootari** [comment]
For a practical example of the bug see https://observablehq.com/embed/@hastebrot/typography?cell=*

**Comment by CobusT** [comment]
Actually, it is still not correct after making that change. It may be that prod is caching something... let me wait a bit and see if it fixed

**Comment by CobusT** [comment]
OK, looks like this is actually fixed now. Phew.
