### ISSUE TITLE
[Next] "< >" icon for HTML cell mode deviates from convention "</>"

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#181]
**Describe the bug**

The mode icon for the "HTML" cell mode shows `< >`, even though HTML/XML icons commonly use `</>`. This also makes the icon shape less distinguishable from the "JavaScript" cell mode icon `{ }`, especially at small sizes.

Note that `< >` is often used to represent code in general, e.g. in the [Material Icons](https://fonts.google.com/icons?selected=Material+Icons&icon.query=code).

**Expected behavior**

Update the HTML cell mode icon to display `</>`.

**Screenshots**

![image](https://user-images.githubusercontent.com/322014/129489488-bce4708a-26a9-4a9b-8e74-104b4ffa62e3.png)

**Additional context**

I rarely use other cell modes and got genuinely confused for a moment wether the correct cell mode was active.

**Comment by mootari** [comment]
This may be not as clear-cut as I made it out to be: Both `< >` and `</>` are popular choices to represent "code". For "HTML" however `</>` appears to be more popular (although the HTML5 icon appears even more often).

Regardless, I think the argument for a more readable icon shape still stands.

**Comment by CobusT** [comment]
I think we will close this one. :-)
