### ISSUE TITLE
[Next] Slow performance of code editor on large notebooks

### ISSUE THREAD

**Issue by jurb** [observablehq/feedback#182]
While editing [this admittedly huge notebook](https://observablehq.com/@jurb/analyse-jeugd-masterplan-zuidoost) in next mode, I experience almost a second of lag between pressing a key and seeing the cursor move when editing any cell. 

When using `?ui=classic`, everything is snappy.

I'm on the latest macOS update, and experience this with the latest Safari and Chrome update.

**Comment by mootari** [comment]
I'm starting to get noticable delays with a lot less cells. In this case 27 cells, at a total of 460 lines of code.

---

To get those metrics, open your notebook in classic UI safe mode (append `/safe?ui=classic` to the URL), then run the following commands in the Developer Tools console (make sure that "top" is the browsing context):
- number of cells: `$$('.CodeMirror-code').length`
- number of lines: `$$('.CodeMirror-line').length`

**Comment by CobusT** [comment]
Thanks @mootari. This is definitely something we are looking into.

**Comment by CobusT** [comment]
We released a number of performance fixes today... I tested my own long notebooks and the one you mentioned here, and feel that the response time issue is now fixed. Would you mind retesting and closing this if you agree?

**Comment by jurb** [comment]
Perfect, everything feels nice and snappy again for me. Thanks!
