### ISSUE TITLE
Button CSS is not vertically aligned

### ISSUE THREAD

**Issue by abitrolly** [observablehq/feedback#185]
**Describe the bug**

On the https://observablehq.com/@mbostock/file-input page.

![image](https://user-images.githubusercontent.com/8781107/130499247-5c943f9f-6a59-4c63-9d98-32f866c77b5b.png)

The `Submit` `<button>` is located higher that other form elements on the line, because it is missing `vertical-align: middle;` style that is present for other elements that are using `<input>` tag.

**Comment by CobusT** [comment]
I tested this on MacOS in Safari and Chrome, and on Windows using Edge, and I don't see this alignment problem. Can you please let us know what platform and browser you are using?

**Comment by CobusT** [comment]
Thanks. I was able to reproduce this in Firefox. I forked the notebook and made the style change and suggested the change back to the author (Mike). He will merge that change into his official notebook if he agrees with the fix.

In future, you could try that flow yourself (especially since you figured out the fix!)

Thanks again.

**Comment by abitrolly** [comment]
@CobusT this fixes just one notebook, but doesn't fix all other forms in the wild. I thought about update of Observable CSS, but I am not sute if it is open source.

**Comment by CobusT** [comment]
@abitrolly Thanks for pushing for this. Fixed the CSS.

**Comment by abitrolly** [comment]
Niiice. I can't see the fix #4187. Suppose it is in private repo. Whatever. Good it is fixed.

**Comment by CobusT** [comment]
Yup, private repo. But hopefully you can see the results of the fix in your notebooks :-)

**Comment by abitrolly** [comment]
Definitely. )
