### ISSUE TITLE
Live public view of a notebook.

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#190]
I was just watching @visnup and @tophtucker [live stream on twitch](https://www.twitch.tv/videos/1131255240) And a comment made sounded really good.  It was having the ability to share a live view of the notebook. That mode could block editing/comments (but not forking).
This would make streaming of live coding  so people can view the coding sessions better.  

I guess it could be done by having a special share person called 'public'
It would be like sharing a notebook with a user for pair programming.
The 'public' user would only see the live notebook changes and not be able to interact with the notebook.

Having the ability for the public copy cell links would make it also useful for streaming as that link could be shared in steam as a question or help about a bit of code.

**Comment by CobusT** [comment]
This is now possible using public notebooks.
