### ISSUE TITLE
[Next] Editor toolbar hides error marker in last line

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#193]
**Describe the bug**

If an editor contains an error marker at the beginning of its last row, the marker is covered by the toolbar. This happens primarily when the last line of code contains `}`, and the code produces `SyntaxError: Unexpected token`.

**To Reproduce**
1. In Next, create a cell with the following content:
   ~~~
   {
     function
   }
    ~~~
2. Save the cell.
3. Try to find the error marker. (Hint: It's barely visible behind the toolbar.)

**Screenshots**

![image](https://user-images.githubusercontent.com/322014/131230186-2162f182-08f3-43fe-80ea-41417627ee72.png)

**Desktop (please complete the following information):**
- Chrome 92 / macOS 10.13

**Additional context**

Related: https://github.com/observablehq/feedback/issues/116

**Comment by CobusT** [comment]
We now moved the cell toolbar to the bottom of the screen (fixed position) to clear up the congested space around cells. Hope you like that change!
