### ISSUE TITLE
[Classic] Compare: Button "Notebook actions" covers dropdown "Comparison options"

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#196]
**Describe the bug**

When comparing two notebook versions in the classic UI, the "Comparison options" dropdown is covered by the notebook actions button.

**Screenshots**

<img width=300 src="https://user-images.githubusercontent.com/322014/131264884-00e6b1ad-98a1-4421-88e0-30d04ee5edb9.png"> <img width=240 src="https://user-images.githubusercontent.com/322014/131264908-2ef350fa-a588-401d-9e81-316e278fff44.png">

**Comment by CobusT** [comment]
Since this is a minor bug in Classic (which we plan on retiring), we won't plan on fixing this. Sorry!
