### ISSUE TITLE
Accessing ?ui=classic as guest forces Sign In

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#197]
**Describe the bug**

Unauthenticated users can no longer access notebooks in the classic UI.

When an unauthenticated user opens a notebook with the `?ui=classic` suffix, the notebook becomes visible for a brief moment (with the classic UI), but is then immediately replaced by Observable's frontpage, with the Sign-In modal open (without updating the window's location).

**To Reproduce**

1. While logged out, go to e.g. https://observablehq.com/demo?ui=classic

**Expected behavior**

The notebook can be accessed in the classic UI.

**Comment by visnup** [comment]
Should be fixed in an imminent deploy.

**Comment by visnup** [comment]
Deployed and verified fix.
