### ISSUE TITLE
[Next] Default CSS breaks pre/code formatting in table cells

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#198]
**Describe the bug**

Observable's default styles in Next define the rule:
~~~css
table pre, table code, table tt {
  font: inherit var(--monospace-font);
}
~~~
This causes any `<pre>` or `<code>` element inside a table to be displayed in the default sans-serif font defined for tables.

**To Reproduce**

1. In the classic UI, create a notebook with the following cell:
   ~~~javascript
   html`<table>
    <tr><td>ijkl</td></tr>
    <tr><td><pre>ijkl</tr>`
   ~~~
2. In the cell output, make note of the different font formatting in the first and second row.
3. Switch to Next.

In Next, both the first and second row are displayed in the same sans-serif font, at the same size.

**Expected behavior**

No regression in Next.

**Screenshots**

<img width=500 src="https://user-images.githubusercontent.com/322014/131267430-16b03643-55f1-4bd0-9e60-ac4517b66c38.png">

**Comment by CobusT** [comment]
This is now fixed.
