### ISSUE TITLE
Number of likes has disappeared from profile pages

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#2]
**Describe the bug**
The number of likes on profile pages has disappeared after the latest feature update to profiles.

**To Reproduce**
1. Go to an author's profile page
2. Try to find their total number of likes

**Expected behavior**
I see the number of likes.

**Screenshots**
![image](https://user-images.githubusercontent.com/322014/108556145-dbcb7f00-72f6-11eb-98c7-7d49330f9a56.png)

**Additional context**
- To me, likes are an important metric to judge wether I should explore an author's notebooks more thoroughly.
- If this was inspired by Instagram's change, please be aware that there's a vast number of differences between the two platforms and their audiences.
- If you're worried that new users may be discouraged by those numbers: I don't think it's a contest, but you can alternatively display ballpark numbers, like "100+ likes", or "1000+" likes. After a certain amount the precise number becomes largely irrelevant anyway.

**Comment by jrus** [comment]
FWIW, I prefer to keep those off. I don't think people trying to optimize their total like count or comparing people based on total like count is productive/healthy.

**Comment by mootari** [comment]
> I don't think people trying to optimize their total like count or comparing people based on total like count is productive/healthy

What makes you think that this is happening? Likes have been displayed on profile pages since the early days of Observable, and have only been removed in the last update.

**Comment by jrus** [comment]
I didn't ever realize that feature existed. However, it is a relief to me that it now does not.

**Comment by mootari** [comment]
That sounds like personal preference, not an objective reason.

**Comment by jrus** [comment]
Adding 'gamification' features has the general tendency to subvert people's motivation, but this typically is unrecognized or underestimated because it is difficult to measure in comparison with 'engagement'.

**Comment by mootari** [comment]
> Adding 'gamification' features

Again, this issue is about *restoring* a feature that has been available since the start. A feature that you didn't even know existed.

**Comment by jrus** [comment]
I strongly dislike the tone of this conversation. I don't think it would be healthy or productive to continue along the track it is headed down.

I hope that people building social systems keep the potential side effects of their 'gamification' features in mind when deciding what to include.

**Comment by mootari** [comment]
I share your concerns about gamification in general, but I fail to see how these may apply to Observable with its current system and community. Unfortunately you also didn't address the points that I made in "Additional context", which leads me to believe that you're arguing against something that wasn't suggested by this issue.

> The still-included per-notebook 'likes' feature has significant negative side effects for authors and readers

Can you elaborate how these significant negative side effects show themselves?

**Comment by jrus** [comment]
> how these significant negative side effects show themselves?

Authors spend their attention and emotional energy tracking the likes on their published work, and are emotionally affected by the number of likes their posts receive. Authors decide what to work on based on what will get the most likes rather than intrinsic goals. Readers see the like counts of popular works and compare themselves negatively to the authors. Etc.

If you want recent scholarship, I'm sure a lot has been written about facebook likes. Or in a more work-focused context, about citation counts and "impact factor" etc. among academic researchers. These systems of external validation have significant effects on people's feelings and behavior.

**Comment by mootari** [comment]
Perhaps @cassandraoid can share some background on the removal:
- Was it an oversight of the redesign? [The endpoint](https://api.observablehq.com/user/@fil/stats) is still available, so it would seem fairly inexpensive to add the information back.
- If it was a deliberate choice, would the team be willing to share their reasoning, so that we can take away lessons for our own projects?

**Comment by cassandraoid** [comment]
@mootari thanks for surfacing this. @jzhang621 & @dunstan could you give some insights on Fabian's questions per the 'likes' on an Authors page?

> * Was it an oversight of the redesign? [The endpoint](https://api.observablehq.com/user/@fil/stats) is still available, so it would seem fairly inexpensive to add the information back.
> * If it was a deliberate choice, would the team be willing to share their reasoning, so that we can take away lessons for our own projects?

**Comment by dunstan** [comment]
Hi again. It wasn't an oversight. We removed them for the reasons that @jrus suggested, which is to say an easing away from promoting things that have a good chance of negatively effecting people's behavior and enjoyment here. Hopefully the profile page will become more useful over time and make up for that small loss of signal that you're used to looking for.

**Comment by mootari** [comment]
I've been using https://observablehq.com/@mootari/sortable-notebook-list almost exclusively to discover new authors and their notebooks (sorting by likes and comments, e.g.), so the loss is manageable for me. :)

@dunstan If there are some resources that you referred to for your decision making process (e.g. papers, articles), could you perhaps share them here (or in Slack)? I'd love to catch up with the current state of research in this area.
