### ISSUE TITLE
"Download Code" bundle is not working with SVG FileAttachment image

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#202]
**Describe the bug**

notebook
https://observablehq.com/@tomlarkworthy/dataeditor@759

on version 759 does not work when exported (Download Code). The issue is with the SVG fileattachment.

![image](https://user-images.githubusercontent.com/1848162/132009292-d6819d56-7c4a-4722-acd7-3226c0970513.png)

note: I will attempt to fix by referencing the SVG in a different way, so note it will probably work unless you explicitly export v759

Cell that introduces problem is
```
handle = {
  const template = document.createElement('template');
  template.content.appendChild(
    await FileAttachment("drag_indicator_black_24dp.svg").image()
  );
  return () => template.content.cloneNode(true);
}
```

**Expected behavior**
Exported notebook should work.

**Screenshots**

**Desktop (please complete the following information):**
Desktop/Chrome

**Comment by tomlarkworthy** [comment]
I fixed the immediate problem but refrencing the SVG later also causes a MIME type guessing problems. I boiled it down to an minimal repro

This is what I see when I locally host

![image](https://user-images.githubusercontent.com/1848162/132023502-41df9c96-610a-40f2-936c-c7c19bfbcd80.png)


This is the source

https://observablehq.com/d/2dd5bad5c5ed0fc9

Note using FileAttachment.image() doesn't update its filename on export properly (real BUG 1)

But even if I work around that issue by using FileAttachment.url(), the system cannot guess the mimetype becuase the filename has lost its extension. (not really a bug but maybe a FR would be to be able to set the file extension on export? in the FileAttachment panel?)

**Comment by tomlarkworthy** [comment]
So my working work around is to just put the SVG in the notebook as a html`...svg...` literal.

**Comment by mootari** [comment]
To summarize the problem:
- FileAttachment methods rely on fetch().
- The fetch Response adopts the MIME type as returned by the server.
- `<img>` requires a MIME type to determine, well, the type of image (e.g. SVG). Attempting to use an SVG as `src` without the proper MIME type will fail.
- Observable's infrastructure returns the proper MIME type based on the original filename extension.
- In an export all extensions are absent. A local server (like `http-server`) has no way of determining the MIME type, causing fetch to default to "text/plain".

Imo the only sensible workaround is, as sugggested by Tom, to append the original file extensions to the exported file names.

**Comment by mootari** [comment]
The following helper can be used as an ugly workaround to derive a new FileAttachment with a forced MIME type:
```js
async function overrideType(fileAttachment, type) {
  const blob = new Blob([await fileAttachment.arrayBuffer()], {type});
  return new fileAttachment.constructor(URL.createObjectURL(blob), fileAttachment.name);
}
```
Examples:
```js
overrideType(FileAttachment("drag_indicator_black_24dp.svg"), 'foo/bar')
  .then(f => f.blob())
  .then(b => b.type)
```

```js
overrideType(FileAttachment("drag_indicator_black_24dp.svg"), 'image/svg+xml')
  .then(f => f.image())
```

**Comment by CobusT** [comment]
It does seem like adding the extension to downloaded attachments would work...
