### ISSUE TITLE
merge workflow does not render on mobile

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#204]
**Describe the bug**

topmenu overlaps (oneplus 6t chrome)

![Screenshot_20210905-120004](https://user-images.githubusercontent.com/1848162/132122893-d2f395fc-a3bd-484f-96bb-9df5ea2d2f40.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CobusT** [comment]
We made a number of fixes to the mobile layout of the 'compare' banner, and it appears to be fixed for out test cases. Please re-open if you still see a problem. Thanks for raising this!
