### ISSUE TITLE
a link to fill a webpage with a single cell output on observablehq

### ISSUE THREAD

**Issue by jrus** [observablehq/feedback#21]
**Problem statement:** There are many interesting kinds of UI experiments/experiences that can be implemented when code has use of the whole browser window, not only the content inside an iframe surrounded by platform chrome. For example, experiences that futz with browser scrolling, scroll horizontally, or tile elements horizontally wider than 954 pixels are all currently impossible from within Observable.

**Proposed idea:** It would be neat to be able to make up some kind of link which would point directly at a single notebook cell, and would load it to fill the whole browser window, without rendering other cells, cell editors, or other platform chrome (but still running any dependencies of the target cell).

**Current workarounds:** This can be sort of achieved by making the cell take up the whole screen. It can also be done by embedding the notebook on an external website.

**Comment by jrus** [comment]
As one example, this could be used to build and experiment with a book navigator UI as requested in https://github.com/observablehq/feedback/issues/20 which could render a hierarchical table of contents at left and individual constituent notebooks to the right.

**Comment by mbostock** [comment]
Can you use an /embed link?

https://observablehq.com/embed/@d3/treemap?cell=chart

**Comment by jrus** [comment]
I haven't played with the /embed links. Quite possibly!

**Comment by CobusT** [comment]
@jrus Did you have a chance to look at using the /embed method?

**Comment by CobusT** [comment]
Closing since the /embed link should work. @jrus, please review and re-open if you agree.
