### ISSUE TITLE
Cell mode cannot be changed in new non-empty cells

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#210]
**Describe the bug**

If a newly created cell already has content, but has not been saved yet, then its cell mode options cannot be accessed.

**To Reproduce**

1. Add a new cell (without typing or saving it). Make note of the cell mode selection.
2. Type content into the cell. Note that the selection disappears. On the left, the cell options symbol is visible where the cell modes symbol will later appear.
3. Save the cell. The cell options symbol moves up beside the cell output, making room for the cell modes symbol which is now accessible again.

**Expected behavior**

Cell mode selection remains accessible while typing in unsaved cells.

**Additional context**

On several occasions I've started typing markdown into a new cell without remembering to change its mode first. In all instances I was irritated that I could no longer change the cell mode.

**Comment by triptych** [comment]
I run in to this all the time. I'll be typing in Markdown mode in my head (but  didn't change the mode from JS ),  and I have to actually submit it in JavaScript mode, see the error, then I can switch it in the UI to Markdown.

**Comment by tophtucker** [comment]
Fixed!

<img width="249" alt="D71EDB35-D270-4C1E-BF19-CC19C5DE7C80-953-0001D09237C68C06" src="https://user-images.githubusercontent.com/841829/167743323-20961c0a-b843-410f-a100-6d8738de808d.png">
