### ISSUE TITLE
Clickable area on footer popup close button offset to the left

### ISSUE THREAD

**Issue by natalyjazzviolin** [observablehq/feedback#211]
**Describe the bug**
The clickable area on the X (close) button of the footer pop-up is offset to the left. When clicking on the X nothing happens, have to move mouse considerably to the left to click the button and close the popup. 

**To Reproduce**
1. Go to https://observablehq.com/@d3/learn-d3
2. Click on the 'Close welcome message' button
3. See error

**Expected behavior**
When the X is clicked, the footer popup should close.

**Screenshots**
Unable to include mouse pointer in screenshots. Screen cap: 

https://user-images.githubusercontent.com/65251165/132748591-4160c474-e568-45da-911d-2716ed6d98ca.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by mootari** [comment]
@CobusT This happens when the area of the sidebar container overlaps the button.

**Comment by CobusT** [comment]
Should be fixed now. Thanks for raising it.
