### ISSUE TITLE
Size Total of all attached files.

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#213]
Having a total size of all files attached would be useful when there are a lot of files.

<img width="976" alt="Screenshot_24" src="https://user-images.githubusercontent.com/121805/132933958-641c226f-6f66-4900-b68f-03ec27e50d03.png">

**Comment by triptych** [comment]
Yes, especially if you are getting close to the max -  the only way to know is to calc yourself or wait for the site to return  an error.

**Comment by CobusT** [comment]
> Yes, especially if you are getting close to the max - the only way to know is to calc yourself or wait for the site to return an error.

Note: There is no max on total files, as long as they are <50 MB each, and as long as you don't go over your rolling quota of uploading up to 1GB over a 28 day period.

**Comment by grant** [comment]
Thanks for the feature request @hellonearthis. I recently (just now) added this feature.

Let us know if there are any other questions / FRs.

**Comment by hellonearthis** [comment]
Thanks @grant
