### ISSUE TITLE
counter-intuitive MD parsing 

### ISSUE THREAD

**Issue by Guillaume-Levrier** [observablehq/feedback#215]
**Describe the bug**
Observable's MD parsing is overly dependent on indentation, which can lead to numbered list mix-ups.

**To Reproduce**
1. Create an observable cell
2. Make it an MD cell
3. Create the following list

> 1. this is the first item
> - this is supposed to be first sub-item of the first item
> 2. This is the second item
> - this is the first sub-item of the second item

**Expected behavior**

My expected result would be this:

1. this is the first item
- this is supposed to be first sub-item of the first item
2. This is the second item
- this is the first sub-item of the second item 

Instead, what I get is this
1. this is the first item
2. this is supposed to be first sub-item of the first item
3. This is the second item
4. this is the first sub-item of the second item 

There is an easy "fix" : my expected result is reached by indenting the bulleted-lists. The indentation shouldn't be necessary though.

**Screenshots**
<img width="398" alt="Screenshot 2021-09-11 at 10 27 01" src="https://user-images.githubusercontent.com/18345966/132948721-dee33ba3-c3d2-4048-9f44-9c963eb087fe.png">
<img width="314" alt="Screenshot 2021-09-11 at 10 28 25" src="https://user-images.githubusercontent.com/18345966/132948724-99cdf252-420a-4d77-8872-9e2408fceeb0.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Chrome
 - Version: 93.0.4577.63

**Comment by j-f1** [comment]
According to [babelmark](https://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+this+is+the+first+item%0A-+this+is+supposed+to+be+first+sub-item+of+the+first+item%0A2.+This+is+the+second+item%0A-+this+is+the+first+sub-item+of+the+second+item+%0A), a website that lets you run many Markdown parsers on the same piece of code, only 2 programs produce your desired output. The others either match Observable or GitHub. To make nested lists, you need to indent the sub-lists, although the precise amount of indentation required varies between implementations.
