### ISSUE TITLE
Menu links don't work while search suggestions are open

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#216]
**Describe the bug**

When the suggestions dropdown below the search box is visible, menu dropdown will still respond to mouseover. Clicking any link in a menu dropdown closes it, but does not cause navigation to the link's target. 

**To Reproduce**
1. Type "abc" in the search box and wait for the suggestions to appear.
2. Hover over a menu item, e.g. "Explore" or "Learn".
3. In the appearing dropdown, click any link.

**Expected behavior**

The browser navigates to selected page. Instead, the click causes the suggestions to close.

**Screenshots**

<img width=400 src=https://user-images.githubusercontent.com/322014/132959707-1961c64f-02a0-4acc-9a4f-d829af093ec7.gif>

**Comment by CobusT** [comment]
The Next UI (which is now the standard) does not have this problem, since the Search 'dropdown' is replaced by a search modal window.
