### ISSUE TITLE
[Next] Make cell shortcuts available in Next

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#217]
**Is your feature request related to a problem? Please describe.**

Observable's Classic UI offers [cell shortcuts](https://observablehq.com/@observablehq/cell-shortcuts) (aka "visual mode"), which allow users to modify multiple cells simultaneously.

The feature has not yet been ported to Next. This FR serves as a public tracking issue that users can subscribe to.

**Comment by CobusT** [comment]
This is now supported, see https://observablehq.com/@observablehq/release-notes#cell-934
