### ISSUE TITLE
Add MongoDB Database Support

### ISSUE THREAD

**Issue by mullojo** [observablehq/feedback#221]
I'm leaving a **new feature request** here after writing support.  It would be great if MongoDB was a supported database for notebook connections.

I use MongoDB with Meteor.js and I'd be happy to tell the whole Meteor community if Observables adds support for MongoDB.   We all have lot's of data that would be fun to access in Observables notebooks for fast exploration & data visualizations.

Data from MongoDB is always easy to work with in JavaScript, so it makes a perfect fit.  **MongoDB is the most popular NoSQL database with about 15 million downloads from a quick Google search.**  

![image](https://user-images.githubusercontent.com/13399332/134071076-053c6ce2-e9c2-4222-bcfd-2eeb8af1efdf.png)

**Comment by CobusT** [comment]
We now have MongoDB support!
see https://observablehq.com/@observablehq/release-notes#cell-2961
