### ISSUE TITLE
Feature Request: all official Observable templates should have licenses

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#226]
**Is your feature request related to a problem? Please describe.**
This feature: https://observablehq.com/templates
Encourages users to fork these notebooks and use them. 
However, none of these notebooks have licenses?
If you want to encourage folks to publish notebooks and share them - your own blessed notebooks aught to have the correct licensing so folks feel comfortable using them.

For example https://observablehq.com/@observablehq/interactive-html-canvas --> no license showing.

**Describe the solution you'd like**
Update all official Observable template notebooks with an appropriate license.

**Describe alternatives you've considered**
I  am trying  to use this feature more often myself.

**Additional context**
Official notebooks from Observable should have all the attributes that the site wants to encourage users to do themselves on their own notebooks. Not having licenses on these notebooks that are intended to be forked seems like an oversight. Plus someone might hesitate to use them if they  don't know  the license.

**Comment by CobusT** [comment]
This is now taken care of. Thanks again.

**Comment by triptych** [comment]
That's really awesome, actually! Thank  you!
