### ISSUE TITLE
Feature Request: Add links to Observable employees listed in About page

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#227]
**Is your feature request related to a problem? Please describe.**
I was browsing the About page --> https://observablehq.com/about
And I was super surprised to see the list of employees did not provide links to their Observable profiles.

**Describe the solution you'd like**
For every Observable person listed in the  about page ( https://observablehq.com/about ) make their profile link to their Observable profile  ( unless of course that person doesn't want that ) 

**Describe alternatives you've considered**
I have to search Observable  for their name, and that's no guarantee I'll find the right person...

**Additional context**
I can understand not listing their email address, or other personal information, but there should at least be links to these folk's Observable profiles... 

<img width="1356" alt="Screen Shot 2021-09-21 at 3 27 16 PM" src="https://user-images.githubusercontent.com/8691/134256006-7c846657-6aa6-47a2-9dd4-b906ada5ac4e.png">

**Comment by CobusT** [comment]
Great idea!

**Comment by CobusT** [comment]
After further discussions, we decided to keep our team members' personal activities separate from their professional profiles on our About page. Thanks for the thought, though!

**Comment by triptych** [comment]
No worries! Thanks for considering it.
