### ISSUE TITLE
Improve the UX for sharing a private notebook link

### ISSUE THREAD

**Issue by saraquigley** [observablehq/feedback#229]
**Is your feature request related to a problem? Please describe.**
Our team has made a lot of progress creating notebooks and analyzing data and are beginning to privately share our work within the enterprise. This particular notebook describes how we've encountered some UX issues when sharing private notebook links with team members.

Let's say I have been working on a notebook and that I have already shared with a team member, and I comment on the notebook. My team member is an occasional user and is not already logged into Observable. An email is generated and sent to my colleague. 

![image](https://user-images.githubusercontent.com/590828/134547790-aebdbf0b-774c-4598-9a0f-859dee3967b5.png)

My colleague follows up with me about the link because when he clicked the View comment button, he was taken to a page that says:  "Sorry, we couldn't find that page."

![image](https://user-images.githubusercontent.com/590828/134547869-1fbe2e40-5210-42a5-85b8-f943955a25f6.png)

**Describe the solution you'd like**
Would it be possible to redirect to the Sign up / sign in dialog instead?

![image](https://user-images.githubusercontent.com/590828/134547951-56677e39-85a9-4c7e-a0e1-603eb950b37a.png)

**Describe alternatives you've considered**
I've attempted to proactively prevent this issue by describing how to ignore the "Sorry, couldn't find that page" message and log in with Google, but I still get questions from email recipients who are confused that the page could not be found.

![image](https://user-images.githubusercontent.com/590828/134548205-056da494-48bc-45ac-b147-80eac93cbed4.png)

**Additional context**
This is a pretty big issue for us as we begin to share notebooks across campus and we would very much rather not have to spend time helping up to 100 people who respond that the shared link is broken.  

Thanks for your help!

**Comment by CobusT** [comment]
OK, we just deployed a fix for this. When someone is not logged into Observable and clicks on a link to take them to a notebook that is not public, they will see a login prompt.
Thanks for raising this!

**Comment by saraquigley** [comment]
Awesome, thank you so much Cobus and team!  I can confirm that the new
behavior is working now you described for me (when I use Chrome in
incognito mode.)  Have a great evening.

Sara
