### ISSUE TITLE
New Discourse menu causes horizontal scrolling in narrow viewports

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#23]
**Describe the bug**
The recently introduced menu at https://talk.observablehq.com/ is not optimized for mobile displays:
- If the viewport is narrower than 909px, a horizontal scrollbar will appear.
- On mobile screens, the login button, notification menu and burger menu in the top right corner can only be accessed after scrolling the page to right side.

**To Reproduce**
1. Open https://talk.observablehq.com/ on a mobile phone or tablet with a horizontal resolution of less than 909 CSS pixels.
2. Try to locate the burger menu in the top right.

**Expected behavior**
The menu collapses into, or is replaced by, a mobile-friendly version that keeps the burger menu within the viewport.

**Screenshots**
![scrolling viewport](https://user-images.githubusercontent.com/322014/109426680-2a5fd400-79ef-11eb-8308-feef126800b4.gif)

**Comment by waynesutton** [comment]
Thanks @mootari  fixed!
![Image from iOS](https://user-images.githubusercontent.com/720186/109724524-9283f680-7b64-11eb-8d04-4d80a7531e79.jpg)
