### ISSUE TITLE
Keyboard shortcuts don't seem to work on new editor

### ISSUE THREAD

**Issue by steren** [observablehq/feedback#234]
[This page](https://observablehq.com/@observablehq/keyboard-shortcuts) lists many keyboard shortcuts.

For example `J` and `K`

I can use them fine in the "classic" Editor. But not in the new editor.

**Comment by mbostock** [comment]
Thanks for the feedback, @steren. The j/k shortcuts are part of the “cell shortcuts” or “visual mode” feature which has not yet been ported to Next, but is covered by #217. If there are other keyboard shortcuts that you find missing, please let us know.

**Comment by steren** [comment]
Thanks, I'd recommend calling out on the keyboard shortcut page which ones do not apply yet to the Next editor

**Comment by mbostock** [comment]
Done. Thanks for the suggestion.
