### ISSUE TITLE
Unclear if/how I can create a new variable inline of markdown

### ISSUE THREAD

**Issue by steren** [observablehq/feedback#235]
I'd like to write something line this in markdown:

```
to send all power , we need ${num_laser = Math.ceil(panel_power_per_m2 / laser_power)} lasers
```

In order to re-use the `num_laser` value later.

It seems the only way to do so is to create a JS block with `num_laser = Math.ceil(panel_power_per_m2 / laser_power)`. 

Adding a new block has the drawback of breaking the flow of my text.

**Comment by mbostock** [comment]
To expose a named value to other cells in Observable, you must define it as a separate cell. I don’t expect we’ll change this because the flat list of cells is fairly core to the design of Observable at this point, and because it ensures that all cell values are inspectable, but thank you for the feedback and we’ll keep it under consideration.

**Comment by CobusT** [comment]
I usually put these cells at the bottom of my notebook to avoid breaking the flow of my markdown cells.

**Comment by mbostock** [comment]
Yep! I should have mentioned that but I forgot because it’s so internalized. Cells can be in any order. (See [How Observable Runs](https://observablehq.com/@observablehq/how-observable-runs).)

**Comment by steren** [comment]
I understand. 

See this [twitter thread](https://twitter.com/steren/status/1442010098482626563) for more context about why I was looking to do this: I was hoping to be using Observable as a "Google docs but with variables and formulae".

I think it can still be used for my use case of exploring an idea that requires some maths, but the block structure feels distracting, both to the writer (put me out of the flow because I need to switch between markdown and JS modes, and potentially move up / down the page) and the reader (if blocks are inline, they break the structure, if blocks are at the bottom, they don allow to easily see the formula behind a variable)

**Comment by mbostock** [comment]
You can do inline stuff, it’s just more work. E.g. https://observablehq.com/@mbostock/tangle

**Comment by steren** [comment]
Oh nice. https://observablehq.com/@mbostock/tangle indeed implements some of the UX I was hoping for readers to tweak parameters (today I'm using sliders, which also bring unnecessary breaks for value inputs)

If blocks are core to Observable's design, I suggest we close this feature request.
