### ISSUE TITLE
feature request:  Update Fileattachment.zip notebook with .xlsx example

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#239]
**Is your feature request related to a problem? Please describe.**
It might not be obvious to people that the new .xlsx parsing feature works for files in a zip archive.
For example https://observablehq.com/@triptych/testing-compressed-xlsx-files

**Describe the solution you'd like**
Update the https://observablehq.com/@observablehq/zip notebook to include a .xlsx example like you do for images, text, etc.

**Describe alternatives you've considered**
I created a test notebook to  make sure it worked https://observablehq.com/@triptych/testing-compressed-xlsx-files
**Additional context**

**Comment by justin-nw** [comment]
Added a new section to FileAttachment.xlsx() describing this and also edited FileAttachment.zip() to explicitly state that an .xlsx file can be accessed (linked to FileAttachment.xlsx() as well).
