### ISSUE TITLE
feature request: correct metadata in collections ( for social sharing ) 

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#246]
**Is your feature request related to a problem? Please describe.**
When I share a Notebook to say Twitter - the metadata in the head gives Twitter what it needs to make a card-->
( https://observablehq.com/@anjana/data-viz-for-web-devs ) 
```
<meta charset="utf-8">
<link rel="canonical" href="https://observablehq.com/@anjana/data-viz-for-web-devs">
<link rel="icon" type="image/png" href="https://observablehq.com/favicon-512.png" sizes="512x512">
<link rel="apple-touch-icon" href="https://observablehq.com/favicon-512.png">
<title>Data Visualization for Web Developers / Anjana Vakil / Observable</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="prefetch" href="https://cdn.jsdelivr.net/npm/marked@0.3.12/marked.min.js" crossorigin="">
<meta charset="utf-8">
<link rel="canonical" href="https://observablehq.com/@anjana/data-viz-for-web-devs">
<link rel="icon" type="image/png" href="https://observablehq.com/favicon-512.png" sizes="512x512">
<link rel="apple-touch-icon" href="https://observablehq.com/favicon-512.png">
<meta name="next-head-count" content="7">
```
(Notice also the title is descriptive of the notebook)
(Is there a bug that you have duplicate header stuff in there?)

But I noticed when I tried to share a collection, a lot of that metadata is missing  -->
(https://observablehq.com/collection/@anjana/data-viz-for-web-devs)
```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="google-site-verification" content="Cb1i2q7oVgeeYvCfXyzou6YrKo5cPOGleoeIojAGqLM">
<meta name="description" content="Discover insights faster and communicate more effectively with interactive notebooks for data analysis, visualization, and exploration.">
<meta name="twitter:card" content="summary">
<meta property="og:description" content="Explore and visualize data. Share and publish your insights. Discover and be inspired.">
<meta property="og:image" content="https://static.observablehq.com/summary.fda06e4bebc0fc81df1e8b01b8f720476c183dd808e1a34bc8bd8bf074f134eb.png">
<meta name="twitter:image:alt" content="Observable logo">
<link rel="preload" href="https://api.observablehq.com/user" crossorigin="use-credentials" as="fetch">
<title>Anjana Vakil / Observable</title>
<link rel="stylesheet" type="text/css" href="https://static.observablehq.com/style.a55fed1b7ab9d7cd8ae0dc6fbce1727cf46027e6e2f55aa001245bf6b6a7732e.css">
<link rel="apple-touch-icon" href="https://static.observablehq.com/favicon-512.0667824687f99c942a02e06e2db1a060911da0bf3606671676a255b1cf97b4fe.png">
<link rel="icon" type="image/png" href="https://static.observablehq.com/favicon-512.0667824687f99c942a02e06e2db1a060911da0bf3606671676a255b1cf97b4fe.png" sizes="512x512">
<link rel="search" type="application/opensearchdescription+xml" href="https://static.observablehq.com/opensearch.bf5e25ab3eef28bb53ee52e7f57ea5210eb03b2edb9f7c51328d4b7ed874497a.xml" title="Observable">
<link rel="alternate" type="application/rss+xml" href="https://api.observablehq.com/documents/@anjana.rss" data-react-helmet="true"><meta name="description" content="Recently published notebooks by Anjana Vakil" data-react-helmet="true">
```
It looks like it would be good, but when I try to tweet the Collection I see: 

<img width="604" alt="Screen Shot 2021-10-07 at 12 27 43 PM" src="https://user-images.githubusercontent.com/8691/136449891-7be38edc-5735-4ee6-a91a-55ef9ba7b268.png">

For  instance - the  title is not descriptive at all --> Just says the user's name.
There's no preview, no description, It doesn't show  the  collection's  image -->
<img width="313" alt="Screen Shot 2021-10-07 at 12 30 31 PM" src="https://user-images.githubusercontent.com/8691/136450272-a993e86d-7898-4c7f-a2a1-fcaf9f8e615f.png">

**Describe the solution you'd like**
Fix the metadata so it share's with preview image, etc.
Fix the collections TITLE to  be descriptive of the collection  --  not just "Observable/ username"

**Describe alternatives you've considered**

**Additional context**
Here's a link to a shared collection -- https://twitter.com/triptych/status/1446197441921884160  which doesn't show anything usef other than the url and the un useful title

**Comment by CobusT** [comment]
Also update this thread when this Is fixed: https://talk.observablehq.com/t/social-media-metadata-buggy-on-collection-pages/5854
