### ISSUE TITLE
Page header info is duplicated

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#247]
**Describe the bug**
In a notebook,  some of the header tags are duplicated:
<img width="706" alt="Screen Shot 2021-10-07 at 12 42 23 PM" src="https://user-images.githubusercontent.com/8691/136451732-c4adbc29-f831-45f9-b158-f167a80e19b5.png">

* canonical link
* icon link
* apple touch  icon
* meta charset

**To Reproduce**
1 load any notebook
2 inspect page
3 note header tag contents

**Expected behavior**
redundant tags should not be there

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] --  MacOS
 - Browser [e.g. chrome, safari] -- Chrome
 - Version [e.g. 22] -- Any

**Additional context**

**Comment by wiltsecarpenter** [comment]
I don't see this happening anymore. Is there a recent test case?

**Comment by triptych** [comment]
Seems to be fixed now!
