### ISSUE TITLE
feature: personal templates

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#248]
**Is your feature request related to a problem? Please describe.**
The global Observable Templates are very handy, and have a lot of great features. 
I would like to be able to flag one or more of my own notebooks as 'personal templates' - so that when I hit the "new" button, they show up  as an option on the  left:
<img width="883" alt="Screen Shot 2021-10-08 at 1 16 51 PM" src="https://user-images.githubusercontent.com/8691/136620277-fa913609-48f6-4f11-a181-6674542fa4bb.png">

Use cases:
blog post template - with my own style, images, links
app templates - I want to  use my own Three.js template perhaps
classroom templates -- a teacher want our assignments done with a certain template.

Extra credit: flag "any" template as a personal template --> say some user foo has a really cool D3 template that I want to use over and over, I add it to my "personal" templates.  (A workaround of course is to fork their notebook and now it's "mine" to use ) 

**Describe the solution you'd like**
Step  1 : flag a notebook as a personal template
Step 2: see that notebook show up on the list when I press "new notebook"  - in it's own group. (Above the generic templates)

**Describe alternatives you've considered**
I've thought about making a Templates collection but it's pretty cumbersome.

**Additional context**
Yes, all notebooks are clonable, but would like to have a collection of notebooks I could create for myself to make writing notebbooks easier.

**Comment by tophtucker** [comment]
Teams can now do this, as of February https://observablehq.com/@observablehq/team-templates; I wonder if it could be extended to Pro users…

**Comment by CobusT** [comment]
This is now available to all Pro users and Pro teams.
