### ISSUE TITLE
Feature request: Allow to hide cell output

### ISSUE THREAD

**Issue by stefaneidelloth** [observablehq/feedback#257]
It is already possible to hide cell inputs and only show the cell output, using the pin feature. 

I would like to be able to only show cell inputs and collapse/hide the cell output. 

For example I would find the following notebook cleaner if the output of the first
two code cells would be hidden:

![image](https://user-images.githubusercontent.com/12675339/137122343-7f4d20f0-c096-43e2-967b-f44a52d8da78.png)

For those cells the interesting information is already included in the input and kind of duplicated/obfuscated by the output. 

**Describe the solution you'd like**
Replace the "pin" option with the two options
"Hide/show cell output"
"Hide/show cell input" 

(Anyways, in my opinion the name "pin" is not that clear/intuitive. "pin" could also mean that the cell should not move while scrolling the rest of the notebook.)

If its already possible to hide the cell output and I just did not find how to do so, please let me know.

**Comment by tophtucker** [comment]
We added this maybe six months ago, forgot to close! 😅 It was a good feature request and I’ve been loving using it.

https://user-images.githubusercontent.com/841829/235259706-e386f92d-f738-4022-9e1d-aef0ff1df22e.mov
