### ISSUE TITLE
bug: Introduction  to require page has errors

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#261]
**Describe the bug**
Visit https://observablehq.com/@observablehq/require

Observe the inline errors:  
<img width="1413" alt="Screen Shot 2021-10-14 at 2 57 00 PM" src="https://user-images.githubusercontent.com/8691/137401184-a470fea0-6261-45f8-a7e5-15ebe38acb70.png">

I don't believe they are intended to error out.

**Comment by CobusT** [comment]
Thanks for raising this. Should be fixed now.
