### ISSUE TITLE
Share modal takes a long time to render

### ISSUE THREAD

**Issue by tarekrached** [observablehq/feedback#262]
When I click the share button, it takes on the order of 3 seconds for the share modal to appear.  This is an action I do on almost every single notebook that I create, so it's pretty frustrating.  (Especially because I usually forget to do this initially, send someone the link, and then am trying to share very quickly bc they've told me they can't access it 🤦‍♂️)

**Comment by CobusT** [comment]
Tarek, please try it again now. It definitely seems faster on my end after the fix.

**Comment by tarekrached** [comment]
confirmed, it's snappy again - thanks muchly!
