### ISSUE TITLE
Reorder cells by drag & dropping in the minimap

### ISSUE THREAD

**Issue by tarekrached** [observablehq/feedback#263]
**Is your feature request related to a problem? Please describe.**
It can be difficult to reorder cells by dragging  when there's a lot cells that have a lot of output, because you have to grab the cell handle, drag to near the top or bottom of the window, and then wait for the window to scroll.  If the cells are collapsed, it can also be hard to figure out where you are in the notebook as the cells scroll by, because you don't see their names.  I find that I often fly right by where I'd like to put the cell, which is frustrating.

**Describe the solution you'd like**
It would be awesome to be able to reorder cells by dragging and dropping them within the minimap, which is beautifully information-dense, as it just shows the cell names and little else.  Plus, the dependency edges are useful context when rearranging.

**Describe alternatives you've considered**
I considered a cell reordering mode that would collapse all the cells and just show their names, but then I realized that's just the minimap.

**Comment by CobusT** [comment]
Also https://github.com/observablehq/feedback/issues/40

**Comment by tophtucker** [comment]
Just launched! You can also now cmd-click on cells in the minimap to select them.

https://user-images.githubusercontent.com/841829/196605133-f605e9f9-9af0-4f67-9320-db2779d63d85.mov
