### ISSUE TITLE
Code editing areas are blank

### ISSUE THREAD

**Issue by kalmdown** [observablehq/feedback#266]
**Describe the bug**
Code cells display blank regions in current scroll region

**To Reproduce**
Hard to say...the notebook has become complex and I don't know what the trigger is that causes the problem. 

**Expected behavior**
Code is always visible in code cells.

**Screenshots**
![image](https://user-images.githubusercontent.com/2244894/137418894-03612e34-0756-4752-937a-6529da6367bd.png)

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Browser Chrome
 - Version 94.0.4606.81

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kalmdown** [comment]
![image](https://user-images.githubusercontent.com/2244894/137424594-b0deb1ba-9c02-4e37-8531-a20c9d7b6ef2.png)

**Comment by duaneatat** [comment]
Thank you for this report -- we are working on it and will update you!

**Comment by mootari** [comment]
See also #84

**Comment by CobusT** [comment]
@kalmdown I am closing this issue since it is well covered in the previously mentioned issue. Thanks for raising it, though.
