### ISSUE TITLE
Allow "Set Preview Image" from within notebook

### ISSUE THREAD

**Issue by mattdzugan** [observablehq/feedback#27]
**Problem Description.**
I'm always frustrated when I am ready to set the preview image for a notebook I'm about to publish, and I need to leave the notebook in order to set its preview image.  Unless I'm a total n00b, the only way I know how to currently set the preview image is to click the "3 dots" nav from within a COLLECTION page or a PROFILE page, but not within the notebook itself.

**The solution I'd like**
I think it'd be very logical to put a "set preview image" option in the little "3 dots" nav item at the upper right of a notebook.

**Alternative Solution**
I suppose you could put a little modal prior to publishing saying "Hey here's the default preview, do you wanna set your own?"

**Comment by CobusT** [comment]
+1
We are actually redoing that '...' menu and this is definitely on the list!

**Comment by mootari** [comment]
Related Discourse topic: [Set preview image from within notebook](https://talk.observablehq.com/t/set-preview-image-from-within-notebook/3733)

**Comment by CobusT** [comment]
This is now possible from the Publish modal in the Notebook menu in Next. We may change this to a different wording in the menu structure, but you can now set a thumbnail image from the notebook itself :-)

**Comment by mootari** [comment]
> This is now possible from the Publish modal in the Notebook menu in Next.

@CobusT Only if the notebook has changes. I don't think this issue can be closed just yet.

**Comment by CobusT** [comment]
Ah. Interesting. Looks like if we enable the 'publish settings' menu items on published notebooks that should do the trick? Investigating whether we could do that.

**Comment by CobusT** [comment]
OK, this menu item is now be enabled! Please let me know if you feel this should stay open.

**Comment by mootari** [comment]
Looks good to me, thanks for the fix!

**Comment by mootari** [comment]
Unfortunately I have to nitpick the current solution: Setting the preview image within the modal is only possible if I intend to publish the notebook. I cannot change the thumbnail and at the same time keep the notebook private.

**Comment by cboyda** [comment]
> This is now possible from the Publish modal in the Notebook menu in Next. We may change this to a different wording in the menu structure, but you can now set a thumbnail image from the notebook itself :-)

Screenshot? Where?
