### ISSUE TITLE
Port "Compare Edits" to Next

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#272]
**Is your feature request related to a problem? Please describe.**

When viewing an editable notebook with unpublished changes in the classic UI, the notebook menu offers the option "Compare Edits" to quickly compare the latest version with the latest published version.

However, in Next this option is not directly available. Instead, one has to open the history, find and select the latest version that is marked as "published", then select "compare to latest" from the notebook menu.

**Describe the solution you'd like**

When a notebook has unpublished changes, make "Compare edits" directly available in the menu (as top level or sub level item).

**Comment by CobusT** [comment]
In next, I see an option for that... are you not seeing the same?
<img width="514" alt="Screen Shot 2021-10-19 at 4 04 32 PM" src="https://user-images.githubusercontent.com/10869236/138002427-242a9616-5f35-479b-9f6e-9d7324f10b02.png">

**Comment by CobusT** [comment]
Ha! I think that is it! Marking this as a bug.
