### ISSUE TITLE
Mismatched order after reloading a user's notebooks listing

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#279]
**Describe the bug**

Reloading a user's list of notebooks produces a mismatch between shown and applied sort order when any non-default order was selected.

*Update: This bug only affects unauthenticated users.*

**To Reproduce**
1. Go to https://observablehq.com/@observablehq?tab=notebooks
2. Sort by title
3. Reload the page

Both the URL and selected sort order show "title", but the actual sort order is the default ("published").

**Expected behavior**

The applied order matches the selected order.

**Comment by CobusT** [comment]
I cannot reproduce this... I tried on multiple browsers... very strange.

**Comment by mootari** [comment]
This only seems to happen if you're not logged in. I've updated the issue description.

**Comment by CobusT** [comment]
Ahhhh! Thanks.

**Comment by CobusT** [comment]
Fixed.
