### ISSUE TITLE
Batch copy cells or fork to existing notebook)

### ISSUE THREAD

**Issue by CobusT** [observablehq/feedback#282]
From: [bradydowling ](https://talk.observablehq.com/t/feature-request-batch-copy-cells-or-fork-to-existing-notebook/4621)

It’d be nice to be able to batch copy several cells from one notebook to another existing notebook. If you’ve already created a notebook but you want most of the contents from another notebook you can no longer fork it.

Some kind of batch copy or partial fork into an existing notebook would save a ton of time.

**Comment by triptych** [comment]
Yeah  like "partial fork" button which brings up a list of cells. Hit checkboxes next to  the cells and the new page is "forked" with only the selected cells carried over

**Comment by CobusT** [comment]
Now that we have launched the new Cell mode (press Esc while in a cell in your notebook) you can select multiple cells, copy them and paste them into a new notebook. I see you already saw the update in the forum. Closing this issue. Feel free to reopen if you think it is not addressed.
