### ISSUE TITLE
Allow range requests

### ISSUE THREAD

**Issue by domoritz** [observablehq/feedback#283]
Please add support for `Access-Control-Allow-Headers: range` so that we can make range requests from Observable. This change would make it possible to request only parts of a file for example. See https://github.com/duckdb/duckdb-wasm/discussions/356 for an example application.

**Comment by visnup** [comment]
Range request headers should at least work right now for private (not link shared, not published) or team private as they don't cross a CORS boundary. Looking into allowing this on published files. I've only skimmed the [CloudFront / S3 documentation on range support](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RangeGETs.html), so I know they're supported and cached, but unsure how well yet.

**Comment by visnup** [comment]
Ok, so I have a version working but realized there's one last hurdle to discuss: for compressible files, we store a gzip version at rest on S3 and these confuse range requests.

Range headers are relative to the gzip encoded version. A fetch for a CSV file with a range header, starting from byte 0 works pretty much out of the box, with the browser gzip-decoding for you. Any subsequent request for ranges starting >0 are garbled and error with "Failed to load resource: cannot decode raw data." Now, parquet files aren't a compressible mime type (I think we recognize them generically as application/octet-stream) so range requests should work fine for those, but CSV will be tricky or impossible to leverage range requests.

And to be clear, this isn't in production yet, but just in a local working version where I'm able to experiment some with these headers.

**Comment by visnup** [comment]
Update: I deployed the above to production since any range requests before would already be erroring on CORS. Let me know what you think. A demo: https://observablehq.com/d/6767d5c6e06b94a3

**Comment by visnup** [comment]
Going to call this done, but @domoritz let us know if this works out for the parquet use case and we can re-open if something isn't right.

**Comment by domoritz** [comment]
The range requests on file attachments work well. We are not using them in the DuckDB Observable client.

**Comment by mootari** [comment]
@visnup Can these headers also be added to the endpoint for notebook modules?

**Comment by visnup** [comment]
> @visnup Can these headers also be added to the endpoint for notebook modules?

That would be a radically different endeavor. This specific request was accomplished via adjusting AWS configuration whereas supporting those headers for our own endpoints would take more coding.

Unless I'm misunderstanding the request…
