### ISSUE TITLE
Can't dismiss keyboard in Chrome on iOS 14

### ISSUE THREAD

**Issue by israelgonzalezb** [observablehq/feedback#286]
Pressing the Done button on the keyboard, or clicking outside of a cell, no longer dismisses the keyboard.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.6
 - Browser: Chrome
 - Version: 95

**Additional context**
The only way to dismiss the keyboard is to click into the address bar and then go back to the notebook.

**Comment by israelgonzalezb** [comment]
I found a workaround. The keyboard can be dismissed by pressing on the empty right margin space of the notebook.

**Comment by mbostock** [comment]
We pushed a fix for Safari’s blur behavior and I’m no longer able to reproduce this on iOS 15. Can you reload and let us know if this is still broken for you? (And if you’re willing, whether it goes away when you upgrade to iOS 15?)
