### ISSUE TITLE
RSS discovery missing?

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#287]
**Describe the bug**
I don't see any [link rel=alternate] links to my RSS feed in the HEAD in any of my notebooks. Is RSS auto discovery not a feature on Next?
https://www.rssboard.org/rss-autodiscovery

**Comment by mbostock** [comment]
We’ve never had this feature on notebook pages. It’s only present on collections, profiles, and explore. We could definitely add it in Next, though.

**Comment by CobusT** [comment]
This is implemented now.
