### ISSUE TITLE
Inputs.button reduce option doesn't work when it depends on a cell using yield.

### ISSUE THREAD

**Issue by andypea** [observablehq/feedback#289]
**Describe the bug**
The _reduce_ option in _Inputs.button_ does not update the button's value if it depends on a cell which contains a _yield_ statement.

**To Reproduce**
See: https://observablehq.com/@andypea/bug-in-inputs-button

```{js}
bValue = {
  while (true) {
    yield 13;
  }
}
```

```{js}
viewof bButton = Inputs.button("B", { value: 0, reduce: () => bValue })
```

```{js}
bButton
```

**Expected behavior**
The button's value should be updated when it is clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/764764/141877717-caf34749-dc89-4ad7-9b39-4b35328582ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 94.0.1 (64bit)

**Comment by mbostock** [comment]
bValue is continuously yielding a new value (60 times a second), causing bButton to continuously be recreated (60 times a second).
