### ISSUE TITLE
Cell toolbar covers cursor

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#291]
**Describe the bug**

Moving the cursor inside an editor scrolls the viewport to keep the cursor in view. However, when the cursor is moved towards the bottom, and the editor touches or extends beyond the bottom edge of the viewport, then the sticky toolbar covers the cursor for the approx. two bottom lines within the viewport.

**Screenshots**

![Kapture 2021-11-19 at 00 54 37](https://user-images.githubusercontent.com/322014/142515481-da7dfd4a-addb-467f-9303-c2362c1bea77.gif)

*(Apologies for the awful dither.)*

**Desktop (please complete the following information):**

Chrome 95 on macOS 11.6.1

**Comment by mootari** [comment]
The toolbar also covers the bottom of the history, which makes it difficult to see if the end has been reached:
![image](https://user-images.githubusercontent.com/322014/144743614-3fd1689b-7cc2-42fe-a412-2907f6be89e7.png)

**Comment by mootari** [comment]
Most importantly, the toolbar also covers search results. When a search result is clicked, the user still has to scroll down to see the highlighted match.

**Comment by CobusT** [comment]
@mootari Could you please retest this? In looking at the current behavior, it seems to be fixed.
- toolbar doesn't cover history or search results panes anymore
- when clicking on a search result, the match is visible without having to scroll.

**Comment by mootari** [comment]
@CobusT 
1. Fixed: history is no longer covered by cell toolbar
2. Fixed: cursor is no longer covered by cell toolbar or sticky header
3. Still open: cell toolbar covers cursor. See demo:
4. <video src="https://user-images.githubusercontent.com/322014/163977912-5e7caa4e-180c-48b6-ba76-98a66c6192e7.mp4">

**Comment by mootari** [comment]
It's the [demo notebook](https://observablehq.com/@observablehq/demo) ;)

I suspect that the second line is partially within the threshold that determines wether a line is "visible". Here I've added the CSS rule `.cm-content > div { outline: 1px dotted #0005 }` to the parent window: 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/322014/164034566-88c1cdd3-cf4c-4dbe-9ba3-566dc836d026.png">

Note that I cannot reopen this issue.

**Comment by mootari** [comment]
By the way, you can find published notebooks via their content by picking any phrase and searching for it in quotes, e.g.: https://observablehq.com/search?query=%22you+can+yield%22
