### ISSUE TITLE
Clicking People Icons should jump to where they are editing the file.

### ISSUE THREAD

**Issue by kalmdown** [observablehq/feedback#296]
**Is your feature request related to a problem? Please describe.**
WOuld like ot be able to quickly get to where other people are editing

**Describe the solution you'd like**
Clicking on their icon in the header should take me to where they are editing - like Miro.

**Describe alternatives you've considered**
Haven't, but people may say "How do you get to their profile?" To which I would say...DId you invite someone you don't know to your Ob? Seeing where they are editing is more relevant to the context.

**Additional context**
None

**Comment by CobusT** [comment]
I am sure you have discovered this already, but the minimap shows you where someone is editing in the notebook

See https://twitter.com/observablehq/status/1433099729852850178

**Comment by kalmdown** [comment]
Had not discovered. But since I don't keep it open all the time it would be
nice to have the access on entering the page.

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by tophtucker** [comment]
You can now click people's avatars to jump to (and follow!) their cursor. https://twitter.com/observablehq/status/1591180087785033728
