### ISSUE TITLE
Let me sort my notebook list by creation date

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#30]
**Is your feature request related to a problem? Please describe.**

Notebooks are currently sorted by the date of their last modification, causing old notebooks to move to the front of the list even if only a small fix was applied. Updates to many older notebooks (e.g. a "spring cleaning") can push back recently created notebooks by several pages, making the notebook list largely unusable as an organization tool for a period of time.

**Describe the solution you'd like**
1. Allow authors to sort their notebooks by creation date. Figma's UI may serve as an inspiration:
    <img width="407" src="https://user-images.githubusercontent.com/322014/109706285-0a6c1400-7b99-11eb-809b-35ef93581a8f.png">
2. Let authors define the default sort order in their account settings.

**Describe alternatives you've considered**

- The original order of latest notebooks can roughly be restored by editing them one after another. This process is cumbersome, error prone and introduces unneccessary edits.
- Observable's internal API does not explicitely expose a notebook's creation date. Instead the date has to be obtained by fetching the version history and retrieving the first version's timestamp. The high number of API requests required makes solutions in user space impractical, as is demonstrated in [this prototype](https://observablehq.com/d/c467c727f2a0d30b).

**Additional context**

The feature was first requested in the Discourse topic [Feature request: Persistent sort order for notebooks](https://talk.observablehq.com/t/feature-request-persistent-sort-order-for-notebooks/3735).

**Comment by a10k** [comment]
I started using a private collection to jump to recent notebooks TODO/TMP etc., having this will be super helpful!

**Comment by jrus** [comment]
I'd like to be able to sort *anyone's* notebook list by creation date, modification date, or number of likes.

Alphabetical is not too useful.

**Comment by jrus** [comment]
I'd also like it if the notebook 'list' view would be a compact table of rows and columns, like the list view in a GUI file manager, optionally with more than 30 entries at a time (maybe supporting a click to sort in the table header row). The current 'list' view is pretty much useless as an alternative to the grid of cards view.

**Comment by jrus** [comment]
@mootari maybe we can build an alternative view in a notebook that fetches a person's published notebooks from the API and then presents them using an [@observablehq/inputs](http://observablehq.com/@observablehq/inputs) table.

**Comment by mootari** [comment]
> I get both update_time and publish_time

Which is different from the creation time, i.e. the timestamp of the first version.

> @mootari maybe we can build an alternative view in a notebook that fetches a person's published notebooks from the (undocumented) API and then presents them using an @observablehq/inputs table.

Done! See https://observablehq.com/@mootari/sortable-notebook-list

> I'd also like it if the notebook 'list' view would be a compact table of rows and columns

I'd prefer if this was adressed in a separate issue. I want to keep the scope of this issue as narrow as possible, to improve its chances of getting picked up and implemented in the near future.

**Comment by mootari** [comment]
I just had to update 21 notebooks to fix a breaking library change, which completely messed up my list of recent notebooks.

I cannot use the @mootari/sortable-notebook-list as a workaround because it only includes published notebooks. This feature request is now almost nine months old, but hasn't received any feedback from the team, neither on Discourse nor here. Can we get at least *some* response?

**Comment by CobusT** [comment]
Hi @mootari 

First of all, I apologize that we have not responded to this sooner. We have actually been discussing this idea internally and love the sortable notebook list that you created (I use it myself!). We also feel your frustration of not being able to sort the notebook listing screen.  

While we think through a full solution (including potentially making the listing more tabular), would it be helpful to start with adding a dropdown to the notebook listing page with a sort option:
["alphabetical", "most recent created", "most recent edited", "..."]
and making that selection "sticky"?

**Comment by mootari** [comment]
> would it be helpful to start with adding a dropdown to the notebook listing page with a sort option:
["alphabetical", "most recent created", "most recent edited", "..."]
and making that selection "sticky"?

@CobusT Absolutely, that's all I ever wanted! 😃

**Comment by mootari** [comment]
@CobusT Any update on this?

**Comment by CobusT** [comment]
@mootari It is actually in development atm. This will not be as full-featured as you may eventually want, but we are just adding a dropdown to a user or team's notebook listing screen (not on search results, and not when viewing another user's notebooks).
You can see what we are thinking of doing below.
Q1: Happy with these sorting options?
Q2: Would you expect Published to be the original publish time, or the latest publish time? Or should we have two different sort options?

<img width="325" alt="Screen Shot 2021-06-24 at 10 04 46 PM" src="https://user-images.githubusercontent.com/10869236/123372316-350f1d80-d538-11eb-8cb3-6657716c0906.png">
<img width="286" alt="Screen Shot 2021-06-24 at 10 09 28 PM" src="https://user-images.githubusercontent.com/10869236/123372685-e0b86d80-d538-11eb-9d73-e8bcf52e5e4d.png">

**Comment by mootari** [comment]
@CobusT This is great news! Can you estimate how long it will take until the feature can be released?

> Q1: Happy with these sorting options?

Absolutely!

> Q2: Would you expect Published to be the original publish time, or the latest publish time? Or should we have two different sort options?

Publish dates are a slightly convoluted topic in Observable, and I'm tempted to suggest that you'd leave this option out for the moment.
If you still want to add it, then it should probably match the order in the public profile view. But that order may not make sense for unlisted notebooks, much less so for private ones.

**Comment by CobusT** [comment]
It is currently being reviewed but should be soon!
Perhaps we create 2 options for published:
- Published (original)
- Published (updated)

**Comment by mootari** [comment]
"Published" and "Republished" perhaps? With a fallback to created for private notebooks?

**Comment by CobusT** [comment]
I like that!
The direction will be by toggled with the little widget to the right... and you would be able to set it in the URL parameter:
`https://observable.test:5000/@cobus2?direction=asc&sort=likes&tab=notebooks`

- Edited
- Created
- Published
- Republished
- Title
- Likes

Your first point (Is published) is already a filter criteria, so don't think that makes sense for a sort choice, does it?

**Comment by mootari** [comment]
> Your first point (Is published) is already a filter criteria, so don't think that makes sense for a sort choice, does it?

I was describing multiple internal `order by` statements so that the order of private notebooks doesn't end up undefined. To demonstrate it as a table (and ignoring the actual internal format):

|Notebook|1. Is published|2. Publish date|3. Created date|
|---|---|---|---|
|A published notebook|1|2021-05-25|2021-06-18|
|An unlisted notebook|1|2021-05-23|2021-06-20|
|A private notebook|0|NULL|2021-06-21|

**Comment by CobusT** [comment]
I see. I think the Published, Republished and Likes all could use a secondary sort so the results are deterministic. So for the secondary sort on those, perhaps created date?

**Comment by mootari** [comment]
Sounds good!

**Comment by CobusT** [comment]
Quick update... After a few reviews, we are not going to have a sort order for 'republished'. As you correctly stated, this is a bit of a convoluted topic... :-)

**Comment by mootari** [comment]
> Adding update_time as the secondary sort

@CobusT Hadn't seen your edit before. My response was to your original suggestion of using the "created" time as secondary sort. I strongly advise against using a secondary sort like update time that is bound to change frequently, as users won't be able to infer the reason. Please use the created time as secondary sort.

**Comment by CobusT** [comment]
@mootari A few things to consider:
- The default sort is update_time desc, so it feels more intuitive to have this be the secondary sort?
- The secondary sort only comes into play when choosing "Published date" and "Likes" where there are multiple items with the same primary sort (for published date, the multiples are the null ones that are not published). A user can still select 'Created' as the primary sort...
- This only applies to the notebook listing screen for your own notebooks and the search results screen.

**Comment by mootari** [comment]
@CobusT It's not a hill I want to die on, but for posterity:

> The default sort is update_time desc, so it feels more intuitive to have this be the secondary sort?

I would argue that sorting by update time was never intuitive, and has been a questionable choice from the start.

> The secondary sort only comes into play when choosing "Published date" and "Likes" where there are multiple items with the same primary sort (for published date, the multiples are the null ones that are not published).

The idea for using created here is to provide a predictable behavior, by making the fallback order stable and unchanging. I would always advocate simplicity and learnability over context-dependent utility.

> This only applies to the notebook listing screen for your own notebooks and the search results screen.

Especially the latter makes it important to offer a stable fallback. Imagine how frustrating it would be to page through results, only to have notebooks change their positions even though the aspect of a notebook by which you sort hasn't changed.

Anyway, since you closed the issue: When is the release due?

**Comment by CobusT** [comment]
It is live!

**Comment by mootari** [comment]
Thanks so much!
