### ISSUE TITLE
Add notebook to collection

### ISSUE THREAD

**Issue by MayaGans** [observablehq/feedback#300]
Hi! Lazy feature question (maybe this exists already, in which case I guess the feedback is that it wasn't immediately obvious to me 🙈) - it'd be cool to have a new notebook option _inside_ a collection? Maybe a little plus icon/button to add a new notebook to the collection? I though the "add to collection" option in the edit dropdown would do this but it looks like that does a collection merge...

**Comment by CobusT** [comment]
That is a great idea. Somewhat related to #26.

**Comment by CobusT** [comment]
Also, the 'New' notebook button now allows you to select a collection.
