### ISSUE TITLE
Binder error for SQL Cell with numerical parameter

### ISSUE THREAD

**Issue by kimmolinna** [observablehq/feedback#306]
If I define numerical parameter in other cell like `parameter_year = 2018` the following code is not working in SQL Cell
```
SELECT
*
FROM prices
WHERE year(time)=${parameter_year}
LIMIT 100
```
I will get the following error message:
`Error: Binder Error: Parameter/argument count mismatch for prepared statement. Expected 1, got 0
`

The following code is working nicely:
```
SELECT
*
FROM prices
WHERE year(time)=2018
LIMIT 100
```

**Comment by CobusT** [comment]
Can you please confirm what type of database this is? Is this a MySQL database?

**Comment by kimmolinna** [comment]
DuckDB. I'm sorry I didn't mentioned that earlier.
```
import {DuckDBClient} from "@cmudig/duckdb"
db = new DuckDBClient
Select 42
number_42=42
Select ${number_42}
```
The last last leads to the biden error.

**Comment by kimmolinna** [comment]
Actually this seems to be DuckDB client problem. Maybe @domoritz could  help me...

**Comment by kimmolinna** [comment]
@CobusT SQL Cell seems to use parameters for prepared statements. Would it be possible to use same logic as previously  so that cell is just one statement? Because previously `con.query("SELECT ${number_42}")` was equal to  `con.query("SELECT 42")`  instead of `con.query("SELECT ?",[42])`

**Comment by domoritz** [comment]
I can add support for prepared statements to the duckdb observable client.

**Comment by kimmolinna** [comment]
@domoritz As a general rule it's good, but I don't know is it wise for selects with parameters? You can quite easily handle those just by adding parameters to a query and then it's just one query. I dit it like this.

```
function par2query(query, params){   
  var out = query
  if (typeof params !== 'undefined'){
    for (let i = 0; i <params.length; i++) {
      out = out.replace('?',params[i]);
    }
  }
  return out
}

```

**Comment by domoritz** [comment]
Are you worried about performance? @ankohn mentioned the difference should be minimal.

**Comment by kimmolinna** [comment]
I'm always worried about performance. That sounds good.

**Comment by domoritz** [comment]
I just added support for parameterized queries to the Observable client at https://observablehq.com/@cmudig/duckdb. Take it for a spin and let me know how it performs.

**Comment by kimmolinna** [comment]
Thank you very much. Works nicely.

**Comment by CobusT** [comment]
Great. Thanks @domoritz and @kimmolinna.
Parameterized queries sounds like a great enhancement.
