### ISSUE TITLE
SQL Cells don't work with imported clients

### ISSUE THREAD

**Issue by domoritz** [observablehq/feedback#309]
If I import a client, I cannot reference it in a SQL cell.

<img width="617" alt="Screen Shot 2021-12-05 at 14 38 52" src="https://user-images.githubusercontent.com/589034/144761074-45d1349a-f3d8-4275-9d3d-d550bcdf4398.png">

**Comment by mbostock** [comment]
Thanks for the report. I’ve put a PR up for this and expect it will go out sometime tomorrow.

**Comment by domoritz** [comment]
I guess the fix is not live yet?

**Comment by mbostock** [comment]
Give it a few minutes…

**Comment by mbostock** [comment]
(Update: There’s an [active Heroku incident](https://status.heroku.com/incidents/2390) which is delaying deploys.)

**Comment by domoritz** [comment]
Works now. Thanks for implementing support!
