### ISSUE TITLE
Make visual representation of an import copy & paste-able

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#31]
**Describe the bug**

The hyperlinked visual representation of an "import" is almost, but not quite, copy and paste-able into a new notebook (confusingly so). 

Visual representation is missing quotes. As a work around, many people now provide a copy and paste-able snippet in their introductory prose.

![image](https://user-images.githubusercontent.com/1848162/109775488-dd078080-7c01-11eb-8c3b-36680b28fcd1.png)

**Comment by mootari** [comment]
What about imports that use `with`? Is there a benefit to duplicating the editor content verbatim, when the cell could be pinned instead?

**Comment by tomlarkworthy** [comment]
yeah the 'with' should be there too I think. The main benefit is people not asking stuff like: https://talk.observablehq.com/t/unexpected-character/4916/3

To me its an unnecessary trip hazard. Why is is so close to being copy and paste-able yet not. Why not just go all the way? Why we saving 2 characters and generating forum confusion over 2 characters. The variables imported are wrapped with { } , so it looks like computer code at the beginning... but it isn't.... it is ambiguous.

**Comment by j-f1** [comment]
Maybe it should behave similarly to commented-out cells (i.e. show only the code and not have a space for the output)?

**Comment by jrus** [comment]
j-f1: Having clickable links is super helpful.

tom: I don't really want to see the 'with' part; cell output would start to get excessively verbose.

**Comment by mootari** [comment]
> The variables imported are wrapped with { } , so it looks like computer code at the beginning... but it isn't.... it is ambiguous.

Here's a thought: perhaps the actual problem is that it looks like code?

**Comment by mootari** [comment]
@CobusT Can you describe which changes were made that resolved this issue?

**Comment by CobusT** [comment]
We now show quotes with the visual representation of the import. We did not incorporate the 'with' clause.

**Comment by mootari** [comment]
Thank you!
