### ISSUE TITLE
Markdown doesn't work within <details> <summary> html tags

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#310]
I have a markdown cell and when I try to use the html _detail_ tag, like below.
```html
<details>
<summary>
# An H1 html title
</summary>
> things about this title
- one
- two
</details>
```
The markdown is ignored and treated like plain text.

**Comment by mbostock** [comment]
Within HTML you are only allowed to use inline Markdown elements such as italics (`*`), bold (`**`), and links. You aren’t allowed to use block elements such as headings (`#`), blockquotes (`>`), and lists (`-`). If you want these elements within HTML, you should write them as HTML. Alternatively you can interpolate Markdown into Markdown, but that’s probably more awkward than just writing HTML.

```js
<details>
<summary>
${md`# An H1 html title`}
</summary>
${md`> things about this title
- one
- two`}
</details>
```

**Comment by hellonearthis** [comment]
That's cool,  I was just dreaming of an easier way that the simple way you mentioned or just using HTML.
