### ISSUE TITLE
SQL Cell - CREATE table

### ISSUE THREAD

**Issue by kimmolinna** [observablehq/feedback#311]
When I 
1. open a connection to a database 
2. create a table in a next cell `CREATE table ...`
3. insert data to the new table

Normally insert tried  before the creation of table is ready and this generates error message. How should I control this? Where should I put `await`? ;)

**Comment by CobusT** [comment]
For these types of support questions, it is best to email the support team at support@observablehq.com.

However I think I know what you are asking. It sounds like you want to make sure that cell 3 waits for cell 2 to complete and resolve whatever promises are still pending before executing (cell 3). If that is the case, you can create a dependency between the cells by writing cell 3 like this:

```
{
  cell 2;
  insert data..
}
```

That will make cell 3 wait for cell 2 to resolve before proceeding.

**Comment by CobusT** [comment]
Did that suggestion work?

**Comment by kimmolinna** [comment]
It seems I can't do a dependency between SQL Cells.
`Error: Parser Error: parser error : syntax error at or near "{" LINE 1: {cell 1; ^ `

**Comment by CobusT** [comment]
Please send a notebook for us to look at to support@observablehq.com

**Comment by kimmolinna** [comment]
[DuckDB and SQL Cell test](https://observablehq.com/@kimmolinna/duckdb-and-sql-cell-test`)

**Comment by CobusT** [comment]
Thanks for sending that notebook along. That clarified the request for us. The support team will get back to you.
