### ISSUE TITLE
A "timeline" notebook with updates from people one follows

### ISSUE THREAD

**Issue by veli-gasparovic** [observablehq/feedback#314]
**Is your feature request related to a problem? Please describe.**
There's too much good stuff and good authors on the platform. We need a "follow" concept.

**Describe the solution you'd like**
I'd like the option to follow authors, updates can be added to an autogenerated notebook on my observable profile.

**Describe alternatives you've considered**
Click around to see what's new. Doesn't work.

**Additional context**
/

**Comment by CobusT** [comment]
Thanks for the feedback! This is definitely high on our list. We are working on some features that would allow you to follow other creators. It may not be in the form of a notebook, though.

**Comment by CobusT** [comment]
Also see #59

**Comment by CobusT** [comment]
This has been added in Jan 2023. See [here](https://observablehq.com/@observablehq/following)
