### ISSUE TITLE
URL settings: Deleting suffix up to forward slash crashes app

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#318]
**To Reproduce**

1. Open a notebook's URL settings
2. enter "foo/2"
3. Delete "2" via backspace
3. Watch the Observable UI crash.

**Additional context**

The following errors are logged (however, no network requests were made):
![image](https://user-images.githubusercontent.com/322014/147383404-1d0ee5aa-3b92-4012-bf4f-2cfbf139d2af.png)

**Comment by grant** [comment]
I made a change that should fix this. The update will be deployed soon.
