### ISSUE TITLE
Republish Bar

### ISSUE THREAD

**Issue by LaoTzunami** [observablehq/feedback#320]
**Is your feature request related to a problem? Please describe.**
I work on a fairly small screen, and header bars make me feel claustrophobic because of the screen real-estate it takes up. I avoid sending links to notebooks I am working on to my friends, because then I'll have to deal with that bar, and when I modify a notebook I've already published, I republish after every tiny little change just to get rid of it.

**Describe the solution you'd like**
It would be nice to have an option in user settings that keeps the republish bar at the very top, so you have to scroll up to see it, but it doesn't hover over the entire notebook.

**Describe alternatives you've considered**
Alternatively, put the republish message to the left or right side of the screen, like how you have the notebook table of contents, so it is still always visible reminding you to republish, but doesn't cover up the workspace. Or, just put an [X] button so I can get rid of it by closing it, not republishing.

**Comment by CobusT** [comment]
We do not have a 'republish' feature anymore, and we made some improvements to banners on mobile devices. Please let us know if you still have issues with the banners on mobile.
