### ISSUE TITLE
two character searches do not trigger search

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#322]
**Describe the bug**
I want to search for "d3" info. I cannot because "d3" is not enough characters to trigger the site to search

**To Reproduce**
1. Go to 'https://observablehq.com/
2. Click on search at the top
3. Type "d3"
4. press enter 

**Expected behavior**
expect the search to trigger so I can learn about D3 info.

** Actual Behavior**
nothing unless I add more characters 

**Desktop (please complete the following information):**
windows 10 , chrome

**Additional context**

**Comment by CobusT** [comment]
d3 is probably a bit of an outlier here, since kicking off search after two characters in general is not very fruitful. And it is doubtful how fruitful it is for d3, since there are more than 10,000 results.

**Comment by CobusT** [comment]
We are now allowing 2-character searches again, and searching for `d3` now lists some curated results before the long list of other d3 content.
See May 24, 2022 announcement here: https://observablehq.com/@observablehq/release-notes#CuratedSearchResults
