### ISSUE TITLE
Move unpublished changes into a suggestion

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#324]
**Is your feature request related to a problem? Please describe.**

When a notebook contains unpublished changes that are a work in progress and must not be published yet, these changes cannot easily be extracted into a suggestion. Observable will not allow a suggestion to be created because the changes already exist in the parent notebook, even if the parent notebook had been reverted to its published state after the fork was created.

In order to move unpublished changes into a suggestion, one has to follow these steps:
1. open the history
2. select the last published version
3. click "Fork" to create fork of the published version
4. select "Compare fork" from the menu
5. click "Compare reverse"
6. click "Merge ... changes"
7. select "Suggest" from the notebook menu
8. enter a description and confirm
9. switch to the parent notebook
10. select "revert to published" from the menu

After all these steps the user finally ends up with a suggestion that contains the previously unpublished changes.

**Describe the solution you'd like**

In addition to "revert to published", I'd like an option to split these unpublished changes out into a fork and automatically create a suggestion. By including the suggestion step I can annotate the intention of the fork, without having to add notes or comments to the notebook itself.

**Describe alternatives you've considered**

I can still create a fork from the unpublished state and revert the parent notebook. However, I cannot create a suggestion for this fork and have to find some other means to track the changes.

**Comment by mootari** [comment]
Allow me to emphasize the point about tracking:

![image](https://user-images.githubusercontent.com/322014/147685525-a2867f5f-b6d5-4dec-b44a-e74fd72c90ce.png)

**Comment by mootari** [comment]
As an alternative, Observable could allow suggestions to be created even if a fork does not contain any newer versions.

This has the added benefit that I can create a suggestion upfront, in preparation for the planned changes. Currently I have to modify a clean fork arbitrarily just to force a new version, before I can create a suggestion.

**Comment by mbostock** [comment]
I’ve removed the restriction that you have to have edited the fork before you can suggest. It should go live shortly.

**Comment by mootari** [comment]
Thank you!
