### ISSUE TITLE
A way to ask search engines not to index a particular notebook

### ISSUE THREAD

**Issue by yurivish** [observablehq/feedback#326]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to publish a notebook on Observable and also elsewhere, but search engines downrate duplicate content. 

For example I might write a posts for my personal site, and want to link to the Observable version as editable source code. Google picks up on the link, and indexes both versions.

**Describe the solution you'd like**

A checkbox in the publication settings to disallow indexing via a [noindex](https://developers.google.com/search/docs/advanced/crawling/block-indexing) meta tag in the header:

```
<meta name="robots" content="noindex">
```

**Describe alternatives you've considered**

Unpublishing the notebook on Observable.

**Additional context**

Discussed on the Observable Slack on December 29.

**Comment by mootari** [comment]
What's missing here is that unlisted notebooks can end up in search engine results when they are linked to from other pages. I think it's reasonable to always serve unlisted notebooks with `noindex`.

**Comment by mbostock** [comment]
A fix will be live shortly.

**Comment by yurivish** [comment]
That's quick! Is the fix to serve unlisted notebooks with `noindex`, or does it cover the broader case of being able to control when a published notebook is indexed, e.g. if I wanted to fully publish a notebook on Observable (it would be listed in my profile), but host the "canonical" version on my own site?

**Comment by mbostock** [comment]
Unlisted notebooks will have noindex.

**Comment by yurivish** [comment]
Thank you!

FWIW I would also find it useful to be able to set `noindex` on fully published notebooks, but feel free to keep this closed if that's not in the cards.

**Comment by yurivish** [comment]
I see the noindex header on my unlisted notebooks now — thanks again and happy 🎄!
