### ISSUE TITLE
Notebooks are not obviously _Code_ Notebooks (to a first-time-reader)

### ISSUE THREAD

**Issue by mattdzugan** [observablehq/feedback#33]
## Background
I've found that there a few types of notebooks

1. Technical "tutorial" on how to do code something [example](https://observablehq.com/@pbeshai/tidy-js-intro-demo)
2. 1 Main viz with lots of supporting code [example](https://observablehq.com/@rreusser/gpgpu-boids)
3. Blog-post-style prose with visuals/calculations that support the prose [example](https://observablehq.com/@rreusser/finding-roots-in-the-complex-plane?collection=@rreusser/writeups)
 
Notebooks that fall under the first 2 categories, I think present Observable Notebooks fairly obviously as a places where "the source code is right here". Most of the times Authors will pin the code open, or refer to it in their text.

However.... 

## Hypothesis
...Anecdotally, A few times that I've shared notebooks with friends or on twitter, that are closer to that 3rd category, and sometimes folks are unaware that they can actually click within the left-margin of a cell to view its source.
So my hypothesis is essentially - **to some readers, it's not obvious that a notebook is live code, as opposed to a blog**.  For all some random person on the internet knows "Observable" is just a platform like "Medium" allowing folks to publish prose.  

## Describe the solution you'd like
I think there's a few options here:

#### Option 1 -- [Clippy](https://cdn.geekwire.com/wp-content/uploads/2019/05/Clippy.jpg.jpg) for observable
Give authors an option to enable some `helpers` for the margin. Upon publishing, It'd be cool if I could check a box that says "Would you like to inform users that this notebook contains live code?" Here's a disgusting 10-second mockup of what this could look like
![image](https://user-images.githubusercontent.com/6321009/109842409-aafd1b00-7c0f-11eb-9db9-b3a7baa4e768.png)

#### Option 2 -- subtle but clear way to indicate "there's code here"
So by default, unless I have a cell active, there is not indication that there's "more info" avaialable. And even on active cells, the only indication is the little "3 dots" menu.  I don't think the average reader would connect the dots (pun intended) that a "3 dots" menu is going to allow them to view source code on an article that they may not even be realizing has live code running.
![image](https://user-images.githubusercontent.com/6321009/109843999-4e9afb00-7c11-11eb-8e0a-3ba05dbf1334.png)

#### Option N+
I'm sure there's plenty of other ways to solve this problem. But the 2 above are just a few that come to mind for me.

**Describe alternatives you've considered**
I totally realize that Observable may have the opinion: "Just pin your cells to have the code open". 
That's fair. 
But I think it can get in the way of the flow of an "article-style" notebook.  I guess ultimately what I'm looking for is something that can still read like an article or essay, but also makes it clear to readers that "the code is right here if you click".

**Comment by bryangingechen** [comment]
There's already a banner at the top that informs (non-logged-in) visitors that everything is live code:
<img width="1229" alt="Screen Shot 2021-03-03 at 12 21 49 PM" src="https://user-images.githubusercontent.com/5209952/109845403-18627900-7c1b-11eb-8249-5872dfa4ae64.png">

**Comment by mattdzugan** [comment]
🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯

I guess it's been too long since I've been not logged in!! 😬 This is a perfect solution! 🎉
I will close this feature-request

**Comment by mootari** [comment]
It seems that this banner is no longer present, neither in Next nor in Classic?
