### ISSUE TITLE
Activity timeline reports wrong created time

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#331]
**Describe the bug**

The timeline reports a notebook as having been created X minutes ago, where X matches the last publish time. The notebook was created (and first published) over an hour earlier.

![image](https://user-images.githubusercontent.com/322014/147830425-d718fb8b-67af-4c73-9b63-13fb3be38ac8.png)

Notebook URL: https://observablehq.com/@mootari/observablehq-stdlib-issues-274-import

**Comment by mootari** [comment]
Still a problem, note the topmost entry:
![image](https://user-images.githubusercontent.com/322014/165737988-b18d94ce-a7a0-44cb-86c3-2828e7fc7feb.png)

**Comment by mootari** [comment]
It's really amazing how wrong this date it. For a notebook created at 12:04 CEST, viewing the timeline at 14:20 CEST reports the notebook as having been created "7 minutes ago". 

What makes this issue so difficult to fix?

**Comment by CobusT** [comment]
The create and edit events were bundled together, which meant that when there was a create and edit event in the same day, we would say that it was created on the last date that the notebook was edited. We fixed this by splitting out the create event from the other edit events so it now gets its own entry in the activities. Let us know if this looks right on your end.

**Comment by mootari** [comment]
Looks good, thanks!
