### ISSUE TITLE
Sidebar menu styles are broken on profile pages at various breakpoints

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#339]
**Describe the bug**

**Personal profile page, <= 480px:**

![image](https://user-images.githubusercontent.com/322014/148067525-9586f608-f76e-448c-8757-101582d4678b.png)

**Personal profile page, at 640px:**

![image](https://user-images.githubusercontent.com/322014/148067430-c91eef24-09f6-4e5e-bb54-6821eb3e0a6b.png)

**Team profile page, at 640px:**

![image](https://user-images.githubusercontent.com/322014/148067171-4b2f3e69-6204-49a9-9eaf-beb98186ffe0.png)

Personal profile page,  >640px && <960px:

![image](https://user-images.githubusercontent.com/322014/148068094-f26e71cd-8b9a-42f7-b58e-9157ff698e50.png)

**Comment by CobusT** [comment]
O no! Thanks for flagging.

**Comment by mbostock** [comment]
Hi, my name is ike Bostock and I work at bservable. 🤦
