### ISSUE TITLE
Search/replace: Replacing a result moves selection back to first item

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#341]
**Describe the bug**

When a search result is replaced and thus removed from the result list, the selection does not advance to the next item, but instead jumps back to the first item.

**Expected behavior**

After replacing an item the next item becomes selected, so that multiple results can be replaced in succession.

**Screenshots**

![Kapture 2022-01-09 at 12 24 24](https://user-images.githubusercontent.com/322014/148680275-d374b225-fcc3-4b32-acbe-63a297f6dbb8.gif)

**Comment by CobusT** [comment]
This should now work correctly. Please re-open if you disagree.
