### ISSUE TITLE
Allow web API access from an Observable page

### ISSUE THREAD

**Issue by pkriens** [observablehq/feedback#342]
I am deeply impressed with Observable and can only heap praise. Wow.

## Problem

The problem I am facing is that I need to massage external data to filter out unwanted rows and often transposing data. The problem is that this data is often shared between different notebooks. I currently do not see an easy way to access the data from another notebook. (I might have missed it though.)

Additionally:

* it also would help to modularize larger projects.
* It would allow shared settings between a family of Observable pages

## Solution

For example, in one notebook I create a variable `uk_demographics` which requires massaging data from a government spreadsheet. It would be nice if I could then access this data set via JSON like `https://observablehq.com/d/535dbaece509424b?var=uk_demographics&type=json`. 

## Alternatives

Of course it is possible to massage the data offline first and store it on Github.  However, I find that Observable really is a very impressive tool to massage the data because it is so easy to make intermediates and verify the stages.

## Additional

If this is considered it might be useful to mark variables as `export` to clearly mark the intention to maintain the presence and format of thee variable over time.

**Comment by CobusT** [comment]
Thanks for your kind words!

If I understand your request correctly, I think you can do that by naming your cell ('myCleanData') with your cleaned up data in a notebook ('notebook1') and then in any other notebook where you need it, you simply import that cell, like so:

`import {myCleanData} from "@username/notebook1"`

If you have not created a slug for your notebook yet (typical for private notebooks), you can still import from it...

`import {myCleanData} from "d/notebookId"`

where 'notebookId' is the hex identified you see in your notebook's url, eg. `ef768a6fed38bd7a`

Note, we added a handy little tool in a named cell's ... menu that would copy your cell's import link so you can simply paste it into the notebook where you want to use it.  

<img width="308" alt="image" src="https://user-images.githubusercontent.com/10869236/148692916-2df570ff-5276-4c0a-8964-2e21e55738cf.png">

**Comment by pkriens** [comment]
Wow, I am deeply impressed ...

Would still be useful to have this for use cases that are not notebooks but that is not my direct interest. Thanks!

**Comment by mootari** [comment]
> import {myCleanData} from "d/notebookId"

@CobusT It's "notebookId" though, not "d/notebookId". 😉 

There's an open feature request to support the "d/" prefix as well: https://github.com/observablehq/feedback/issues/134

**Comment by CobusT** [comment]
> > import {myCleanData} from "d/notebookId"
> 
> 
> 
> @CobusT It's "notebookId" though, not "d/notebookId". 😉 
> 
> 
> 
> There's an open feature request to support the "d/" prefix as well: https://github.com/observablehq/feedback/issues/134
> 
> 
> 
> 

Oops! Fixed it in my response. Thanks.
