### ISSUE TITLE
Allow MP4 upload on Discourse

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#343]
**Is your feature request related to a problem? Please describe.**

The allowed file types for post attachments on https://talk.observablehq.com/ are currently limited to  jpg, jpeg, png, gif, heic, heif and webp. If users want to share a video (e.g. a screen cap), their only options are:
- convert the video to a GIF before attaching it
- upload the video to a supported 3rd party image hosting site and embed the link (which converts to an oembed)

**Describe the solution you'd like**

MP4-encoded video files are *much* smaller than GIFs, while having a far superior quality. It would be great if we didn't have to rely on workarounds in order to share videos in forum posts, but could instead attach them directly.

**Comment by mootari** [comment]
I'd like to add that I don't want the current upload limit of 4MB changed. This request is only supposed to introduce a better alternative for short clips, for which GIF is currently the only option (without using 3rd party sites). Anything above that limit will have to use an external provider.

**Comment by CobusT** [comment]
I added .mp4, .m4a, .m4p, .m4b, .m4r and .m4v
Please let me know if that works!
