### ISSUE TITLE
FileAttachment("image.png").image({width:'50%'})

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#353]
The `FileAttachment("image.png").image({width:400})` doesn't take percentage values or other unit values, only pixel values.

For me a percentage value would useful as I don't always recall the image size to half.

`FileAttachment("image.png").image({width:'50%'})`

**Comment by mbostock** [comment]
This is equivalent to saying `image.width = "50%"`, assigning [image.width](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/width). Try this instead:

```js
FileAttachment("image.png").image({style: "width: 50%;"})
```

**Comment by hellonearthis** [comment]
Thanks,  that worked nicely in the markdown cell.  `${await FileAttachment("image.png").image({style: "width: 25%;"})}`
