### ISSUE TITLE
Text Overlaps in Diff Toast-Notification on iOS Chrome

### ISSUE THREAD

**Issue by israelgonzalezb** [observablehq/feedback#355]
**Describe the bug**
A floating blue toast notification that has diff options is unreadable because the text overlaps.

**To Reproduce**
1. While using the Next UI, make changes to a published notebook. The amount of characters in the version number doesn't make a difference so a new notebook will work.
2. Press the notebook's ellipsis settings menu (...).
3. Press "Compare published"
4. The blue notification at the top will have unreadable text.

**Expected behavior**
The notification bar's elements should be readable, otherwise the diff comparison flow is broken.

**Screenshots**
Notebook at version 679
![1A15ECB1-8AAC-43B5-8A24-DCDA42E04C53](https://user-images.githubusercontent.com/48233351/152310372-91e23628-3d52-4900-95fa-a25491ebc0c8.png)
Max zoom out as a workaround. Classic UI has a different diff comparison flow so that is another workaround.
![5DFE51C3-8851-4D3D-84CE-A7E0F513594B](https://user-images.githubusercontent.com/48233351/152310365-ca659d69-c850-42cb-8d60-2f26b0724316.png)
A new notebook on version 7 to see if length of version number had an impact. 
![53C68755-B1B1-47A9-BD86-46AEEA84D38F](https://user-images.githubusercontent.com/48233351/152310379-d4c68244-f084-4c17-a685-aac7416feb8a.png)

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 14.6
 - Browser Chrome
 - Version 96.0.4664.116

**Additional context**
- User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.116 Mobile/15E148 Safari/604.1

**Comment by CobusT** [comment]
Also #204

**Comment by CobusT** [comment]
This should now be fixed! Thanks for raising it.
