### ISSUE TITLE
Forum does not load on Firefox

### ISSUE THREAD

**Issue by severo** [observablehq/feedback#36]
**Describe the bug**

The page https://talk.observablehq.com does not open (nothing is loaded, I get the `NS_ERROR_DOM_ABORT_ERR` error). It seems to be exactly this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1678795.

**To Reproduce**

1. Go to https://talk.observablehq.com using Firefox Version 87.0b5
2. Pin the tab
3. Close the browser
4. Open the browser again
5. The tab does not load any more, and the Network devtools tab shows `NS_ERROR_DOM_ABORT_ERR` after a long time

**Expected behavior**

The page should load

**Screenshots**

![Capture d’écran de 2021-03-04 11-02-43](https://user-images.githubusercontent.com/1676121/109947040-2ecf0a00-7cd9-11eb-8615-48f11d8597eb.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.10
 - Browser Firefox
 - Version 87.0b5

**Additional context**

The bug might be solved following the comment https://bugzilla.mozilla.org/show_bug.cgi?id=1678795#c54.

**Comment by Fil** [comment]
works for me (Firefox 86.0.1 (64 bits) macos)

**Comment by severo** [comment]
Yes, it works, you're right. The behavior has been the same during one or two days after writing the issue, and I forgot to close it then.
