### ISSUE TITLE
Add a collection filter to the search

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#360]
**Is your feature request related to a problem? Please describe.**

*Ported from https://observablehq.com/@observablehq/searching-on-observable#comment-1dc4c802bd9a5f7a. See thread for additional context.*

The search is missing a filter for collections. At a minimum the filter should take a collection name. If possible there should also be a filter to find or exclude notebooks that have not been assigned to any collection.

Use cases:
- Search through notebooks in a collection, sorting the results by the various criteria available in the search (but absent from collections)
- Review notebooks that have not yet been assigned to a particular collection.
- Treat collections as a tagging system for notebooks, search and filter by various "tags" (inclusive and exclusive).

**Comment by CobusT** [comment]
I am just relooking at this and realized that @triptych's request in #369 was a bit different from this request. @mootari I think you are asking to be able to search for notebooks in a particular collection (or in no collection). Whereas the other request was to show collections in the search results. I think we should re-open #369 and keep them separate?

**Comment by mootari** [comment]
@CobusT I agree. It might also help to summarize this distinction in the other issue.

**Comment by CobusT** [comment]
tag search will be available soon!
