### ISSUE TITLE
Left margin on "views per day" truncates axis labels if a views on a day exceed 9,999 views

### ISSUE THREAD

**Issue by yurivish** [observablehq/feedback#362]
**Describe the bug**
<img width="313" alt="image" src="https://user-images.githubusercontent.com/114388/153323081-68d4ca41-3330-4d5f-8e56-e9177697d54c.png">

**To Reproduce**
1. Go to a notebook with more than 9,999 views on one day within the last 30 days
2. Click on 'Open insights pane (👁)'
3. See error

**Expected behavior**
A wider left margin would give more room for digits. Alternatively, `overflow: visible;` might work? Or maybe switching to a "K" formatting.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 98.0

**Additional context**
There's an open issue for adaptive margins based on tick length in the Plot repo: https://github.com/observablehq/plot/issues/383

**Comment by mbostock** [comment]
💪💪
