### ISSUE TITLE
Feature Request:  Collections Description field --> make it a markdown enabled field

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#368]
**Is your feature request related to a problem? Please describe.**
Collections are a powerful feature which allow one to collect a related set of notebooks together.
Right now, the description field is a plaintext field that shows up when a user views the collection such as  https://observablehq.com/collection/@triptych/tips-and-utilities
It would be great if this field was "markdown enabled" like github readme.md files are on a repo.

**Describe the solution you'd like**

Make the Collections description field be a markdown enabled field - so links, images, etc would display when the user visits a collection's 'main page'. Also, use the included image as the thumbnail for that collection when posting it on  social networks.

**Describe alternatives you've considered**
Making the notebooks ordered  and creating an intro notebook for the collection as the "first"  one.

**Additional context**

**Comment by CobusT** [comment]
Dup of #244 ?

**Comment by triptych** [comment]
Yes, this is essentially  the same request. Will close as a dupe.
