### ISSUE TITLE
Gallery won't display

### ISSUE THREAD

**Issue by jeremyherve** [observablehq/feedback#371]
https://observablehq.com/@d3/gallery won't display on firefox 74.0 64-bits Windows 10
Works on the same Windows 10 with Edge.

Firefox Output console :

Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).
Feature Policy: Skipping unsupported feature name “accelerometer”. gallery
Feature Policy: Skipping unsupported feature name “autoplay”. gallery
Feature Policy: Skipping unsupported feature name “clipboard-write”. gallery
Feature Policy: Skipping unsupported feature name “encrypted-media”. gallery
Feature Policy: Skipping unsupported feature name “gyroscope”. gallery
Feature Policy: Skipping unsupported feature name “magnetometer”. gallery
Feature Policy: Skipping unsupported feature name “midi”. gallery
Feature Policy: Skipping unsupported feature name “vr”. gallery
Feature Policy: Skipping unsupported feature name “accelerometer”. gallery
Feature Policy: Skipping unsupported feature name “autoplay”. gallery
Feature Policy: Skipping unsupported feature name “clipboard-write”. gallery
Feature Policy: Skipping unsupported feature name “encrypted-media”. gallery
Feature Policy: Skipping unsupported feature name “gyroscope”. gallery
Feature Policy: Skipping unsupported feature name “magnetometer”. gallery
Feature Policy: Skipping unsupported feature name “midi”. gallery
Feature Policy: Skipping unsupported feature name “vr”. gallery
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o299802.ingest.sentry.io/api/5593183/envelope/?sentry_key=ca9eac14b9164458a334243bb3c08c45&sentry_version=7. (Reason: CORS request did not succeed).
SyntaxError: invalid identity escape in regular expression 6889-be4e945550042a72.js:1:2
SyntaxError: invalid regular expression flag s 5291-3bae7e23ea3817fb.js:1:4803
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o299802.ingest.sentry.io/api/5593183/envelope/?sentry_key=ca9eac14b9164458a334243bb3c08c45&sentry_version=7. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o299802.ingest.sentry.io/api/5593183/store/?sentry_key=ca9eac14b9164458a334243bb3c08c45&sentry_version=7. (Reason: CORS request did not succeed). 2

**Comment by CobusT** [comment]
Looks like Firefox is blocking Cross Origin requests. Can you check if you have any extensions installed like Privacy Badger? See some other discussions about this here:
https://stackoverflow.com/questions/24371734/firefox-cross-origin-request-blocked-despite-headers

**Comment by mootari** [comment]
@jeremyherve That Firefox version is almost two years old. I recommend that you update to the current version 97.

@CobusT sentry.io being blocked should be unrelated to the problem. Firefox 74 chokes on various regular expressions:
- `SyntaxError: invalid identity escape in regular expression` [`6889-be4e945550042a72.js:1:2`](https://observablehq.com/_next/static/chunks/6889-be4e945550042a72.js)
- `SyntaxError: invalid regular expression flag s` [`5291-3bae7e23ea3817fb.js:1:4803`](https://observablehq.com/_next/static/chunks/5291-3bae7e23ea3817fb.js)
</pre>

**Comment by CobusT** [comment]
@jeremyherve Are you able to upgrade and retest?

**Comment by CobusT** [comment]
Closing this for now. Please feel free to re-open if this is still an issue after you upgraded.
