### ISSUE TITLE
Search for notebook imports

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#384]
**Is your feature request related to a problem? Please describe.**

As an author of notebooks that expose APIs I often need to know if/how these APIs are used in other notebooks in order to plan enhancements or breaking changes.

Right now I cannot explicitely search for imports, as a search for `"@user/slug"` will also produce results that only contain the text (e.g. as part of a URL).

**Describe the solution you'd like**

Add a search prefix `import:` to match the phrase to notebook imports. Searching for `import:@user/slug` will only match notebooks that import from the notebook `@user/slug`.

**Comment by CobusT** [comment]
We now have a feature in the header of a notebook (for notebook editors) for this!

<img width="216" alt="image" src="https://user-images.githubusercontent.com/10869236/234429173-6e5ee6b9-4bed-4434-a3ea-76ef6f3baf4f.png">

When you click on it, you get a list of the notebooks that import from the current notebook.
