### ISSUE TITLE
Observable Search response sent to notebooks as json

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#39]
I would like Observable search to be able to be called from a notebook and have the results returned as json object.

Using search box like [searching-on-observable](https://observablehq.com/@observablehq/searching-on-observable) would return the results so the user could then do their own processing and filtering on the results.

**Comment by jrus** [comment]
This can be done via the (undocumented) Observable API (through a CORS proxy), but I'm not sure if it violates the TOS or not.

e.g. you can fetch https://api.observablehq.com/documents/search?page=1&query=food

**Comment by CobusT** [comment]
@jrus This does not violate the ToS, but as you said, the API is not documented and not supported, meaning we may change it without the need to be backwards compatible, so use at your own risk.

**Comment by mootari** [comment]
Another example for customized results consumption and processing: https://observablehq.com/@mootari/search-results-paging

**Comment by CobusT** [comment]
We are not planning on adding a public Search API at this point.
