### ISSUE TITLE
Hello , Can you please add a feature of Embedding an iframe without the Logo and the name of Observable ?

### ISSUE THREAD

**Issue by mariamatef** [observablehq/feedback#390]

**Comment by tomlarkworthy** [comment]
Workaround https://observablehq.com/@endpointservices/example-custom-embed

**Comment by ananya-roy** [comment]
There is now an option, for Enterprise teams, to remove the Observable attribution banner in iframe embeds: https://observablehq.com/@observablehq/embeds?collection=@observablehq/embedding-notebooks#cell-1081
