### ISSUE TITLE
Vega-lite charts un-render after switching tabs on Chrome

### ISSUE THREAD

**Issue by itmeson** [observablehq/feedback#393]
**Describe the bug**
In all notebooks that I have accessed in Chrome, that use vega-lite, charts display correctly when the page loads or is refreshed, but when I switch to a different tab and then return, I find the charts are no longer rendered.  Inspectors, markdown, and other code cells seem to work as usual, and tooltips still pop up when I mouse over the spots where they would have appeared in the original chart, but the chart itself is invisible.

I asked for help from Observable Support and they were not able to replicate, but I was asked to submit the Issue here in case it can be picked up later.  As suggested by Support, I can workaround the issue by using other browsers, or by using svg renders (add `.render({renderer: `'svg'})  ) to the vega-lite code

**To Reproduce**
1. Open a notebook that uses vega-lite charts in Chrome
2. Switch browser tabs
3. Return to tab with observable notebook
4. See that all the vega-lite charts are now un-rendered

**Expected behavior**
I expect rendered charts to remain rendered after switching tabs.

**Screenshots**
![Notebook display with working charts](https://user-images.githubusercontent.com/210367/160013842-e7901ca5-aa69-41e2-b6ab-ebe0e34c2d37.png)
**notebook display with working charts**

![Notebook display after switching tabs with un-rendered charts](https://user-images.githubusercontent.com/210367/160013894-340ec23a-66e9-4866-89a8-523c47c275a0.png)
**notebook display after switching tabs with charts un-rendered**
**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Chrome
 - Version 98.0.4758.80 (Official Build) (64-bit)

**Additional context**

**Comment by mootari** [comment]
I suspect this is an issue with your graphics driver. Try disabling hardware acceleration in Chrome and check if the problem still remains.

**Comment by mootari** [comment]
@itmeson No idea, sorry.

**Comment by CobusT** [comment]
This doesn't sound like something Observable can fix/change, right? Closing, but if you feel this still needs to be addressed then please let us know.
