### ISSUE TITLE
Collaborator Icons should send you to where people are working in a notebook

### ISSUE THREAD

**Issue by zachbogart** [observablehq/feedback#397]
**Is your feature request related to a problem? Please describe.**
Working with others in a notebook is super cool, but it would be helpful if the icon list at the top of current collaborators link to _where_ in the notebook they are working, rather than their profile pages. Here's a shot of where the icons show up:

<img width="255" alt="Screen Shot 2022-04-03 at 9 57 40 PM" src="https://user-images.githubusercontent.com/31786233/161476911-b03d1ad7-a547-4c0d-9b5e-f3a61d01582d.png">

I think it would make more sense for those icons to link to where your collaborators are working rather than take you to an external page.

**Describe the solution you'd like**
Collab icons link to cell that collaborator is working out of (if they are in a cell) instead of their profile page.

**Describe alternatives you've considered**
Profile page links are still valuable, so it could be "in addition to" rather than "instead of"

**Comment by tophtucker** [comment]
You can now click people's avatars to jump to (and follow!) their cursor. https://twitter.com/observablehq/status/1591180087785033728

**Comment by zachbogart** [comment]
That's so good, nicely done!
