### ISSUE TITLE
Returning more than 99 rows fails on Postgres

### ISSUE THREAD

**Issue by danny-waite** [observablehq/feedback#399]
I'm a newbie so I'm possibly doing something wrong but I can't find any inspiration in the docs.

The following fails
```
db = DatabaseClient("test")
data = db.query("SELECT name FROM test_table limit 100")
```

with `TypeError: Failed to fetch` after waiting for a minute or so.

`data = db.query("SELECT name FROM test_table limit 99")` works

**Comment by CobusT** [comment]
Is this still happening? I have not been able to reproduce using our Postgres databases...

**Comment by CobusT** [comment]
Closing this. Please let us know if this is still an issue.
