### ISSUE TITLE
Notebook option "Move to trash" not initially available

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#4]
**Describe the bug**
When working within a newly created notebook, the menu option "Move to trash" is not available until the page has been reloaded.

**To Reproduce**
1. Create a new notebook.
2. Edit and save cells until the URL switches from `/new` to the notebook ID.
3. Attempt to delete the notebook via the menu in the top right corner.

**Expected behavior**
After the notebook has received its internal URL, the option "Move to trash" becomes available in the context menu.

**Additional context**
The use case for immediate deletion comes up fairly often with quick sketches or tests.

**Comment by cassandraoid** [comment]
hey @mootari are you in Classic or Next in reference to this issue?

**Comment by mootari** [comment]
@cassandraoid Classic, FP is currently on hold.

**Comment by jrus** [comment]
**Workaround:** Refresh the page (in Mac Safari, ⌘R) then select the ... / Move to Trash menu option.

**Comment by mootari** [comment]
@jrus It's mentioned in the first sentence.

**Comment by jrus** [comment]
Fair enough. As a trivial point of bug report style, I think it's helpful to clearly spell out workarounds or alternatives in a dedicated section.

**Comment by dunstan** [comment]
Just adding some screenshots since this came up again.

![image](https://user-images.githubusercontent.com/1316196/117865738-1e905980-b24b-11eb-8701-325469a1d9d8.png)
<img width="1234" alt="Screen Shot 2021-05-11 at 11 19 35 AM" src="https://user-images.githubusercontent.com/1316196/117865755-23eda400-b24b-11eb-8275-33488b60ca6c.png">

**Comment by CobusT** [comment]
This is fixed in next. If you find it not working, please re-open this.
_(We are not planning on fixing this in classic)_
