### ISSUE TITLE
Adjust cell order via dataflow minimap drag and drop

### ISSUE THREAD

**Issue by noblemillie** [observablehq/feedback#40]
**Is your feature request related to a problem? Please describe.**
I love the dataflow minimap the team implemented a little while back. If it could double as a UX shortcut for drag and drop cell re-ordering, I think it could serve as a useful little usability improvement as I've found that the order of cells in a cleaned up final version of notebook I would want to publish for public consumption is typically different than the cell order I use when composing the notebook (i.e. I like to place interrelated cells next to one another when writing code for screen real estate purposes, however I feel its better to order cells by logical grouping (i.e. imports, utility functions, inspirations/attributions, etc) prior to publishing as I feel this cell ordering makes for a more intuitive organizing convention for readers to follow. 

**Describe the solution you'd like**
Allow the user to drag-and-drop the cell order via the topological dataflow minimap displayed in the upper right corner of each notebook.

**Describe alternatives you've considered**
I typically just used the keyboard shortcuts to reorder the cells as the notebook begins to come together. It's a perfectly serviceable solution and this drag-and-drop suggestion would simply be a small reduction of friction to an already outstanding workflow.   

**Additional context**
I have a 2019 15-inch macbook pro, which comes with Apple's touch bar instead of the traditional keyboard function keys, which includes the escape key. Putting the escape key in the touchbar has turned out to be an unfortunate design decision by Apple in my opinion, as the escape key does not always register reliably and has an incongruent feel with the rest of the keyboard. 

As a result, this tends to impair my navigation speed whenever I try to navigate a notebook using Observable's keyboard shortcuts exclusively given the unreliability of the ESC keypress. The recurring interruption to my type flow is obviously minor, however given how central the escape key is to Observable's keyboard shortcuts it does become a bit tedious after a while.  So while it clearly an issue with Apple, I thought the drag and drop minimap might alleviate the issue somewhat, plus would benefit all desktop users irrespective of their particular hardware. 

All in all, it's ultimately a minor irritation and I love the Observable product regardless. Just wanted to share in case other users are experiencing the same issue and hope the team finds this helpful.

**Comment by jrus** [comment]
This was previously discussed among other ideas at [talk/2976](https://talk.observablehq.com/t/visual-dataflow/2976).

**Comment by tophtucker** [comment]
Just launched! You can also now cmd-click on cells in the minimap to select them.

https://user-images.githubusercontent.com/841829/196605133-f605e9f9-9af0-4f67-9320-db2779d63d85.mov
