### ISSUE TITLE
If named cell contains dash, cell embeds are blank

### ISSUE THREAD

**Issue by amyzhaoyu** [observablehq/feedback#403]
**Describe the bug**

If I name a cell with a label containing a dash (eg. `copy-top`) - I can save it in the notebook, however, when I go to embed the notebook cells, the resulting embed (iframe, etc) is blank. 

**To Reproduce**
1. In a notebook, name a cell with a label containing a dash `-` (I didn't try other punctuation but assuming that is probably problematic as well). 
<img width="236" alt="image" src="https://user-images.githubusercontent.com/573071/163269521-ce692d3a-f71d-48c0-92ed-83610298abe1.png">

2. Click the checkmark.
3. Go to `...` --> export --> embed cells. 

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/573071/163269735-158b2cb0-0a10-41a1-9f90-814c44e839f7.png">

**Expected behavior**
Embed should work as expected (ie. the code/visualizations should render). 

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome

**Comment by CobusT** [comment]
JavaScript does not allow dashes in variable names. In fact, when you create a JavaScript cell in a notebook such as:
`copy-top = 10`
you would get a syntax error. 

We should validate the cell name field to avoid this from happening.
