### ISSUE TITLE
What does `undefined` mean in the sql table?

### ISSUE THREAD

**Issue by domoritz** [observablehq/feedback#405]
SQL tables have an `undefined` text below the column title. What is this for?

<img width="1222" alt="Screen Shot 2022-04-16 at 1 42 29 PM" src="https://user-images.githubusercontent.com/589034/163685755-66ee5ec8-a388-4d17-8af2-36c2aae9d54a.png">

**Comment by CobusT** [comment]
This looks like a bug... it should show 'int32' instead of 'undefined'. Let me follow up on this.

**Comment by annie** [comment]
i was able to reproduce this locally, it's definitely a bug! i'm working on a fix now 👍

**Comment by annie** [comment]
just merged a fix. @domoritz is the issue fixed for you now?

**Comment by domoritz** [comment]
Yes
