### ISSUE TITLE
Should article:published_time be included meta?

### ISSUE THREAD

**Issue by abenrob** [observablehq/feedback#407]
**Is your feature request related to a problem? Please describe.**
I used to use the `<meta property="article:published_time">` tag to create embeds of notebooks. It is no longer included, and it is a valid and interesting piece of metadata.

**Describe the solution you'd like**
It would be great to include _more_ open graph tags, especially since the content is user-created, and therefore warrants attribution when embedding.

**Describe alternatives you've considered**
Then only way to get publish date from a notebook's html is to parse a div with no id, which contains the publish date as a `Mon DD` string.

**Additional context**
[Open Graph](https://ogp.me/#no_vertical)
I would be better served personally with an api to get notebook details, but I think the open graph protocol is useful in many other ways.

**Comment by mbostock** [comment]
Thanks for the report! I’ve added a bunch of Open Graph meta tags to user profiles, notebooks, and collections. Please let me know if there’s anything else we can add.
