### ISSUE TITLE
Selection checkbox is missing for commented cells

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#422]
**Describe the bug**

If a JavaScript cell contains no active code, then the selection checkbox to its left is missing.

![image](https://user-images.githubusercontent.com/322014/168864148-d2422f25-794b-40a8-a03f-392d49039a30.png)

The cell can still be selected via keyboard shortcuts.

**Comment by grant** [comment]
Thanks for reporting. I recently fixed this bug with new changes, which should roll out later today.
