### ISSUE TITLE
Custom font for code cells and result inspectors

### ISSUE THREAD

**Issue by wizzard0** [observablehq/feedback#428]
**Is your feature request related to a problem? Please describe.**
I work with numbers having lots of significant decimal digits. There's an awesome font hack making them more readable called Numderline which underlines every other group of three digits with ligatures. I use Numderline fonts in IDE, terminal, etc.

Fonts on most websites can be styled with Stylebot or changed via browser settings, however Observable has a tricky DOM which I've been unable to style with Stylebot so far.

**Describe the solution you'd like**
Ability to set a custom font for code and execution results.

**Describe alternatives you've considered**
Stylebot; changing default monospace browser font - neither seems to work with Observable

**Additional context**
![telegram-cloud-photo-size-2-5359659675903177134-m](https://user-images.githubusercontent.com/424619/170361991-78f89c5a-9b87-439e-9663-61ed4aa93081.jpg)

**Comment by CobusT** [comment]
Not sure if this helps, but here is an example of applying a truetype font to a table in Observable

https://observablehq.com/@cobus/truetype-font

**Comment by mootari** [comment]
For the editors you can create a user style with the following content:
~~~css
@-moz-document domain("observablehq.com") {
  :root { --monospace: Numderline }
}
~~~
The notebook contents reside in an iframe, which (as far as I'm aware) cannot be modified by extensions. To change the monospace font there, you'll have to insert the following line into a Markdown or HTML cell:
~~~html
<style>:root { --monospace: Numderline }</style>
~~~

**Comment by hellonearthis** [comment]
There are font-variant-numeric settings that might work. 

`font-variant-numeric: tabular-nums;`

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric
