### ISSUE TITLE
Feature Request - link to help  when Embed is disabled or tooltip with explaination

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#445]
**Is your feature request related to a problem? Please describe.**
New users may learn they can embed cells in other sites. But they are frustrated when they  choose a cell and "Embed" is disabled. There's no tooltip or help link  to explain WHY the  cell can't be embedded ( yet ) 

**Describe the solution you'd like**
When you open the drop down and mouse over Embed if it's disabled have some tooltip or help explaining why.

**Describe alternatives you've considered**
Having to read docs + go into forums and ask.
**Additional context**
<img width="165" alt="Screen Shot 2022-06-15 at 9 25 19 AM" src="https://user-images.githubusercontent.com/8691/173878215-388078e4-c9b0-4c7c-b317-d6888a71395a.png">

**Comment by hellonearthis** [comment]
Most common reason is that a related cell has no name or the notebooks not published.  
Would having a link to or popup help page be a solution?

**Comment by triptych** [comment]
Also if the cell is not named. 
Just having some (?) with a tooltip would just give a hint to folks about why they cannot click the embed link.

**Comment by mbostock** [comment]
> When you open the drop down and mouse over Embed if it's disabled have some tooltip or help explaining why.

Does it not already do this?

<img width="245" alt="Screen Shot 2022-06-15 at 12 01 42 PM" src="https://user-images.githubusercontent.com/230541/173904592-56262dc5-25fa-43ed-af16-6c4f5eafe030.png">

**Comment by hellonearthis** [comment]
Oh it does that.  I noticed the issue [here.](https://observablehq.com/@thecomputergirl/doodledoo-based-on-draw-me)
Because the HTML cell had no name, the critical cells could not be embedded without the whole notebook being embedded.
![image](https://user-images.githubusercontent.com/121805/173916433-6280ab96-cf7d-4fde-b634-a1c631ab34d2.png)

Not sure if there is am easy way around this.

**Comment by triptych** [comment]
I swear when I tested this I did not see a tooltip, but it is now, in fact, there. So, that use case is handled.
