### ISSUE TITLE
SQL Cell DuckDB bigint application error

### ISSUE THREAD

**Issue by nolan-redox** [observablehq/feedback#447]
**Describe the bug**
`Application error: a client-side exception has occurred (see the browser console for more information).` seems to be related to when a bigint is returned from the SQL Cell. I tried a fresh notebook and still receive the error (began occurring for the first time maybe a week ago - no issues prior).

**To Reproduce**
1. Go to https://observablehq.com/d/7988c0805aefcdef
2. Change SQL cell from `select 1::int` to `select 1::bigint`
3. See error: `Application error: a client-side exception has occurred (see the browser console for more information).`

**Expected behavior**
The statement `select count(*) from events` returns a bigint and hits the error above. Changing to `select count(*)::int from events` gets around the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/61290212/174455887-dfe1046f-555a-4308-887d-d97a5e59bf87.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser: Chrome 
 - Version: Version 102.0.5005.115 (Official Build) (x86_64)

**Additional context**

**Comment by CobusT** [comment]
Thanks for logging this. We noticed the same yesterday and are working on a fix.
