### ISSUE TITLE
on mobile, adding cells with the add cell menu fails with error "Oops, an unexpected error occurred"

### ISSUE THREAD

**Issue by 77it** [observablehq/feedback#448]
**Describe the bug**
On mobile, using the notebook while logged in, adding cells with the add cell menu fails with error "Oops, an unexpected error occurred".
This happens with any notebook I tried to fork/create.
With the same notebooks, shared and opened without a login (e.g. in a private session) adding cells works.
With the same notebooks, used while logged in, duplicating cells works.

**To Reproduce**
See [youtube video](https://www.youtube.com/shorts/WV12CmWbVJ8)

**Expected behavior**
Adding a cell with the "plus" menu should work for any notebook, while logged in or not.

**Screenshots**
![Screenshot 2022-06-19 112341](https://user-images.githubusercontent.com/8860389/174474522-dfda7c56-4f57-4dd3-ae45-5e7ff3371161.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone6s / IPhone8]
 - OS: [14.7.1 / 15.5]
 - Browser [Safari]
 - Browser [Chrome, v102.0.5005.87]
 - Browser [Firefox, v101.1]

**Additional context**
Some days ago the bug was absent.

**Comment by CobusT** [comment]
Thanks for reporting this. It definitely looks like a bug. As a workaround, you should still be able to press and hold the '+' to bring up the cell Menu (on mobile, we just default to JavaScript cells and you have to click and hold to bring up the menu).

**Comment by CobusT** [comment]
This is now fixed.
