### ISSUE TITLE
Minimap icons get distorted in intermediate page zoom levels

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#449]
**Describe the bug**

When the page is zoomed in via the browser zoom, the appearance of the icons in the minimap icons break in various ways at zoom levels between 100% and 200%.

**Screenshots**

| 100% | 110% | 125% | 150% | 175%
| -| -| -| -| -
|<img width=200 src="https://user-images.githubusercontent.com/322014/174962071-b19e441d-9932-47cf-9e4a-2cfdeab36e76.png">|<img width=200 src="https://user-images.githubusercontent.com/322014/174962088-6d14696f-ad7b-4333-9931-0bda8aaf8fdf.png">|<img width=200 src="https://user-images.githubusercontent.com/322014/174962103-0bd76fe7-72ec-458f-9bc8-28b6cc26bbcd.png">|<img width=200 src="https://user-images.githubusercontent.com/322014/174962127-166d715b-5e62-4f63-aa2e-e7ba72c26e00.png">|<img width=200 src="https://user-images.githubusercontent.com/322014/174962134-a25ffc68-c872-4eb8-901d-7b37a8bead66.png">

(Source: Google Chrome 99 on macOS 12.4, display pixel ratio 1)

**Comment by CobusT** [comment]
I tried to reproduce but didn't see this. I suspect this has been fixed. Could you please re-open if it is still not working for you?

**Comment by mootari** [comment]
@tophtucker fixed this a couple of months ago, I think.
