### ISSUE TITLE
Data Table Cell does not highlight NULL correctly

### ISSUE THREAD

**Issue by domoritz** [observablehq/feedback#451]
In https://observablehq.com/@cmudig/duckdb-client#cell-1003, if I hover over a row with NULLs, the histograms highlight 0 and not NULL.

<img width="1004" alt="Screenshot 2022-06-22 at 2 36 02 PM" src="https://user-images.githubusercontent.com/589034/175111491-be630e9a-b209-471e-9502-d96c6c8e91b3.png">

**Comment by visnup** [comment]
Further, the NULLs I think count towards 0 in the histogram:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/10444/175139865-1958cc4d-11d1-4e6d-91e5-c32c7dab88c8.png">

**Comment by visnup** [comment]
Both issues with the hover behavior and NULL being interpreted in the histogram as 0 should be fixed now.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/10444/175364042-b450d75d-3059-4941-96a4-8793fb9569c1.png">
