### ISSUE TITLE
Tooltips are displayed underneath the cursor pointer.

### ISSUE THREAD

**Issue by mlynchdev** [observablehq/feedback#456]
To repro: Simply visit any project, hover any item in the right vertical menu and notice that it is very difficult to read.

Fix: change positioning of the tooltip so that it is above the cursor pointer.

**Comment by mootari** [comment]
Are you talking about these tooltips?

<img width="266" alt="image" src="https://user-images.githubusercontent.com/322014/176030622-98c6cd5b-8f41-4b71-a231-5ec5d8aadd58.png">

**Comment by mootari** [comment]
Those are native tooltips which can be neither positioned nor styled.

@hellonearthis I assume that you have the exact same issue with every other native tooltip on every other site?

**Comment by mythmon** [comment]
Notably, how do the tooltips of the browser's UI work? I'd expect the refresh button or back button on the toolbar to act the same.

Are you using a third party tool for that cursor? I don't have a lot of experience with Windows cursor customization.
