### ISSUE TITLE
Embedding of Data Table or SQL cells

### ISSUE THREAD

**Issue by mwhitaker** [observablehq/feedback#468]
**Is your feature request related to a problem? Please describe.**
I love Data Table cells, but I find it confusing that they are are embedded as a Javascript array. 
**Describe the solution you'd like**
I'd like to be able to interact with Data Table cells in emdedded notebooks just like on Observable.

**Additional context**
![embedding_data_table](https://user-images.githubusercontent.com/3980239/180046719-606b9851-0fe2-42fd-bfd7-248a414e38c1.png)

**Comment by GordonSmith** [comment]
I would like to second this - any reason its not part of the standard library?

**Comment by GordonSmith** [comment]
@mootari - I think this was closed in error - or has the fix not made it to the site yet?

**Comment by mbostock** [comment]
Reopening until this is generally available.

**Comment by mootari** [comment]
SQL and Data table views are now generally available in iframe embeds. For more details please see our updated [Release Notes](https://observablehq.com/@observablehq/release-notes).
