### ISSUE TITLE
Worker CSS prevents bold formatting of inline code in Markdown cells

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#473]
**Describe the bug**

Given an inline code element that is wrapped in `<strong>`:
~~~
**`this should be bold`**
~~~
the text will still display in normal weight, because Observable's worker styles contain the following declaration:
~~~css
pre, code, tt {
    font: var(--monospace-font);
}
~~~
which overrides the bold formatting of the parent `<strong>`.

**Expected behavior**

Ensure that bold formatting is restored, by adding the following rule:

~~~css
strong pre, strong code, strong tt {
  font-weight: bold;
}
~~~

**Additional context**

Ideally each property would have been defined separately:
~~~css
pre, code, tt {
    font-family: var(--monospace);
    font-size: 14px;
    line-height: 1.5;
}
~~~

However, some authors may have redefined `--monospace-font`, and this change would break their styles.

**Workaround**

Add the following line in any Markdown or HTML cell:
~~~html
<style>strong code { font-weight: bold }</style>
~~~

**Comment by mootari** [comment]
This also affects `<code>` inside headings.

**Comment by CobusT** [comment]
We opted to define the properties separately. 

```
pre, code, tt {
    font-family: var(--monospace);
    font-size: 14px;
    line-height: 1.5;
}
```
Hoping it doesn't affect people who have redefined `--monospace-font` too much.
