### ISSUE TITLE
Dismiss the "Unable to save changes" error toast after successfully reconnecting and saving changes

### ISSUE THREAD

**Issue by visnup** [observablehq/feedback#474]
**Describe the bug**
If the socket disconnects and you have pending changes, and the notebook can't save them for over 30s, you get an error toast the says "Unable to save changes." The notebook will keep trying to reconnect and save, and if it's successful, everything will be fine again. But, the error toast doesn't go away and the page still feels broken since it's still there.

**To Reproduce**
1. Make an edit to a notebook you own.
2. Get the notebook to not save somehow (in development, add an artificial delay to save events).
3. See the Unable to save changes error toast.
4. Wait for save/saveconfirm to complete successfully.
5. See toast not go away.

**Expected behavior**
After a successful save, it's confusing to leave the toast visible as it seems like something is still broken.

**Screenshots**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/10444/186784978-de2cd73a-6474-4710-8751-05b298e8a40e.png">

**Desktop (please complete the following information):**
macOS Safari 15.6.1

**Comment by mootari** [comment]
> Get the notebook to not save somehow (in development, add an artificial delay to save events).

Alternative repro steps:
- Go offline:
  - Firefox: Select "File" > "Work offline"
  - Chrome: Open the Network tab in the developer tools and select the preset "Offline"
  - Safari: Disable WiFi or use a 3rd party app like Charles Proxy.
- Make an edit
- Wait 30 seconds for the spinner to stop and the message to appear.
