### ISSUE TITLE
Cannot import notebook if any cell name contains invalid characters

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#478]
**Describe the bug**

Follow-up to #423

Notebooks that still contain invalid names cannot be imported because their compiled module code contains syntax errors. Examples:
- https://api.observablehq.com/@observablehq/sample-datasets.js?v=3
- https://api.observablehq.com/@observablehq/database-client-specification.js?v=3

**Comment by CobusT** [comment]
I think these will just have to be updated with valid names. Thanks for pointing them out.

**Comment by mootari** [comment]
For posterity: For the purpose of compilation invalid names are now treated as unnamed (which makes sense since they cannot be referenced in JS anyway). Anchor links continue to work.
