### ISSUE TITLE
revise log-in options to emphasize equality of choice :P

### ISSUE THREAD

**Issue by aaronkyle** [observablehq/feedback#481]
**Is your feature request related to a problem? Please describe.**

As I request colleagues to sign-in to Observable, I am seeing email as the selected option. I asked those why this choice, when single-click MS OIDC login in available. The common response was: it's the UI.

![sign-up-options](https://user-images.githubusercontent.com/2301690/190055388-7f5a28e2-ac75-40cc-a396-a3866c48f8cf.png)

**Describe the solution you'd like**

I would like all log-in options to be treated equally:

![sign-up-options-equal](https://user-images.githubusercontent.com/2301690/190055909-864b06cd-a930-41ed-91cf-0d85185ebbf2.png)

**Describe alternatives you've considered**

Seems that once an account is created with one option; changing to another option is not possible without account deletion.  More flexibility in authentication choice, and multiple concurrent options, would maybe help?

**Additional context**

Nope. Thank you for your consideration!

**Comment by dunstan** [comment]
Excellent feedback!

**Comment by CobusT** [comment]
This have been changed. Email is now a button on the signin and signup modals. Thanks again for the great idea.
