### ISSUE TITLE
Add an option so that Input.Table can have radio instead of checkbox.

### ISSUE THREAD

**Issue by Anaglyph-ic** [observablehq/feedback#482]
I use input.tables as elaborate selector list, and in most cases I need my users to select only 1 item in the list.

**Describe the solution you'd like**
Add a boolean option that lets you switch from checkboxes (many choices) to radio (only one choice).

**Describe alternatives you've considered**
I can implement this myself, but this sounds overkill compared to you making it standard?

**Comment by mootari** [comment]
You can provide the option `{multiple: false}` to force a single selection (see the [list of available options](https://github.com/observablehq/inputs#Table) and this [example](https://observablehq.com/@observablehq/input-table?collection=@observablehq/inputs#cell-851)).

**Comment by Anaglyph-ic** [comment]
Aaaaand that solves it, thanks for the pointer, sorry for the useless request.
