### ISSUE TITLE
Make comments on notebooks editable

### ISSUE THREAD

**Issue by amyzhaoyu** [observablehq/feedback#483]
**Is your feature request related to a problem? Please describe.**
If I comment on a cell within an Observable notebook, I am unable to go back and edit that comment once it's been submitted. I can only delete or report it, or add an additional follow on comment. 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/573071/193138444-8da74289-1bf7-4b13-8cb4-b92eec9138bd.png">

**Describe the solution you'd like**
I would like comments that I've written to be accessible for editing - i.e. if I am logged in and I open a notebook where I have left comments, I would like to be able to edit/change them as I see fit. 

**Describe alternatives you've considered**
Currently I can copy the entire (existing) comment, paste it into a new comment, edit it as needed, then repost (and then delete the old comment).

**Additional context**
#367 may be related/relevant here

**Comment by CobusT** [comment]
This is now possible! Thanks for the suggestion.
