### ISSUE TITLE
Allow to not open collections sidebar by default

### ISSUE THREAD

**Issue by oluckyman** [observablehq/feedback#486]
**Problem**

Every time I open a notebook from a collection, it shows the collection sidebar and has `?collection=...` in the URL.
The problem is, that I use the left-side white space to expand cells, so when I'm in the creator-mode, the sidebar is on my way and distracts me and I have to close this sidebar every time I open a notebook.
What makes it worse is that it does not remember my choice, and after refresh (which happens a lot during the coding) the collections sidebar opens again.

**Solution**

Keep the collections sidebar closed by default.
Or at least update the URL when I close it, so if I refresh the page, the sidebar does not pop up again.

**Comment by CobusT** [comment]
I think it is a great suggestion to update the URL when you close the collections panel.

**Comment by CobusT** [comment]
@oluckyman the URL is now updated when you close the collections sidebar.
