### ISSUE TITLE
Integer columns are importing as text

### ISSUE THREAD

**Issue by KathrynC** [observablehq/feedback#487]
I am working with a table of Blood Glucose test readings. As of yesterday, the integer column of test results is being interpreted by the parser as a string rather than an integer or a number.

Even when I export from Observables an array that works from yesterday and reimport it today, the integers are not parsed as integers.

**To Reproduce**
1. Export an array that has an integer column from Observables which has, for example, integers in the 90s and in the low 100s.
2. Reimport it.
3. View this data and sort by the integer colum.
4. See that it thinks 98 is larger than 103 (or 900 for that matter). Attached image shows that the integers are not being handled as integers.

**Expected behavior**
Integers should be sorted by numerical value.

**Screenshots**
<img width="996" alt="Screen Shot 2022-10-10 at 8 34 39 AM" src="https://user-images.githubusercontent.com/1850535/194901507-42d239ad-bec1-4398-883c-c95119c380e9.png">

**Desktop (please complete the following information):**
 - Device: MacBook Pro
 - OS: Monetrey
 - Browser Safari
 - Version 16

**Additional context**
If this is a bug, it is something that has changed in the last 24 hours.

**Comment by mbostock** [comment]
If you’re using a CSV file, you need to add {typed: true} to infer types (or use array.map to set the types of columns yourself); see [File Attachments](https://observablehq.com/@observablehq/file-attachments) for more.

**Comment by KathrynC** [comment]
Yup. That works to fix the problem. 

Thanks.
