### ISSUE TITLE
Issues connecting to Microsoft SQLServer Management Studio

### ISSUE THREAD

**Issue by jonjack-data** [observablehq/feedback#489]
Tried connecting a db in Microsoft SQLServer Management Studio. Should it work through MySQL integration or is that a completely separate connection?

**Comment by CobusT** [comment]
See #323 and add your support to that request.

**Comment by CobusT** [comment]
@jonjack-data would you be interested in being a beta tester for a SQLServer database connector?

**Comment by jonjack-data** [comment]
@CobusT Yes, that would be great

**Comment by CobusT** [comment]
Please email support@observablehq.com and provide your @username. Thanks!
