### ISSUE TITLE
provide a way to disable a cell

### ISSUE THREAD

**Issue by trebor** [observablehq/feedback#500]
**Is your feature request related to a problem? Please describe.**

often while debugging i need to remove cells from evaluation.  currently to do this i need to:

1. if it is a markdown cell, convert it to a js cell
1. open the cell
1. select the content and comment it out

and to restore:

4. if it was formally markdown cell, convert it from js back to markdown
1. open the cell
1. select the content and comment it in

throughout this process, i risk spurious edits.

**Describe the solution you'd like**

provide a way to disable/enable cells.  disabling a cell would grey it out, lock editing, and remove it from evaluation.

**Additional context**

i might note that the ⌥-D shortcut is not occupied. :)

**Comment by CobusT** [comment]
Related: #381

**Comment by trebor** [comment]
related: #495

**Comment by CobusT** [comment]
Marking as a duplicate.
