### ISSUE TITLE
allow trailing commas

### ISSUE THREAD

**Issue by trebor** [observablehq/feedback#501]
**Is your feature request related to a problem? Please describe.**

often when editing/debugging i am commenting lines in and out.  if those lines are parameters or array items, the [trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are removed by auto formatting.  i am unable to simply comment an old line back in without tracking commas.

**Describe the solution you'd like**

provide an option to [allow trailing commas](https://prettier.io/docs/en/options.html#trailing-commas) in cell auto formatting. 

**Describe alternatives you've considered**

i could turn off auto formatting when it is getting aggravating.

**Additional context**

 i understand that adding this option risks opening the floodgates to formatting option feature requests.  i would argue generally that, as no real alternative to in browser editing exists (that i know of) that ceding some control back to users with regard to editing seems fair.  so maybe giving advanced users an option to roll their own prettier configurations is not such a bad idea?

**Comment by CobusT** [comment]
Duplicate #206

**Comment by CobusT** [comment]
Would you agree, Robert? Can I mark this as a duplicate?

**Comment by trebor** [comment]
oh totally!  i should have trolled through before i wrote it up! :)

**Comment by CobusT** [comment]
Haha, that is my job :-) I love doing it actually. So great to read these suggestions.
