### ISSUE TITLE
Connect to SQL Server

### ISSUE THREAD

**Issue by jess-s** [observablehq/feedback#502]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jess-s** [comment]
Would like SQL Server database connector.

**Comment by mythmon** [comment]
@jess-s I assume you mean Microsoft SQL Server? If so, you may be interested to know that we've started internally testing that support. You can see some more details in issue #323.
