### ISSUE TITLE
Hide Table in SQL query view

### ISSUE THREAD

**Issue by domoritz** [observablehq/feedback#503]
**Is your feature request related to a problem? Please describe.**
I would like to be able to hide the table view in SQL cells. In my case, I only want the result of a query to be assigned to a variable. I still like having the syntax highlighting for SQL. 

**Describe alternatives you've considered**
I considered calling `client.query` directly but then I don't get the syntax highlighting. 

Context is that I am using the database client in https://observablehq.com/@cmudig/peeking-into-the-gaia-star-catalog?collection=@cmudig/duckdb

**Comment by mbostock** [comment]
You can click this button in the toolbar or use the Command-comma keyboard shortcut:

<img width="44" alt="Screen Shot 2022-11-11 at 3 18 19 PM" src="https://user-images.githubusercontent.com/230541/201443268-596cee1d-b46b-4441-b420-fc95dc1b49ee.png">

**Comment by domoritz** [comment]
Ohhh, I did not see that. I expected this functionality to be near the cell. Thanks!
