### ISSUE TITLE
Error when try to generate embed for DuckDB table

### ISSUE THREAD

**Issue by gustavorps** [observablehq/feedback#504]
**Describe the bug**
stars = RuntimeError: DuckDBClient is not defined

**To Reproduce**
1. Go to https://observablehq.com/@observablehq/duckdb
2. Click on ["stars" lateral bar](https://observablehq.com/@observablehq/duckdb?utm_medium=newsletter#stars)
3. Click on "Embed" 

**Expected behavior**
Embedded table

**Screenshots**
![Screenshot from 2022-11-22 15-30-58](https://user-images.githubusercontent.com/516827/203393676-936cbbb9-db9c-45df-8efe-e3b6a17f7651.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave
 - Version: [Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)](https://brave.com/latest/).

**Comment by CobusT** [comment]
We are working on a fix for this. Thanks for raising. 
FYI @mootari

**Comment by CobusT** [comment]
This should now be fixed!
