### ISSUE TITLE
Arabic string does not appear in the inspector

### ISSUE THREAD

**Issue by yurivish** [observablehq/feedback#506]
**Describe the bug**

[A clear and concise description of what the bug is.](https://observablehq.com/d/3afdbeabd799351f)

**To Reproduce**
Steps to reproduce the behavior: Go here; if you do not see the string in the inspector, then you have reproduced the bug: https://observablehq.com/d/3afdbeabd799351f

**Expected behavior**
Seeing the string "قطر"

**Screenshots**
<img width="475" alt="image" src="https://user-images.githubusercontent.com/114388/203459586-04cb3453-a09f-47a4-b621-67c42d2debc5.png">

**Desktop (please complete the following information):**

macOS 12.6.1, Chrome Version 107.0.5304.110 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
Might have to do with RTL or multi-codepoint characters.

**Comment by CobusT** [comment]
Interesting...
I actually see something on the far right of the inspector...
<img width="1013" alt="Screenshot 2022-11-23 at 11 25 29 AM" src="https://user-images.githubusercontent.com/10869236/203630797-a0c3d49b-6fc1-4482-9b2d-08e43be76320.png">

**Comment by yurivish** [comment]
Hah, so do I. Totally missed that! I wonder if that's somehow technically correct...

**Comment by CobusT** [comment]
I think it may be! Since it is a right-to-left language...

**Comment by mbostock** [comment]
See also https://twitter.com/mapmeld/status/967634520295071744
Previously https://github.com/observablehq/notebook/pull/1011

I think it would be fine to always use dir="left" for the Object inspector, but we should definitely leave on dir="auto" for non-inspector output.

**Comment by yurivish** [comment]
Was thinking about this again, and remembered about this fun blog post about a Mathematica error message: https://blog.wolfram.com/2009/09/03/a-new-slant-in-mathematica/


![](https://content.wolfram.com/uploads/sites/39/2009/09/slantimage01big.png)

**Comment by grant** [comment]
I believe this is WAI as reported.

If you're facing a real issue writing notebooks in RTL languages, please state the expected behavior and we can change the behavior to fix it, or create a new issue.
