### ISSUE TITLE
List of tables within Database files section is not alphabetical

### ISSUE THREAD

**Issue by saneef** [observablehq/feedback#512]
**Describe the bug**
In 'Database' pane, under 'Database files' section, the list of tables is not alphabetical. I have only tested with SQLite DB. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Attach an SQLite DB in a notebook.
2. Open 'Database' pane
3. Under 'Database files' section, click on the attached database name.
4. See the listing.

**Expected behaviour**
Expect to see the list of tables in alphabetical order. The listing of tables within a 'Data table' cell is alphabetical. 

**Screenshots**
<img width="1392" alt="Screenshot 2022-11-30 at 15 59 42" src="https://user-images.githubusercontent.com/81863/204772921-2d268c8d-9f70-425b-8f4d-087dd6abf945.png">

**Desktop:**
 - OS: macOS 13.0.1
 - Browser: Firefox
 - Version: 107

**Comment by CobusT** [comment]
This should now be fixed.
