### ISSUE TITLE
After using 'find' feature, typing in any cell scrolls the page away from active cell

### ISSUE THREAD

**Issue by saneef** [observablehq/feedback#513]
**Describe the bug**
Once, I use Find (Find and Replace) to jump to a cell. Every time I type in another cell, the page scrolls to a different place.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a long notebook.
2. Open 'Find and Replace' pane using 'Lens' icon
3. Search for something which towards the bottom of the page.
4. Click on one of the search result to jump to that cell.
5. Dismiss the find pane by clicking 'Lens' icon
6. Try typing in another cell, preferably one which is in the top of the notebook. The page jumps around when I type.

**Expected behaviour**
The page shouldn't scroll.

**Screenshots**
📽️ [Video](https://d.pr/v/lnE2Ql)

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
 - Browsers: Firefox (107.0.1), Safari (16.1), Chrome Dev (109.0.5414.10 )

**Additional context**
This behaviour goes away if I clear the search term from the search field, using 'cross' icon.
<img width="200" alt="Screenshot 2022-12-01 at 10 59 59" src="https://user-images.githubusercontent.com/81863/204973327-cccefc12-238b-403c-b463-39e68bdecd22.png">

**Comment by CobusT** [comment]
It looks like it keeps on trying to bring the previously searched cell into view. Is that what you see happening?

**Comment by saneef** [comment]
Looks like it.

**Comment by CobusT** [comment]
It behaves as if the search panel was still open... when I try the same with the search panel open, it does the same (which may be a bug in any case), but when I close the search panel, I don't get that.

**Comment by saneef** [comment]
Yes, it is as if the search panel is open. For me, closing the search panel through <kbd>esc</kbd> key or clicking on lens icon, get into this behaviour.

I need to clear the search term by clicking the cross icon, to make the problem go away.

<img width="417" alt="Screenshot 2022-12-01 at 10 04 01" src="https://user-images.githubusercontent.com/81863/204967053-76aa672c-5705-43b4-ae81-5459f9f34dca.png">

**Comment by saneef** [comment]
Does the search input clear when you close the search panel? It is not for me. The term will still be there. That could be the cause of this issue.

**Comment by CobusT** [comment]
The search input doesn't clear when I collapse the panel... it is persistent. But I don't get the jumping behavior unless the search panel is open...

**Comment by Martien** [comment]
It seems indeed the same as #517, so I closed that one.

**Comment by JobLeonard** [comment]
I also just encountered this. It seems to depend on `replace` being open too for me, but maybe that's a red herring.

https://user-images.githubusercontent.com/259840/210067965-fa101937-f439-4dd1-9ab1-3c25b421e924.mp4

What's strange is that I definitely *also* had moments where it happened with the search panel closed (but the fields not being empty), but as you can see that didn't trigger while recording the video

**Comment by mootari** [comment]
Confirming that I get the jumps to the last find location on every keystroke even with the pane closed if I don't clear the "Find" field.
