### ISSUE TITLE
Erratic notebook jumping

### ISSUE THREAD

**Issue by Martien** [observablehq/feedback#517]
So, I’m editing a notebook on a MacBook and my iPad sits to the right as a sidecar, showing the same notebook, its top, with the graphic. As soon as I change a cell using my MacBook, the window on the iPad jumps to some (arbitrary?) place deep in my notebook. I have to scroll completely back up to see the graphic again. Is this intentional behaviour? Or desired behaviour?

I’d like to have one computer showing other cells of the same notebook, while I edit the notebook on a second computer and see its effects on the first.

I’ve deselected any cells on the sidecar, but to no avail.

Also, I’ve noticed erratic jumping up and down in a notebook after some time. Reloading the page sometimes alleviates it. And at times I have to restart the browser. Happens both in Safari and Chrome.

**Expected behavior**
Views on other than editing computers of same notebook should continue to show same area of notebook as much as possible, when editing notebook.

If desired, I can try and make a video of erratic behavior.

**Desktop (please complete the following information):**
 - iOS 16.1.1, macOS 11.7
 - Safari 16.0

**Comment by Martien** [comment]
Thanks! Will try.

**Comment by saneef** [comment]
It looks like a variation of #513

**Comment by Martien** [comment]
Yes it does. This one can be closed then.
