### ISSUE TITLE
Navigation bar not working on https://observablehq.com/explore

### ISSUE THREAD

**Issue by Martien** [observablehq/feedback#519]
**Describe the bug**
Navigation bar not working on https://observablehq.com/explore?

Tried with Safari and Chrome, both in private mode and normal mode. Other entries do work.

**To Reproduce**
1. Open Safari or Chrome **in private mode** on https://observablehq.com/explore (normal mode works as expected).
2. Tray and click on any topic in the top navigation bar.
3. Nothing happens: there are no links.

**Expected behavior**
See any other sub page from top navigation bar.

**Desktop (please complete the following information):**
 - OS: macOS 12/6/1
 - Browser Safari 16.1, Chrome 108.0.5359.94

**Comment by mootari** [comment]
Can you please share a screen recording of the behavior? I am unable to reproduce it.

**Comment by Martien** [comment]
Will do. Additional info: only happens in full screen.

**Comment by Martien** [comment]
Can you reproduce now or do you really need the 233 MB screen recording?

Adjusted steps to reproduce
1. Open Safari or Chrome in private mode on https://observablehq.com/explore (normal mode works as expected).
1. Try and click on any topic in the top navigation bar: works as expected.
1. Make window full screen.
1. Try and click on any topic in the top navigation bar: nothing happens: there are no links.
1. Switching back and forth between normal and full screen mode switches back and forth between working and not working links.

**Comment by mootari** [comment]
> Can you reproduce now

I cannot. I would also recommend that you reboot to make sure that the error that you are seeing isn't related to your browser's GPU rendering.

>  or do you really need the 233 MB screen recording?

A small clip of you clicking on those non-functional links should suffice. Alternatively you could inspect the element and share a screenshot of that.

**Comment by mootari** [comment]
Note that you may also want to test the menu bars of other sites in fullscreen, as something related to your system might be interfering with your clicks in the top area of the window in fullscreen.

**Comment by Martien** [comment]
After reboot problem persists.

Will follow up on your other suggestions later this afternoon. Must address some other issues first.

**Comment by Martien** [comment]
- Here you go regarding screen recording.
- Did test a handful of other web sites: no problems there.
- Tested with Safari, Chrome, and Firefox: all show same problem in fullscreen.
- https://user-images.githubusercontent.com/6566925/208121623-711d12f2-1926-46e8-bd26-0ed0d3b9d6ba.mov
- May be OS-specific; I’m running macOS Monterey 12.6.1; cannot upgrade (newer OS versions unavailable for my iMac Late 2015).

**Comment by Martien** [comment]
Inspect element as per your request:

<img width="3198" alt="Screenshot 2022-12-16 at 15 41 24" src="https://user-images.githubusercontent.com/6566925/208122633-923b28ce-7297-4abe-8279-6b729c87920d.png">

**Comment by camdecoster** [comment]
Can you tab over to the menu item and still interact with it?

**Comment by mythmon** [comment]
Not highlighting links is a standard behavior for Safari. Be default it will only tab between button and inputs. You can change that in your settings https://www.a11yproject.com/posts/macos-browser-keyboard-navigation/

**Comment by CobusT** [comment]
> * Here you go regarding screen recording.
> * Did test a handful of other web sites: no problems there.
> * Tested with Safari, Chrome, and Firefox: all show same problem in fullscreen.
> * https://user-images.githubusercontent.com/6566925/208121623-711d12f2-1926-46e8-bd26-0ed0d3b9d6ba.mov
> * May be OS-specific; I’m running macOS Monterey 12.6.1; cannot upgrade (newer OS versions unavailable for my iMac Late 2015).

Interesting. In the video, it looks like you are staying on the explore page, and when you click on the Learn link, you are supposed to see a small dropdown (it doesn't navigate from there), but that doesn't show up. Clicking back to Explore doesn't look like it is doing anything because you are still on the Explore page. So the problem I see (I cannot reproduce either) is that the Learn submenu is not showing for you.

**Comment by mootari** [comment]
I suspect that fullscreen mode is irrelevant to the problem, and that the important difference is the width of the viewport (and position of the menu links).

**Comment by mootari** [comment]
@Martien Can you click the links if you move your cursor further to the top border of the page while over a link?

**Comment by mootari** [comment]
Here is my repro attempt:
1. open in private window (any page will do)
2. decrease the browser zoom of the page until the nav links are to the left of the content area
3. hover over the links

https://user-images.githubusercontent.com/322014/208151080-f91908b2-7902-4e8b-9c44-c78522746a56.mp4

**Comment by Martien** [comment]
In the video I _am_ staying on the Explore page, because the menus don’t react anymore once on that page in fullscreen.

In non-fullscreen, things work fine: drop downs appear for all but Parking and Explore and I can navigate there.

In fullscreen, and logged in, things work as expected.

In fullscreen, and anonymous/private in, things work as expected until entered into Pricing or Explore which catch me in a dead end.

As per @mootari’s request: private window, non-fullscreen, zoomed out 3x: all menu items dysfunctional.

BTW, I do not want to use too much of your time if this is a this-version-of-macOS-no-longer-supported issue. I can live with it.

**Comment by Martien** [comment]
In Chrome, symptoms show when zoomed out 6x. (Almost cannot read it anymore.)

Browser-dependent?

**Comment by CobusT** [comment]
@Martien Would you mind checking if this is still a problem for you? We made a lot of changes to the menu and I suspect this is not happening anymore (I couldn't reproduce)

**Comment by Martien** [comment]
Hi @CobusT, 

Thanks to you and the team for investing all this creative effort!

BLUF: In general, I do not understand why there is a difference between UX from logged in (hidden sub-menu; shows when clicked) and private (visible caret suggesting sub-menu; shows when hovered). Feels inconsistent for no reason.

Just tested on Safari 16.6.

When **logged in** into Observable:
- Visit https://observablehq.com/explore
- Menu shows Products Pricing etc, Just the words, no hint of drop down menus.
- Click on Product: drop down menu (suddenly) shows.
- Click on Pricing: immediately opens https://observablehq.com/pricing

I find the above somewhat confusing from a UX perspective, but can live with it.

When using **Private** browsing:
- Visit https://observablehq.com/explore
- Different menu shows: “Why Observable”, Product, Enterprise, etc. Confuses me.
- “Why Observable”, Product, and Resources show a down caret, suggesting a drop down menu.
- Hovering over the entries with a down caret bring up its menu (pop up?).

Both normal and full screen appear the same; i.e. no difference in appearance or UX.

Please tell me how I can be of further assistance.

❤️ 👁️ (Observable, that is).

**Comment by CobusT** [comment]
@Martien 

You are absolutely right! That UX is 'inconsistent for now reason'. Noted!
