### ISSUE TITLE
Allow ability to set thumbnail within notebook 

### ISSUE THREAD

**Issue by zachbogart** [observablehq/feedback#520]
Find myself wanting to set the thumbnail as I am working on a notebook, rather than jumping back out to update it. It could be helpful to include it under a notebooks's settings:

<img width="507" alt="Screen Shot 2022-12-16 at 4 28 08 PM" src="https://user-images.githubusercontent.com/31786233/208213087-7e106f74-73f1-42fe-a9b8-311256ea7876.png">

Thanks!

**Comment by mythmon** [comment]
This could be easier to find, but you can set the thumbnail in the "Share" modal, in the first level of the menu in your screenshot.
