### ISSUE TITLE
Minimap cell dragging is broken

### ISSUE THREAD

**Issue by oluckyman** [observablehq/feedback#529]
**Describe the bug**

When I drag cell in minimap, the cell ends up in the end of the notebook instead of the dropped location.
Also three is no visual feedback during the dragging. 

**To Reproduce**
1. Go to whatever notebook (e.g. https://observablehq.com/@observablehq/minimap)
2. Open minimap
3. Try to drag & drop a cell
4. See how it moves to the end of the notebook.

**Expected behavior**
Cell moves between cells where it was dropped and there is visual feedback so I can see where it will be before I drop it.

**Screenshots**

https://user-images.githubusercontent.com/642673/213514373-736301f2-706e-40ac-b7f0-0d87ea7e3487.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome (sidekick, arc), safari

**Comment by tophtucker** [comment]
😯 Looking!

**Comment by tophtucker** [comment]
@oluckyman This should be fixed now (thanks entirely to @libbey-observable who beat me to it 😅) — let us know if you see it again.
