### ISSUE TITLE
Plot onClick Handler

### ISSUE THREAD

**Issue by johnhellier** [observablehq/feedback#530]
**Describe the solution you'd like**
An event handler for Plot

**Discussion**
This [notebook](https://observablehq.com/@fil/plot-onclick-experimental-plugin) started a solution. I have not seen any other work on this.  As a core capability of all D3 elements this would be very welcome for plot. I would imagine it is on the list already but I have not seen any open requests for it.

Thanks

**Comment by mootari** [comment]
Closing since Plot now has the [Pointer transform](https://observablehq.com/plot/interactions/pointer#pointer-transform). In general Plot related issues should be filed in [observablehq/plot](https://github.com/observablehq/plot).
