### ISSUE TITLE
Is there plan about support DoltDB and public DoltHub data ?

### ISSUE THREAD

**Issue by Code2Life** [observablehq/feedback#534]
DoltDB is a new distributed database that combining features of Git & MySQL. Dolt also have a DoltHub which hosts public data:

[https://www.dolthub.com/discover](https://www.dolthub.com/discover)
[https://docs.dolthub.com/concepts/dolthub/api](https://docs.dolthub.com/concepts/dolthub/api)

Seems all public data could be queried through Dolthub GraphQL/API endpoint.

If this could be supported on Observablehq as alternative to SQLite, it would be really cool.

Some pros I came up with comparing with SQLite:
- No need to upload sqlite files, as Dolthub hosts data and provide API
- The data size, page to load could be on-demand defined by notebook
- Data would be refreshed upon each run
- Versioning is built-in feature of DoltDB
- Complex query and aggregation could be handled on Dolthub side, saving power of Observablehq side when handling large amount of data

**Comment by CobusT** [comment]
Since there is an API interface to Dolthub-hosted databases (limited to 200 rows, though) you can use it already using the DoltDatabaseClient here: 
https://observablehq.com/@observablehq/dolt

The nice thing is that these can be used in Public notebooks!

**Comment by Code2Life** [comment]
Awesome, thanks a lot !
