### ISSUE TITLE
Getting 404 on slug

### ISSUE THREAD

**Issue by JobLeonard** [observablehq/feedback#537]
Fil shared a notebook with me to keep tinkering with blue noise. I clicked on the `shared` link. The modal shows for a split-second before switching to a black screen with an application error. It happens consistently when refreshing. Attached a video because it happens too quickly to properly capture in a screenshot:

https://user-images.githubusercontent.com/259840/217211694-4f3a9988-779c-4de7-b77b-84d21d82191a.mp4

Here is an image of the devtools console:

![image](https://user-images.githubusercontent.com/259840/217212883-6c8bcd2a-be6c-4a39-b556-5b4d75397717.png)

It's all minified of course so no idea what's happening :sweat_smile: 

Linux, Firefox 109.1

**Comment by mootari** [comment]
Thanks for the report, and sorry for the trouble! I expect we'll have a fix out shortly. 🙏🏻

**Comment by mootari** [comment]
This should be fixed now. Thanks again!
