### ISSUE TITLE
API error responses lack CORS headers

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#54]
**Describe the bug**
The public API endpoint for notebook modules (e.g. `https://api.observablehq.com/@observablehq/demo.js?v=3`) serves CORS headers to allow for client-side consumption (usually via static imports).

However, error pages don't serve CORS headers, making it impossible to discern the nature of the error via a fetch request. The error pages in question are:
- `404` in case of an inaccessible notebook slug or version,
- `429` in case of active Cloudflare DDOS protection.

**Expected behavior**
- For `404` responses, add the header `access-control-allow-origin: *`
- For `429` responses, add the header `access-control-allow-origin: *`
- For `429` responses, add the header `access-control-expose-headers: retry-after`

**Comment by jrus** [comment]
As a follow-up: when imports from one notebook to another fail due to Cloudflare DDOS protection, it would be good to have a more meaningful error message within the notebook. Right now it throws up a confusing message about CORS.

Related discussion, [talk/4684](https://talk.observablehq.com/t/4684)

**Comment by mootari** [comment]
Update: 404 errors now have CORS headers! 🎉

**Comment by wiltsecarpenter** [comment]
Can this be closed now?

**Comment by CobusT** [comment]
Wiltse, we are still looking at the 429 errors

**Comment by visnup** [comment]
Related https://community.cloudflare.com/t/cors-on-rate-limit-429/270010

**Comment by mootari** [comment]
Have there been any new insights regarding CORS for Cloudflare's `429` responses? I would love to be able to read out the "retry-after" header.

**Comment by visnup** [comment]
We don't seem to have much control over the _headers_ for the 429 response. If that changes or if someone ever finds a Cloudflare solution in the future, we can re-open.
