### ISSUE TITLE
png/svg download to include legend?

### ISSUE THREAD

**Issue by ijlyttle** [observablehq/feedback#541]
I don't know if this is a `Plot` question or an `observablehq.com` question, but I thought I'd start here.
 
On any of the charts with legends here: https://observablehq.com/@observablehq/plot-legends, if I click "Download PNG" or "Download SVG", I get an image of the chart that does not include the legend. I imagine this follows from the legend being an add-on to the chart. 

Could there be a convenient way to get them both in an image download?

Thanks!

**Comment by Fil** [comment]
I tried my luck and github let me do it :)

**Comment by ijlyttle** [comment]
@fil Thanks! The [html-to-image tool](https://observablehq.com/@fil/hello-html-to-image) will let me do what I need to, looking forward to an update in observablehq :)

**Comment by CobusT** [comment]
This now works! Try it out and let us know if you run into other issues.
