### ISSUE TITLE
Share source code for data-table-cell

### ISSUE THREAD

**Issue by slowkow** [observablehq/feedback#547]
Is it possible to use data-table-cell outside of Observable in a vanilla JS page?

https://observablehq.com/@observablehq/data-table-cell

![Screenshot 2023-03-03 at 11 15 05 AM](https://user-images.githubusercontent.com/209714/222771471-e31340dd-4c4a-48fc-8908-697188185a7b.png)

I use [Tabulator](https://github.com/olifolkerd/tabulator), but I like that data-table-cell displays the summary stats above each column, and I like the user interface.

**Comment by CobusT** [comment]
Unfortunately not. This is proprietary to the Observable platform.
