### ISSUE TITLE
"eject to JavaScript" option in the cell header of chart cell missing

### ISSUE THREAD

**Issue by urswilke** [observablehq/feedback#559]
Sorry, if I'm missing something obvious, but it seems as if the "eject to JavaScript option () in the cell header" (As described [here](https://observablehq.com/@observablehq/chart-cell#cell-263) (in the last paragraph)) has disappeared. Quite sure it was there yesterday..

**Desktop:**
 - OS:  Arch Linux
 - Browser:
   - chrome: Version 111.0.5563.110 (Official Build) (64-bit)
   - Firefox: 111.0.1 (64-bit)

**Comment by mootari** [comment]
Apologies for the confusion! We moved the option to the "add cell" menu below the chart cell:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/322014/229131169-6cc4f711-2063-4712-90ed-afab4407cd2e.png">

I'll leave this issue open until we've updated our docs.

**Comment by tophtucker** [comment]
All my bad! I've updated the docs. I know it feels like a sort of cruel joke to move something right after launching it… a couple other things might move yet, but we'll make sure to keep the docs in sync.

Always tough to balance getting things out when we know there's more to be done, vs. refining in private so we don't move things around on you! In this case we erred on the side of the former; the upside is that getting that outside perspective is invaluable to help us prioritize everything we could be doing.

While I've got you here: currently, "Convert to JavaScript" converts to a Plot.auto mark, which itself creates a dot, rule, bar, rect, etc. We have a [notebook](https://observablehq.com/@tophtucker/convert-plot-auto-to-explicit-marks) that converts Plot.auto to those explicit marks. Would it be valuable to you to have the option to convert the chart cell to that sort of explicit mark instead?

**Comment by tophtucker** [comment]
Thanks @urswilke. I'm going to close this issue since the original documentation issue has been resolved; I split off the explicit marks thing to https://github.com/observablehq/feedback/issues/560. Feel free to open a new issue for anything else I haven't covered.
