### ISSUE TITLE
data loss when browser navigates or reloads with uncommitted cell changes

### ISSUE THREAD

**Issue by jrus** [observablehq/feedback#56]
**Description:** If a notebook author reloads a page or navigates/closes a browser tab with uncommitted cell changes, these are lost. Observable should instead pop up a modal warning/confirmation before allowing the browser to navigate away.

**Steps to reproduce:** (1) Open any notebook, (2) make some changes in a cell but do not commit them (that is, keep the cell editor focused and do not press shift-enter or click the 'execute cell' button), (3) close the browser tab, (4) re-open the notebook.

[Instead of closing the tab in step (3), can also navigate the tab to a new URL, or refresh the notebook page]

**Expected behavior:** The notebook should never lose data without warning. If there are unsaved changes in a cell editor, the page should pop up a modal warning before allowing the page to close.

**Actual behavior:** Any uncommitted changes are irrevocably lost, potentially losing substantial amounts of work.

Past discussions: [talk/1959](https://talk.observablehq.com/t/1959), [talk/2074](https://talk.observablehq.com/t/2074)

**Comment by CobusT** [comment]
Right now, we stash those edits even if the cell has not been run, so when you return to the browser window after closing it, your uncommitted edits would still be there. Can you please verify on your end if this now working?

**Comment by CobusT** [comment]
Closing this since uncommitted changes are actually not lost (at least not in my testing...). @jrus please re-open if you find that this is not working for you.
