### ISSUE TITLE
Option to convert chart cell to explict marks instead of Plot.auto

### ISSUE THREAD

**Issue by tophtucker** [observablehq/feedback#560]
Requested by @abenrob in Slack, seconded by @urswilke in https://github.com/observablehq/feedback/issues/559, and also by others elsewhere; here's a notebook that does it: https://observablehq.com/@tophtucker/convert-plot-auto-to-explicit-marks

**Comment by CobusT** [comment]
I think this can be closed now. This feature has been added.
