### ISSUE TITLE
Suggest the Range input snippet in autocomplete when the user types `range`

### ISSUE THREAD

**Issue by yurivish** [observablehq/feedback#567]
**Is your feature request related to a problem? Please describe.**
I frequently create range inputs using the snippet provided in autocomplete, but the option I want is always the second option list and I would prefer it to be the first option.

**Describe the solution you'd like**

The snippet should appear first in the autocomplete list.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/114388/232551867-5fb2ed44-3e3e-433f-a9a2-3a1bc9f5b86b.png">

**Comment by mootari** [comment]
If you type "Ran" instead of "ran" the snippet should already appear first in the list.

**Comment by yurivish** [comment]
It like there may be a regression here, as I no longer see the range input in the list of autocomplete options (a few examples are below):

<img width="407" alt="image" src="https://github.com/observablehq/feedback/assets/114388/98bcecaf-b5b6-4b11-b4c8-4b6c0ca6c1cb">

<img width="413" alt="image" src="https://github.com/observablehq/feedback/assets/114388/0b49d23c-a728-4478-b58d-ddfb7e2edfe6">

**Comment by mbostock** [comment]
You’ll get it if you type “slider”, but yea… Ideally it should match both, but it not, we should use the name “Range input” since that’s what Observable Inputs and HTML uses.
