### ISSUE TITLE
Add Option to "de-select" all columns in Table Cell

### ISSUE THREAD

**Issue by asg017** [observablehq/feedback#570]
**Is your feature request related to a problem? Please describe.**

When my table data has dozens of columns and I only care about a few of them, I currently have to de-select all of them one-by-one which is extremely tiring.

![image](https://user-images.githubusercontent.com/15178711/232633245-3a2019f6-cd55-4f31-9418-78e6d53b26fa.png)

**Describe the solution you'd like**
A new "deselect all cells" option at the top that will de-select all the columns in the list. Kindof like the "show all" option that appears, but does the exact opposite.
![image](https://user-images.githubusercontent.com/15178711/232633290-679e1512-e9d3-42d7-a5c5-48c6c2b6d9b9.png)

**Describe alternatives you've considered**
Clicking all the columns one by one to turn them off. Very tedious, though

**Additional context**

**Comment by annie** [comment]
@asg017 there's an "only" button that shows up to the right of any column when you hover over it, and you can click that to select _only_ that column. that should let you quickly deselect all other columns and then build up your selection from there.

**Comment by asg017** [comment]
I had completely missed that - thank you!
