### ISSUE TITLE
Data table cell nto working in runtime enviroment (embed: react js app )

### ISSUE THREAD

**Issue by nikitok** [observablehq/feedback#575]
**Describe the bug**

I tryed export code to  "runtime with react"  this notebook: https://observablehq.com/d/e452a4e7e3bd4233

But, cell with "Data table cell" not displayed. 
I want to fix it behaviour, but, i think, this abbility not support in external runtime?

**Comment by mootari** [comment]
The table display is a proprietary component that is only available within Observable.
