### ISSUE TITLE
The footer in the Settings page has the wrong style

### ISSUE THREAD

**Issue by nachocab** [observablehq/feedback#585]
On most pages, the footer has a linear-gradient to prevent it from clashing with the sidebar (although it's a bit weird that it starts cutting off elements when there's so much free space above it):

<img width="262" alt="CleanShot 2023-07-29 at 08 46 01@2x" src="https://github.com/observablehq/feedback/assets/27538/b2fdad5b-44d6-436b-be72-2e2c24be933d">

However, in the settings page, the CSS is not the same and it clashes with the sidebar when zoom >= 150%

<img width="338" alt="CleanShot 2023-07-29 at 08 36 37@2x" src="https://github.com/observablehq/feedback/assets/27538/74fa97e2-fc45-436d-9a43-c8b6b536867d">

**Comment by CobusT** [comment]
Thanks for raising this!

**Comment by CobusT** [comment]
This issue was resolved by the new navigation that was released last week.
