### ISSUE TITLE
Can't create runnable blank notebook

### ISSUE THREAD

**Issue by pearmini** [observablehq/feedback#587]
**Describe the bug**

Can't create runnable blank notebook.

**To Reproduce**
1. Click `New`
2. Choose `Blank Template`

**Expected behavior**
Create a new runnable blank notebook.

**Screenshots**

![image](https://github.com/observablehq/feedback/assets/49330279/0b812cb5-7684-468a-9884-627db5a09f0f)

Open the console:

![image](https://github.com/observablehq/feedback/assets/49330279/2bf5608f-44fe-4aca-a87d-0b1a78bb4061)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 90.0.4430.212（正式版本） (arm64)

**Additional context**

- The notebook has already been created, but every time I click it, it will act like screenshots above.
- Other template can be created properly.

**Comment by tekgrrl** [comment]
Hi there, Is there any way that you can upgrade to a version of Chrome later than version 92? That should resolve the issue. 

Let us know if it's not possible for you to upgrade at this time. We'd be interested to hear why you cannot as we are currently looking at what minimum versions of browsers to support.

**Comment by pearmini** [comment]
When I update my chrome to `115.0.5790.170`, it works! Thanks a lot!
