### ISSUE TITLE
Downloading large attachments from Google stalls

### ISSUE THREAD

**Issue by boxfoot** [observablehq/feedback#589]
**Describe the bug**

Observable frequently (but not always) stalls out when loading large cloud attachments from Google.  This regularly happens to me with attachments larger than ~50MB. Sometimes they load normally and everything is fine.  Other times, the download seems to stall and Observable remains in a loading state indefinitely.

I've noticed that this seems to happen day by day -- on some days, everything will load as expected (no matter how many times I reload a notebook) and other days, the stalling behavior will happen consistently (no matter how many times I load the behavior).

The stalling can be watched by opening the chrome developer console, going to the network tab, and filtering requests for those named `file?token= ...`.  Initially, this load as expected, and then stop suddenly when the file has not been fully downloaded.

**To Reproduce**
1. Upload a large (~100MB) csv file to google drive.  Make sure it's a CSV file, not a google sheet.
2. Create a new notebook and pull in that google drive file.
3. Add a cell to the notebook, something like `FileAttachment("google://AllRecords.csv").text()`
4. Cell never loads (except when it does)

**Expected behavior**
Attachment should load and be available for use in sheet.

**Screenshots**

Showing loading status after several minutes of sitting:
![image](https://github.com/observablehq/feedback/assets/487130/6523148c-4984-4547-b98e-a95dbbe3b7a9)

Network panel showing two stalled attempts to load the file:
![image](https://github.com/observablehq/feedback/assets/487130/c7b1c8f1-7438-4ab8-a3b1-37bf9c1c1f2c)

Details from one of the requests:

![image](https://github.com/observablehq/feedback/assets/487130/923624cc-8e18-4c31-83c0-d5f8b36e226b)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser  arc and chrome (happens in both)
 - Version 115

**Additional context**
I wonder if this is related to #576 .   And it would be much less of a pain if #580 or similar were available, because we'd be less dependent on downloading files repeatedly.

**Comment by CobusT** [comment]
I have been testing this with a 5,000,000 row csv file on Google Drive (111MB). It does seem to load every time for me, but sometimes it is slower than other times. When we looked at our logs, we did notice your incomplete cloud file requests with an error "Client Request Interrupted”. I assume that is when you either refreshed or closed your browser? Wondering whether it would show up if you just wait long enough? For my test, I had to sometimes wait for a whole minute for the file to download...

**Comment by boxfoot** [comment]
@CobusT i am not aware of actions I took on my side to interrupt the request -- and I sometimes would leave it sitting for 10-30 minutes to see if it would resume.  But like I said in the post it's really uneven -- some days no issues and other days a lot.  Today is a "everything is working" day for me...

**Comment by CobusT** [comment]
Closing this issue for now, but feel free to re-open if discover any patters that you think could be causing this intermittent problem.
