### ISSUE TITLE
Make Observable more Social: Follow other users/creators

### ISSUE THREAD

**Issue by Daynex** [observablehq/feedback#59]
**Is your feature request related to a problem? Please describe.**
I love Observable and the fact that I can create anything from scratch with zero setup is amazing. To me the second best feature of Observable is the ability to share content and to see and learn from others. Unfortunately as of me writing this, there isn't a possibility to follow people. so I need to manually go to my favourite users profile to check if they maybe added new content.

**Describe the solution you'd like**
How to follow:
1. Go to a users profile. 
2. Button to follow/unfollow

What following means
1. Get their latest published notebooks onto my feed 
2. Notifications (maybe)
3. Anything else?!

**Describe alternatives you've considered**
Not sure if there is a alternative to this.

**Additional context**

**EDITED**
1.  Fixed some grammar and spelling issues (Sorry, not a native)

**Comment by jrus** [comment]
**Current workaround:** use RSS. Here's a screengrab of my feed reader:

<img width="800" alt="Screen Shot 2021-03-25 at 11 35 02 AM" src="https://user-images.githubusercontent.com/83411/112525525-345ec380-8d5e-11eb-8ff9-04ca80a0548f.png">

**Comment by jrus** [comment]
In lieu of waiting for platform changes, I think it should be possible to build a "follow authors" feature inside a notebook (maybe viewed in 'embed' view to take up more of the browser window) that stores a list of the followed authors' notebooks and whether you have seen them or not, and presents several panes with a list of authors, list of their notebooks, and a rendered notebook when you click one.

It would take a substantial amount of work to get the details right, but all the pieces are already there.

You can see a list of a particular author's notebooks at [@mootari/sortable-notebook-list](https://observablehq.com/@mootari/sortable-notebook-list).

**Comment by Daynex** [comment]
Hi @jrus!

Thank you for your two suggestions. I really appreciate you taking the time to help me!
I especially like the Observable notebook idea by @mootari and will probably go with that for now. 

I am curious to hear what the Observable Team thinks about the idea and if they intend to make ObservableHQ even more social or if they maybe have a different strategy in mind 😊😎

**Comment by j-f1** [comment]
Ooh, interesting! It should also be possible to fork NetNewsWire and have it render notebooks on RSS feeds with notebook URLs

**Comment by Daynex** [comment]
Hi @j-f1!

NetNewsWire seems like a cool, useful tool. Thanks for sharing!

**Comment by jrus** [comment]
> Ooh, interesting! It should also be possible to fork NetNewsWire and have it render notebooks on RSS feeds with notebook URLs

Let me try to figure out if adding the appropriate notebook-embedding code (e.g. for an iframe version) to the feed will make it show up in a feed reader. See [@jrus/feed](https://observablehq.com/@jrus/feed).

**Comment by triptych** [comment]
Note one thing  -  following other users is the action someone takes, but the point is that followed users content also shows up in some way in a feed  - like on my dashboard.  It's about discovery as well as a 'network' - I follow X because they post  cool notebooks and I want to be notified / informed when they post a new notebook, or update an existing one.

**Comment by mootari** [comment]
Solved by the follow feature that was released last month ([see release notes](https://observablehq.com/@observablehq/release-notes#cell-2960)).
