### ISSUE TITLE
Unexpected characters in mobile Chrome 

### ISSUE THREAD

**Issue by nachocab** [observablehq/feedback#594]
**Describe the bug**
When editing a cell using mobile Chrome (at least in Android), typing some keywords results in special characters being added. They can't be deleted and they cause a syntax error. 

**To Reproduce**
1. Create a new Javascript cell using the latest mobile Chrome (Firefox doesn't have this issue) 
2. Type "new" and hit space
4. Two red dots appear which results in a syntax error. They can't be deleted. They appear to be  the [Object replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#OBJ). Here's a [live example](https://observablehq.com/d/59b5482d18ee5664#cell-79).

Screenshot:
<img width="783" alt="CleanShot 2023-08-22 at 19 54 15@2x" src="https://github.com/observablehq/feedback/assets/27538/657cffd6-6c18-4f71-97aa-e0a1427685d8">

**Comment by mootari** [comment]
@nachocab Do you get the same behavior when typing in the demo editor on https://codemirror.net/ ?

And could you perhaps try a different on-screen keyboard that is tailored to code input, like [Hacker's Keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)?

**Comment by nachocab** [comment]
Thanks, @mootari I don't get the same behavior on CodeMirror, but the issue does go away if I switch to Google Keyboard (Gboard) instead of Microsoft Swiftkey, so I'm closing this issue.
