### ISSUE TITLE
HTML as a basic option when creating a new cell

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/feedback#595]
When creating a new cell I would like to see **HTML** as a basic cell option.
![image](https://github.com/observablehq/feedback/assets/121805/c5097456-b4d9-4c07-9c4e-dc6cbdfce2aa)

**Comment by galopin** [comment]
See [Add Cell Bar and Menu Enhancements Feedback](https://github.com/observablehq/feedback/issues/592#issuecomment-1719132996)…

**Comment by tophtucker** [comment]
We’ve reverted to the older add cell menu, which has HTML as the third option. See https://github.com/observablehq/feedback/issues/592#issuecomment-1850880821 for more context. Thanks for the feedback!
