### ISSUE TITLE
Liked notebooks by me

### ISSUE THREAD

**Issue by manishipro** [observablehq/feedback#596]
I have liked many chart notebooks but now I want to see list of all those liked charts then how can I see that, if we can't see that then we should have that feature.

**Comment by mkfreeman** [comment]
Hi @manishipro! You can now view your likes by first selecting _View public profile_ (or navigating directly to https://observablehq.com/@YOUR-USER-NAME?tab=profile):
<img width="533" alt="Screenshot 2023-09-21 at 11 08 52 AM" src="https://github.com/observablehq/feedback/assets/1373882/95020486-2e4b-4a90-8272-113f5ae194f0">

And then clicking on the likes tab.
<img width="790" alt="Screenshot 2023-09-21 at 11 09 10 AM" src="https://github.com/observablehq/feedback/assets/1373882/f16435fa-b775-4c1c-a27b-3a0b09912ebb">

We appreciate your feedback, and are taking it into consideration with this new location of the _likes_. 

Let us know if you have any other questions or feedback.

**Comment by mkfreeman** [comment]
To clarify, the instructions above assume that your side navigation is set to your individual account. You can alternatively click your avatar in the top right corner to navigate to your personal profile: 
<img width="216" alt="Screenshot 2023-09-21 at 11 30 11 AM" src="https://github.com/observablehq/feedback/assets/1373882/2a21a5a2-2fb3-4be2-858a-eedd6f53c5a2">
