### ISSUE TITLE
The option to click between cells to add a new cell make inputs hard to use

### ISSUE THREAD

**Issue by LaoTzunami** [observablehq/feedback#598]
**Describe the bug**
I keep on accidentally adding new cells when trying to use single row input cells.

**To Reproduce**
1. Go to any notebook that has single row inputs that control other cells.
2. Try to click the input fields with your big thumbs on a smart phone or quickly with a mouse when you are distracted presenting it to other people.
3. When you inevitably add a new cell by accident instead of what you were trying to do, quickly try to close the UI while apologizing to the audience.

**Expected behavior**
It was much better when you added a cell by clicking on the + icons on the left. Please do not add cells by clicking between existing cells. If you guys must have that option, please shrink the area between cells that adds a new cell so it is harder to click by accident. 

**Example**
This is the notebook I was trying to present, but most notebooks use this kind of setup:
https://observablehq.com/d/525efdbf20cbb541

**Comment by galopin** [comment]
See [Add Cell Bar and Menu Enhancements Feedback](https://github.com/observablehq/feedback/issues/592#issuecomment-1718081066)…

**Comment by tophtucker** [comment]
Thanks for the feedback and colorful reproduction steps. I and others shared your experience. We’ve reverted to the older add cell menu, including removing the blue bar you describe that let you click anywhere between cells to add a cell. See https://github.com/observablehq/feedback/issues/592#issuecomment-1850880821 for more context.
