### ISSUE TITLE
https://observablehq.com/settings/api-keys throws a 500 error.

### ISSUE THREAD

**Issue by oksure** [observablehq/feedback#601]
**Describe the bug**
As the title says, when I went to that URL to change my notebook key, I encountered the 500 error.

**To Reproduce**
1. Sign in.
2. Go to 'https://observablehq.com/settings/api-keys'
3. Error shows up, saying "Application error: a client-side exception has occurred (see the browser console for more information)."
4. The JS console says, "TypeError: Cannot read properties of null (reading 'map')" and " A client-side exception has occurred, see here for more info:"

**Expected behavior**
My notebook keys should show up.

**Screenshots**
![Screenshot 2023-10-14 at 3 49 02 AM](https://github.com/observablehq/feedback/assets/35975/d8e48c89-ab9f-4ebb-b9bc-d6c1230ea67a)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser Chrome
 - Version 117

**Smartphone (please complete the following information):**
The same error occurs on the iPhone Chrome.
 - Device: iPhone
 - OS: iOS
 - Browser Chrome
 - Version Don't Know

**Additional context**
None.

**Comment by mythmon** [comment]
@oksure Thanks for the bug report! We've found the likely issue and fixed it on our end. Can you try again?

**Comment by oksure** [comment]
@mythmon Thanks for the quick fix. The page itself loads now. I do have one quick follow-up question.

[This help page](https://observablehq.com/@observablehq/api-keys#cell-183) shows tabs allowing me to select between API Keys and Notebook Keys. However, I do not see the Notebook Keys tab in my Settings > API / Notebook Keys page. (See screenshot below; it only shows API Keys.) I do not know where I can manage my existing Notebook keys. I made sure I created some Notebook keys for some private notebooks.

![Screenshot 2023-10-14 at 10 22 32 AM](https://github.com/observablehq/feedback/assets/35975/89da29b4-ccb4-4c2e-9413-adb66cd8285f)

Thanks for the quick follow-up!

**Comment by mootari** [comment]
@oksure We can reproduce the problem. While we work on a fix you should be able to access your notebook keys by following this link: https://observablehq.com/settings/api-keys?tab=notebookKeys

**Comment by oksure** [comment]
Thanks for the quick resolution. I suppose notebook keys can be retrieved at the time of creation not later in that setting pane. Anyways, all my issues in this thread are resolved. Thanks!

**Comment by CobusT** [comment]
You should now be able to see the tab in settings for Notebook keys. Thanks again for reporting it!
