### ISSUE TITLE
Unexpected Plot Output in Electricity Guide (2 of 6)

### ISSUE THREAD

**Issue by homerhanumat** [observablehq/feedback#604]
**Describe the bug**

In Part 2 (of 6) of the Guide ["Electricity use vs. temperature"](https://observablehq.com/guide/electricity), when one modifies the plotting code as directed the legend shows up but the line colors remain black.  (See attached screenshot.)

**To Reproduce**

1. Go to ["Electricity use vs. temperature"](https://observablehq.com/guide/electricity)
2. Go to 2 of 6
3. Copy the suggested text from the right sidebar.
4. In the plot code-cell, delete the closing `]`.
5. Paste the suggested text.
6. Run the cell.

**Expected behavior**

Plot shown with legend and lines colored accordingly.

**Screenshots**

<img width="1208" alt="Screenshot 2023-10-30 at 9 08 10 AM" src="https://github.com/observablehq/feedback/assets/5505653/e481b5e6-edb4-424f-aa17-af1f312b6d29">

**Desktop (please complete the following information):**

 - OS: Mac OS Vnura 13.5.2
 - Browser Firefox
 - Version 116.0.2

**Additional context**

Also, when one presses the Show Me button, the plot appears in the expected way, but it in the code-cell one for the plot can remove the colors option, run the cell, and still the plot shows up with legend and colors.

**Comment by mootari** [comment]
Take a closer look at the second paragraph in the step description:
> First, change the z: "city" assignment in the Plot.lineY call to stroke: "city". This assigns different colors to the two cities.

**Comment by homerhanumat** [comment]
Ah, sorry.

**Comment by mootari** [comment]
No worries! Thanks for taking the time to create this issue, and please let us know if you have any other feedback regarding the guides. 🙂
