### ISSUE TITLE
I need to create graph with single x-axis and y-axis but on y axis I need to plot different types of graph(like bar chart, line chart, stock chart) with same x-axis, How to develop this in angular 14?

### ISSUE THREAD

**Issue by PriyankaDaptare** [observablehq/feedback#611]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mootari** [comment]
This repository is intended for platform feedback. Please post help requests to our forum: https://talk.observablehq.com/
