### ISSUE TITLE
I can't delete my account.

### ISSUE THREAD

**Issue by Vince489** [observablehq/feedback#612]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vince489** [comment]
![Screenshot 2023-12-21 131514](https://github.com/observablehq/feedback/assets/105140528/a89eee0d-39a9-4849-808b-9794d005d803)

**Comment by mootari** [comment]
@Vince489 The ":" is not part of the phrase. The exact phrase is:
```
delete my account
```

**Comment by CobusT** [comment]
Also, you should enter your username `prince-vince` (Prince Vince is your display name).

**Comment by mootari** [comment]
I'm going to close this issue. Please let us know if you continue to encounter difficulties.

**Comment by Vince489** [comment]
I tried that 1st. That didn't work either

**Comment by mootari** [comment]
@Vince489 To summarize, in the first field you need to enter
```
prince-vince
```
and in the second field
```
delete my account
```
Once you've entered the correct information the button at the bottom will become red:

<img width="577" alt="image" src="https://github.com/observablehq/feedback/assets/322014/63750712-b17f-49b3-93ae-628fe912f282">


After you click the button you will get logged out and receive an email that confirms your deletion request.
