### ISSUE TITLE
csvURL in 'Working with APIs & remote files' returns 404

### ISSUE THREAD

**Issue by flrd** [observablehq/feedback#618]
Hello, 

the URL of the example .csv in [Working with APIs & remote files](https://observablehq.com/@observablehq/working-with-apis-remote-files?collection=@observablehq/working-with-data) is not found, I added the new URL below. 

**To Reproduce**
1. Go to Working with APIs & remote files, section '[Fetch CSV data](https://observablehq.com/@observablehq/working-with-apis-remote-files?collection=@observablehq/working-with-data#csvURL)'
2. `csvURL` returns 404

**Expected behavior**
`csvURL = https://raw.githubusercontent.com/max-mapper/csv-spectrum/master/csvs/comma_in_quotes.csv`

Best
Markus

**Comment by mootari** [comment]
Updated, thanks!
