### ISSUE TITLE
Self-Hosted Database Proxy Connection Issue

### ISSUE THREAD

**Issue by markwestm** [observablehq/feedback#622]
I am trying to create a self-hosted database proxy connection by following the instructions provided in the following link. We have an organizational account. I have two PostgreSQL databases on my machine. I am using the latest version of Edge. My OS is Windows 11 Enterprise.

https://observablehq.com/@observablehq/self-hosted-database-proxies

After installing the database proxy via npm, I try to add my database using the observable-database-proxy add testdb command. I use the name of my database vice testdb. At that point a browser window opens up asking me to choose an account. I pick our organizational account. I am then taken to a page saying "Sorry, you’re not allowed to access this page.". Please see the image below.

My manager shared his SSL certificate with me, which I added to my console root as a potential fix. However, I'm not sure how to attach the certificate to the web request that is made for connecting to the Observable site.

<img width="1056" alt="access-not-allowed" src="https://github.com/observablehq/feedback/assets/163023309/cac71672-e1ca-4e49-ad75-7eef577aa0d6">

Please let me know if you need additional details. Thanks in advance for your help.

Regards, Mark

**Comment by CobusT** [comment]
Hi Mark.

Let's take this discussion to our support channel (support@observablehq.com) where we can be of more assistance since I suspect the answer is related to membership permissions on your organizational account. Would you mind sending a short request to that email (you don't have to retype all of this, just reference this GH issue) since I don't want to discuss your specific account in a public forum.

Thanks!
Cobus

**Comment by markwestm** [comment]
Per the e-mail below, I am forwarding to support. Please let me know if you need additional information.

Regards, Mark




Mark West
IoT Engineer IV
Tel: (800) 327-8723 x 10880
E-Mail: ***@***.******@***.***>

[https://sonwebstor01.blob.core.windows.net/signature/sonnys-cw-controls-email-signature.png]
www.<http://www.sonnysdirect.com/>SonnysDirect.com<http://www.sonnysdirect.com/>



The information in this e-mail message may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, any dissemination, distribution or copying is strictly prohibited. If you think that you have received this e-mail message in error, please e-mail the sender and delete all copies.

**Comment by markwestm** [comment]
Hi Mark. 
When I looked at your account, I noticed that you are a viewer on that workspace. In order to configure a database, you need to be an editor. Please reach out to your workspace owner (Ken Martin) and request to be upgraded to an editor, or you can ask him to set up the proxy for the workspace.
Please let me know if you run into any other issues while setting this up.
Regards
Cobus

—
Cobus Theunissen
Head of Customer Success @ Observable
***@***.***

--- original message ---
On March 13, 2024 at 5:31 PM PDT ***@***.*** wrote:



Per the e-mail below, I am forwarding to support. Please let me know if you need additional information.



Regards, Mark




Mark West
IoT Engineer IV
Tel:(800) 327-8723 x 10880
E-Mail: ***@***.***


www.SonnysDirect.com



The information in 
this e-mail message may be privileged, confidential, and protected from 
disclosure. If you are not the intended recipient, any dissemination, 
distribution or copying is strictly prohibited. If you think that you have 
received this e-mail message in error, please e-mail the sender and delete all 
copies.

From: CobusT ***@***.***> 

Sent: Wednesday, March 13, 2024 7:13 PM

To: observablehq/feedback ***@***.***>

Cc: Mark West ***@***.***>; Author ***@***.***>

Subject: Re: [observablehq/feedback] Self-Hosted Database Proxy Connection Issue (Issue #622)





You don't often get email from
***@***.*** 
Learn why this is important




Hi Mark.

Let's take this discussion to our support channel ***@***.***) where we can be of more assistance since I suspect the answer is related to membership permissions on your organizational account.
Would you mind sending a short request to that email (you don't have to retype all of this, just reference this GH issue) since I don't want to discuss your specific account in a public forum.

Thanks!

Cobus

—

Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

You are receiving this because you authored the thread.Message
ID: ***@***.***>

WARNING: This email originated from outside of the organization. Do not click on links or open attachments unless you recognize the sender and know the content is safe.
--- end of original message ---

**Comment by markwestm** [comment]
Cobus,

Thanks so much. I spent hours today trying to resolve the issue.

Regards, Mark




Mark West
IoT Engineer IV
Tel: (800) 327-8723 x 10880
E-Mail: ***@***.******@***.***>

[https://sonwebstor01.blob.core.windows.net/signature/sonnys-cw-controls-email-signature.png]
www.<http://www.sonnysdirect.com/>SonnysDirect.com<http://www.sonnysdirect.com/>



The information in this e-mail message may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, any dissemination, distribution or copying is strictly prohibited. If you think that you have received this e-mail message in error, please e-mail the sender and delete all copies.
