### ISSUE TITLE
Browser > Window menu continues to show old notebook title after change

### ISSUE THREAD

**Issue by Martien** [observablehq/feedback#626]
Browser > Window menu continues to show old notebook title after change.

1. Notebook was titled “Argumentenkaart gemengde scholen”.
2. Renamed notebook to just “Gemengde scholen” by changing the first markdown cell into `# Gemengde scholen`.
3. Changed the URL as well to`/@martien/gemengde-scholen`.
4. Refreshed page/Quit browsers/Emptied caches.
5. Notebook title in browser > Window menu continues to show old title.

Expected to see new title throughout.

**Desktop**
 - OS: macOS 12.7.3 (Monterey)
 - Browser chrome, safari, firefox

**Comment by mootari** [comment]
Unfortunately dynamic titles are not supported. You'll have to replace your interpolated value with a static string or you'll continue to see the title change seemingly at random.

**Comment by mootari** [comment]
As a workaround you can add a hidden title to your title cell:
~~~md
<h1 style="display:none">The actual title</h1>

# ${myDynamicTitle}
~~~
As long as this `h1` is the first element in your notebook it will always get picked as title.

**Comment by Martien** [comment]
Thanks.

The dynamic title is indeed what caused it.

I tried your workaround with success.

Next, I removed the workaround, and now it shows the proper title.

**Comment by mootari** [comment]
> Next, I removed the workaround, and now it shows the proper title.

I recommend to keep the hidden title or just provide a static one. Observable will only register title changes if you also edit the first cell.
