### ISSUE TITLE
Notebook Comments Disappear

### ISSUE THREAD

**Issue by gallowayevan** [observablehq/feedback#633]
**Describe the bug**
I have tried a couple of times to comment on a cell within this notebook: https://observablehq.com/d/6b2c7542cb8d1308. I can add the comment and then click "Comment" and the comment appears to be published. However, if I reload the page, the comment disappears.

**Expected behavior**
The comment appears even after page reload.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 125.0.3]

**Comment by mootari** [comment]
Thanks for the report! Could you try commenting on the [`@latest` version](https://observablehq.com/d/6b2c7542cb8d1308@latest) of the notebook and let me know if that works?

You can access the latest version by clicking "Paused" in the notebook header:
<img width="521" alt="image" src="https://github.com/observablehq/feedback/assets/322014/17550479-5ca3-441e-8724-7c4a0b2690f9">

**Comment by gallowayevan** [comment]
Thanks! Now I was able to post the comment and it stuck. To summarize, in order to comment, I need to make sure that I am commenting on the latest version of the notebook. Is that right?

**Comment by mootari** [comment]
That sounds correct! Observable does not support commenting on specific versions of a notebook, and a paused notebook is essentially displaying an older version. At a minimum we would need to ensure that the "Add comment" option is disabled, and then point you to the latest version instead.

**Comment by mootari** [comment]
We released an update that works around the restrictions of comments on older notebook versions. When you try to comment on a paused notebook you are now given the choice to navigate to the cell in the latest version:

<img width="578" alt="image" src="https://github.com/observablehq/feedback/assets/322014/d18c778a-725f-4b1f-aca7-6959cbc653a5">

I'm going to mark this issue as resolved, but please let us know if you still experience problems.
