### ISSUE TITLE
Unstyled CSS page flickering when debugging notebooks

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#634]
**Describe the bug**
CSS goes into a weird flashing loop with the debugger open on fresh notebook

**To Reproduce**
1. (go to any notebook) 
2. Open webdev debugger
3. [See](url) the page start doing flashes of unstyled text and making network requests in a loop

**Expected behavior**

**Screenshots**

https://github.com/observablehq/feedback/assets/1848162/acd9a422-89c2-4792-8585-be522df44e8f

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version  124

**Additional context**
FWIW the CSS file is a google webfont fetched by the worker.css

![image](https://github.com/observablehq/feedback/assets/1848162/5cfb5448-b951-4a77-ba4c-8580b02e5c57)

**Comment by mootari** [comment]
Your recording shows that you have a Chrome update pending which can cause all sorts of odd bugs until Chrome has been restarted.

Can you still reproduce the behavior after restarting Chrome?

**Comment by tomlarkworthy** [comment]
yeah tried upgrading and disabling all plugins and its still doing it. Not on Safari though 🤔

**Comment by mootari** [comment]
Happy to report that it's not an Observable bug. 😃

I just ran into the same issue and found that I had a [local override](https://developer.chrome.com/docs/devtools/overrides) for `static.observableusercontent/next/worker*.css` that triggered the font loading loop. Removing the override fixed the problem.

**Comment by tomlarkworthy** [comment]
Oh I just came back to say I finally figured it out, I had a local override on! lol. Damn the evidence is even in the screenshot I posted originally, the exclamation on the network tab indicated my dev tools was doing something weird.
