### ISSUE TITLE
New Joiner

### ISSUE THREAD

**Issue by Maidanss** [observablehq/feedback#636]
Dear group members,

I hope this message finds you well. My name is Salman Maidan, I am writing to express my interest in joining as a student.

I am interested in joining the group to further enhance my knowledge, I have been reading about Observable and find it very interesting. I have a little experience in database building and analysis. which is in Claris filemaker Pro.

By writing directly to the group I hope I have not broken any standards or regulations as I am new in the environment. 

I would be grateful for the opportunity. I look forward to joining and starting learning further.

Best regards,

Salman MaidanNovice in the subject

**Comment by mootari** [comment]
Welcome to Observable! We use this repository to collect bugs and feature requests for our platform, but you can [join our Slack](https://observablehq.com/slack/join) to connect with the community (we even have a channel where you can [introduce yourself](https://observable-community.slack.com/archives/C03STDM935X)), or ask questions on [our forum](https://talk.observablehq.com/). If you have questions related to your account, please email them to [support@observablehq.com](mailto:support@observablehq.com).
