### ISSUE TITLE
embedding runtime w/ javascript cannot determing notebook name

### ISSUE THREAD

**Issue by espinielli** [observablehq/feedback#639]
When I want to embed a plot/map and I select "Runtime with JavaScript" for my notebook [1] I get the following error
> chart = RuntimeError: Cannot determine notebook name
See snapshot below
![image](https://github.com/observablehq/runtime/assets/891692/797a9b0b-d798-4bfc-ae90-e1e9e1459a19)

This is showing in embedded cells I used since long [2]

[1] https://observablehq.com/@espinielli/co2-emissions-variation-per-state
[2] https://ansperformance.eu/efficiency/emissions/

**Comment by mootari** [comment]
The error is produced by https://observablehq.com/@endpointservices/serverless-cells@1964, not Observable.

I recommend you replace fetchp with corsproxy.io.

**Comment by espinielli** [comment]
Do you have an example for corsproxy.io?
I had it working in the past but not anymore...

**Comment by espinielli** [comment]
I do not understand why my url does not work
https://observablehq.com/@espinielli/fetch-mystery

**Comment by CobusT** [comment]
When I get the url with your function:
```
proxifyUrl(url)
```

and then open that url in the browser, I get this error:
```
{
"message": "Please create an account at https://accounts.corsproxy.io to proxy this file type."
}
```

You can see the same error when you type that url [here](https://corsproxy.io)

**Comment by espinielli** [comment]
Yes that I already did long ago...and then what? How do I use the account info/params if any?
(Sorry to bother you but I see no examples on how to get over it...and fetchp() works instead in the notebook but not in the embed)

**Comment by CobusT** [comment]
Ah, I see you have been discussing the problem with `corsproxy.io` [here](https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347?permalink_comment_id=4450412).

**Comment by espinielli** [comment]
Yes...and for the actual notebook I reverted to attached files...this is so annoying (and maybe it is due to some config on our webserver side? I do not know enough to dig further...).
I  was so happy that fetchp() worked but then discovered the side effect on embed...so I am yet again stuck...
Any hints / suggestions for investigating further are more than welcome.
