### ISSUE TITLE
"Share with…" autocomplete should ignore leading @ 

### ISSUE THREAD

**Issue by Fil** [observablehq/feedback#64]
**Describe the bug**
In Next, as the owner of a notebook I want to share it with `@anotheruser`. I type `@anotheruser` in the modal but it doesn't find them.

**To Reproduce**
<img width="848" alt="bug" src="https://user-images.githubusercontent.com/7001/113051537-5d3fe800-91a6-11eb-81ef-75bde836ce78.png">

**Expected behavior**
find the user, like when I don't type the @ 
<img width="815" alt="not bug" src="https://user-images.githubusercontent.com/7001/113051614-79438980-91a6-11eb-8b95-1e73d89efe5e.png">

**Comment by CobusT** [comment]
This should now work!
