### ISSUE TITLE
A d3 notebook for a tree hierarchy layed down on a timeline

### ISSUE THREAD

**Issue by pmartinolli** [observablehq/feedback#641]
**Is your feature request related to a problem? Please describe.**
I would like a simple notebook with the basic code to lay down a tree hierarchy on a timeline. 

**Describe the solution you'd like**
A d3 notebook would be great. The data could be hierarchy json (with nodes : nodes, date, tags; and edges : source, target). Zoomable timeline would be great, but accessory. 

**Describe alternatives you've considered**
I found this code online but its too complicated for me to adapt to ObservableHQ : http://lthrock.github.io/d3-genealogy/ and https://github.com/lthrock/d3-genealogy
I made something here https://observablehq.com/@pascaliensis/ttttrpg but it uses graphviz. So the dataviz is not smooth as it is with d3.

**Additional context**
It would be a great new sample in the library of basic codes. As a history scholar, I can say it would be a great tool for the digital humanities.

**Comment by mootari** [comment]
Hi, we reserve this repository for bug reports and feature requests for the Observable platform itself.

I recommend to signup to our community forum and post your question there as a new topic: https://talk.observablehq.com/
