### ISSUE TITLE
Open markdown links in new Tab by default

### ISSUE THREAD

**Issue by Daynex** [observablehq/feedback#66]
**Is your feature request related to a problem? Please describe.**

Having links open in new tabs is a personal preference, but let me explain and motive this:

> I want to make sure, that peoples workflow isn't interrupted while they are in the middle of a notebook. So instead of a link opening in the same tab, which means that you have to "go back" and find the spot you left from I want you to go to a new tab so that you can check out the content in the link and then return to where you left without any hassel.

**Describe the solution you'd like**
Any markdown link should open in a new tab by detail.

**Describe alternatives you've considered**
I currently use a self-made helper function [@daynex/helper-functions](https://next.observablehq.com/@daynex/helper-functions) for this.

**Additional context**
f you for example read a NY Times Article such as this one, any link will make you open a new tab. No-one wants to loose their customers/readers! The same goes for Twitter, Facebook, etc.

**EDITED**
- 02/04/2021 - Added examples (additional context) to other services, which handle link-opening in the suggested way.

**Comment by jrus** [comment]
Please don't break browser default behavior.

If a reader wants to open links in a new tab, they can use the standard browser method. (In Mac Safari, this is either command-click or right-click and select 'open link in new tab' from the contextual menu.)

**Comment by Daynex** [comment]
Hi @jrus,

Thank you for the feedback. I think you make a valid point!
At the same time this _default of behaviour_ seems to be regularly overwritten by many content providers, most likely for the reason I pointed out.

If you for example read a **NY Times Article** such as [this one](https://www.nytimes.com/2021/04/01/us/politics/biden-infrastructure-racial-equity.html?action=click&module=Spotlight&pgtype=Homepage), any link will make you open a new tab. No-one wants to loose their customers/readers! The same goes for **Twitter**, **Facebook**, etc.

**Comment by jrus** [comment]
Facebook et al. do this because they are poor web citizens whose top priority is keeping viewers ‘engaged’ on their own site so they can collect more ad money. It at least makes some sense for a social media platform where the expectation is that someone will skim headlines at the site and may want to open many background tabs without navigating around.

For the NYT, this behavior is really inexcusable, and someone should file bug reports / complain at them.

It’s too bad that the main browsers don’t have a preference setting to always or never opening links in new tabs when clicked (maybe with opposite behavior for modifier + click), instead of leaving the behavior up to the whims of website authors.

**Comment by mootari** [comment]
@CobusT I believe this issue can be closed with the resolution given in https://github.com/observablehq/feedback/issues/96#issuecomment-873326713.

**Comment by CobusT** [comment]
Indeed, we can close this issue. We are not planning on implementing this feature. See resolution in #96.

**Comment by ggutierrez123** [comment]
There are many instances where this would be helpful. Hope you consider to add this functionality.

**Comment by marcobispo** [comment]
It is a pit this cannot easily be done. It causes all sorts of problems in many use cases. For example, universities that use markdown code and then embed web pages in their LMS have problems with this lack of functionality. They don't want the links to open in the iframe and some websites won't open in the iframes. I'm sure there are plenty of other problems. I'm not sure I understand why you are so rigid on something that is important to many people.

**Comment by mootari** [comment]
@marcobispo Because it removes choice. This can't be a "default", because it cannot be overridden.

You can add the following snippet to your notebooks to force links to open in a new tab:
```javascript
{
  const handler = e => {
    if(e.target.matches("a[href]")) e.preventDefault(), window.open(e.target.href, "_blank");
  };
  document.body.addEventListener("click", handler);
  invalidation.then(() => document.body.removeEventListener("click", handler));
}
```
