### ISSUE TITLE
Improve display of sidebar on next.observablehq.com

### ISSUE THREAD

**Issue by j-f1** [observablehq/feedback#68]
A couple of suggestions:

- If there’s space, shift the notebook cell/output view to the left when opening a sidebar tab instead of shrinking it
- only animate the width of the notebook view when toggling the sidebar — resizing the window causes the notebook width to “lag” due to this animation.

**Comment by jrus** [comment]
By 'sidebar' do you mean the little help menu that opens when you click the little circled question mark icon at top right of the viewport?

**Comment by CobusT** [comment]
Would an overlay work better for the sidebar, so that the notebook would not resize or shift left at all? Just a thought.

**Comment by CobusT** [comment]
We removed the animation. Please let us know if this is still a concern.
