### ISSUE TITLE
Prettier formatting doesn't work in new UI

### ISSUE THREAD

**Issue by anandaroop** [observablehq/feedback#69]
**Describe the bug**
I have Prettier formatting ("Auto-format code") enabled on my `/settings` page, yet I don't see auto-formatting taking place while using the Next UI.

**To Reproduce**
1. Ensure "Auto-format code" is enabled in /settings.
1. Go to a new Notebook
2. Enter some code in need of formatting into a cell, e.g. <pre>console.log(  "does this",   {    get:  "formatted?"   })</pre>
3. Save the cell
4. See that auto-formatting HAS NOT taken place
5. Use the ••• menu to choose "Switch to Classic"
6. Edit and re-save the cell
7. See that auto-formatting HAS taken place

**Expected behavior**
Auto-formatting should take place in the Next UI if it is enabled in /settings

**Screenshots**
![prettier gif 5 128](https://user-images.githubusercontent.com/140521/113773654-49d7d400-96f4-11eb-8f12-a2515e7f34ad.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - Browser: Safari 13.1.13 as well as Chrome 89.0.4389.114

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
n/a

**Comment by anandaroop** [comment]
Realizing now that I may have been defaulted to the Next UI when I enabled "lab" features i.e. the collaborative editing. 

I am noticing other regressions with Next (visual mode; the little minimap widget for cell dependencies). Should I file them as issues here, or is it simply expected that Next is not at parity with Classic yet?

**Comment by CobusT** [comment]
Next is not parity yet. There are still quite a number of features that are being ported. Prettier is one of them. See https://observablehq.com/d/d9ddbfcb540d0512
No need to log these as bugs :-)

**Comment by anandaroop** [comment]
Makes sense, and thank you for the quick reply 😄 

(The notebook at that link wasn't visible though)
