### ISSUE TITLE
Suggestion on Shared (Unpublished) Notebook Automatic Publish Fork?

### ISSUE THREAD

**Issue by radames** [observablehq/feedback#72]
**Describe the bug**

After submitting a merging suggestion to a shared notebook from a different user, my forked notebook was automatically published. 
The same behavior has happened when I've sent a suggestion to a published notebook.

**To Reproduce**

Fork a shared notebook or published notebook, make edits, enable link sharing, then make a suggestion. Your forked notebook will now be published.

**Expected behavior**

Fork an unpublished notebook, make edits, send a suggestion, and the forked notebook stays private/unpublished.

**Additional context**

Is this related ? 
https://talk.observablehq.com/t/bug-unpublishing-a-notebook-closes-attached-suggestions/2408

**Comment by wiltse439** [comment]
Thanks for the bug report, we're investigating it now.

**Comment by wiltsecarpenter** [comment]
We identified the issue and have updated the service to correct the problem, and expanded our test coverage. Thanks very much for your helpful bug report.

**Comment by radames** [comment]
that's wonderful @wiltsecarpenter so quick! thanks
