### ISSUE TITLE
Better support for accents (diacritic) in search

### ISSUE THREAD

**Issue by john-guerra** [observablehq/feedback#73]
I have come to expect in search engines that when I search for a word on Spanish without an accent, I get results with accents as well. e.g. Searching for *ocupacion* should return also *ocupación". Currently this is not the case in Observable search, and because of it I have failed multiple times on finding my notebooks in Spanish. It would be awesome if this could be supported

Solution(?): match accented letters to non accented (diacritic) ones. This [stackoverflow answer](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript) seems to provide some good ideas on how to use it

**Comment by CobusT** [comment]
@john-guerra can you try this again? We just released some basic support for this.

**Comment by john-guerra** [comment]
Thanks @CobusT, and thanks to the team for working on this

From a quick search for the same words I used before *ocupación* vs *ocupacion* I can see that is not doing what I expected, which is to obtain the same results with both words. I'm not sure what's the standard you are aiming for though

It seems better now though, as it now *ocupacion* includes some results with accents e.g. *ocupación*.

**Comment by CobusT** [comment]
@john-guerra I actually get the same results (50 notebooks) when I search for ocupación vs ocupacion. The sort order is slightly different because it will show the ones with the exact spelling first, but if you, for example, sort by 'Created' you would see the exact same results.

**Comment by john-guerra** [comment]
I like the idea of showing the exact matching ones first, however:

* The match might be in the contents of the notebook vs the title. I'm getting 11 results like the following without the word ocupacion in the title, before the first one that has it

 - Introducción a la visualización de datos con Observable y d3.js
 - Población indígena víctima del conflicto
 - Visualización de contratos prestación de servicios Alcadia de bucaramanga 2018

* I have an unlisted notebook named "Ocupación camas Colombia". Shouldn't my own notebooks get the highest priority when searching. My main use case when using search is to help me find my own notebooks. I would expect to see my notebook first when I search Ocupacion. It goes second when I search ocupación

**Comment by CobusT** [comment]
We will look at 'boosting' the title and owner ranking. Those are good points. We can probably close this issue though, right? :-)

**Comment by john-guerra** [comment]
Sure can do
