### ISSUE TITLE
Syntax Error does not state which cell the error occurred on

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#77]
**Describe the bug**

If I do a SyntaxError I cannot use "find". Every other dependant cell tells me by name which cell has the SyntaxError through RuntimeError reporting, but the broken cell does not state its own name so its actually very difficult to find which cell is man-functioning when you have a lot of cells.

**Expected behavior**

SyntaxError should be like RuntimeError and be prepending with `<cellname> = SyntaxError: unexepected token`

**Screenshots**

In the following screenshot the cell that is broke is called "rel_links", but the cell is collapsed and the SyntaxError is masking the name...
![image](https://user-images.githubusercontent.com/1848162/114709374-c9852480-9d2c-11eb-8a53-0fcb6ce3ea38.png)

**Comment by mootari** [comment]
@tomlarkworthy Next or to Classic?

**Comment by tomlarkworthy** [comment]
Good point, just tested, Its the same on both

**Comment by mbostock** [comment]
Because the cell has invalid syntax, Observable can’t know what the name of the cell is. I sometimes switch to safe mode to do a full code search (and in Next you can do so without losing any of your page state, since you don’t leave the page—it just opens all the cells and stops running the code).

**Comment by mbostock** [comment]
That said, maybe we could try to guess what the name of the cell is in some cases, and add that to the error message like

```
rel_links? = SyntaxError: Unexpected token
```

But we’d need to write a separate heuristic parser/tokenizer to try to guess the name of the cell in a case like this.

Or maybe the simpler thing to do would be to include the first few words of the cell in the SyntaxError?

```
SyntaxError: Unexpected token `rel_links = something something …`
```

Though, that could possibly be a lot of additional noise especially if you already have the cell open.

**Comment by mbostock** [comment]
Another possibility might be to automatically open any cells that have invalid syntax. :)

**Comment by tomlarkworthy** [comment]
yeah I was trying to do "find" so that would unblock my workflow. Good one.

**Comment by mootari** [comment]
> and in Next you can do so without losing any of your page state, since you don’t leave the page—it just opens all the cells and stops running the code

@mbostock When you say "Next", do you mean the public Next? Because what you describe is not what I'm seeing.

**Comment by mbostock** [comment]
@mootari Yes, public Next. If you use View > Enable safe node to enter and View > Disable safe mode (or click the Exit button), it removes or adds the worker iframe, but it doesn’t reload the page.

**Comment by jrus** [comment]
Please don't auto-open all cells with invalid syntax. I intentionally introduce syntax errors all over the place to disable cells.

**Comment by CobusT** [comment]
> Please don't auto-open all cells with invalid syntax. I intentionally introduce syntax errors (typically by adding `x ` at the start) all over the place to disable cells and (mostly) hide them, but keep their contents for possible later use.
> 

I usually comment out the cell contents that I want to disable... 

Closing this request. Please reopen if you feel like it is not suitably addressed.
