### ISSUE TITLE
Menu action "Switch to Next" available to guests, but has no effect

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#78]
**Describe the bug**
When an Observable notebook is opened by an unauthenticated user, the menu option "Switch to Next" is available. After clicking the option, the user gets redirected to `?ui=next`. However, Next is not active, and the option is still available in the menu.

**To Reproduce**
1. Open an incognito/private tab
2. Visit https://observablehq.com/@observablehq/notebooks-cells
3. Click "Switch to Next" in the menu
4. Verify that the address bar contains the parameter `?ui=next`
5. Verify that the menu still contains the option "Switch to Next"

**Expected behavior**
If Next cannot (should not?) be made available to anonymous users, then the option should not be available in the menu.

**Comment by dunstan** [comment]
That would be a bug! Thanks for spotting it @mootari

**Comment by sydneypalumbo** [comment]
@nebrius fixed this yesterday 🙏
