### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#8]
**Is your feature request related to a problem? Please describe.**
I make many spelling mistakes and it detracts from the quality of my work. For a literate programming environment you might expect this to be available.

**Describe the solution you'd like**
A working spell checker

**Describe alternatives you've considered**
Currently I  copy and pasting into Grammarly. Not so good as it has to be done a cell at a time so I often skip it for small prose cells.

I also tried some development chrome extensions for spell checking whole sites, but they do not work with O's iframes

**Additional context**
Forum thread: https://talk.observablehq.com/t/spell-checker/2553

**Comment by mootari** [comment]
Is your preferred solution to enable spellchecking in the editor, or to make the iframe compatible with spellchecking extensions?

**Comment by tomlarkworthy** [comment]
A non chrome extension solution would be prefered but it's one of those burning issues where any improvement on the status quo is gladly adopted.

**Comment by jrus** [comment]
This is yet another issue that could be at least worked around by a documented, supported read/write API (https://github.com/observablehq/feedback/issues/6). There are plenty of external editors which support spellcheck inside text content wrapped in code (the editors' language parsers are smart enough to understand about the use of mixed languages in one file).

**Comment by CobusT** [comment]
We now have spellcheck in Markdown cells in next! It doesn't work in other cell modes, so won't save you from spelling errors in JS cells or html cells... but you are probably mostly concerned about spelling mistakes in Markdown cells...

Please let us know if it works for you and close this request if you feel this resolves it.

**Comment by tomlarkworthy** [comment]
yeah I guess it works for most workflows, but I do try to write blog posts and capture the markdown so the lack of named markdown cells kinda blunts that use case as I can't access the now correctly spelled content programatically. Anyway, it sure will help in a lot of places and access to markdown cells is a different feature so I think this is closed. Thank you so much!

**Comment by mootari** [comment]
@tomlarkworthy In the meantime you can run this line of code in your JS console (in the parent context) to enable spellchecking for all open editors:
~~~js
$$('.cm-content').map(n=>n.spellcheck=true)
~~~

**Comment by CobusT** [comment]
> yeah I guess it works for most workflows, but I do try to write blog posts and capture the markdown so the lack of named markdown cells kinda blunts that use case as I can't access the now correctly spelled content programatically. Anyway, it sure will help in a lot of places and access to markdown cells is a different feature so I think this is closed. Thank you so much!

I hear you. We still have an open feature request to look at bringing named markdown cells #105
