### ISSUE TITLE
Many debug messages in browser console

### ISSUE THREAD

**Issue by septatrix** [observablehq/feedback#86]
**Describe the bug**
In the browser console many debug messages are logged.
Often I open the console to perform ad-hoc calculations or try some things before putting them into a cell.
When opening the devtools after having worked on the notebook for a while it freezes for a while due to all the messages (in my cause repeatedly over a thousand).

**Expected behavior**
These debug messages yield no benefit and should be disabled (or at least only be enabled after a attribute on the window has been toggled to true).

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 90

**Comment by mootari** [comment]
Do you see these messages in Next or in Classic? If it is Next, then they are necessary for the Observable dev team, but can be disabled by unselecting the log level "Verbose".

**Comment by septatrix** [comment]
I am not sure but I guess I am on classic? The messages themselves are filtered by chrome (i.e. I already have verbose disabled) but they still the slow down the devtools when I first open them.

**Comment by mootari** [comment]
Performance (and memory leaks) is certainly an aspect that I hadn't considered.

> I am not sure but I guess I am on classic? 

Could you please verify? Afaik you should only see them in Next, Observable's feature preview (i.e., beta). There they are unfortunately essential to retroactively analyze bugs, especially with regard to Observable's multiplayer editing.

**Comment by septatrix** [comment]
How can I verify it? If I click on the menu button in my notebooks I get the option to switch to classic so I am guessing I am on Next?

**Comment by tomlarkworthy** [comment]
I am not sure if this is the same thing but I get so much log spam it freezes my devtools on first open 
![image](https://user-images.githubusercontent.com/1848162/134666386-1f76120f-8272-4417-8874-9df569fb6083.png)

Sometimes as many as 700 error message hidden rolled up by the grouping but still seemingly slowing my debugging experience down.

**Comment by CobusT** [comment]
The team is looking into this...

**Comment by mbostock** [comment]
We’ve turned off the console logs in production. Enjoy the silence!

**Comment by mbostock** [comment]
(The .map 404’s should also be gone, but because these were immutably-cached previously, you may need to clear your browser cache to see the effect.)
