### ISSUE TITLE
Certain Custom Error messages don't get displayed properly

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#87]
**Describe the bug**

Firebase and Google APIs define their own custom error types. For some reason these render as [object Object] despite the message field being a simple string. My guess is that there is some accessor indirection due to the use of Typescript and readonly properties. But to me it *should* work but doesn't. Some kinda of detection of Errors is not working well.

**To Reproduce**

https://observablehq.com/@tomlarkworthy/custom-error-weirdness

**Expected behavior**

These shoudl render as normal custom error messages

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  max
 - Browser chrome

**Comment by mootari** [comment]
I'm not sure what Observable is supposed to do about this, given that the error object is not an instance of Error and doesn't even define a custom toString() method.

**Comment by mootari** [comment]
I'm not sure what Observable is supposed to do about this given that the error object does not extend from Error, and does not define a custom toString().

*(comment restored after accidentally deleting it)*

**Comment by mootari** [comment]
It also doesn't look like firebase.storage.FirebaseStorageError gets exported anywhere. Otherwise you could have monkeypatched the method in.

**Comment by tomlarkworthy** [comment]
AKAICT it is an extension of Error

https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/util/src/errors.ts#L74

**Comment by mootari** [comment]
That's not what I'm seeing the typings that Chrome uses:
![image](https://user-images.githubusercontent.com/322014/115874512-773ab680-a444-11eb-98d9-68135fd239a1.png)

**Comment by tomlarkworthy** [comment]
+1 Fabian,

yeah and upgrade of the SDK fixed it and as you notices for inexplicable reasons FirebaseStorageErrors were note part of FirebaseError heiracrchy.
