### ISSUE TITLE
customizable syntax highlighting inside javascript template literals in cell editor

### ISSUE THREAD

**Issue by jrus** [observablehq/feedback#9]
**Problem:**  Currently, only Javascript code is syntax highlighted, but cells also contain HTML, SVG, Markdown, LaTeX, CSV, WebGL shaders, and various other markup / code languages, which currently are not highlighted.

**Proposed solution:**  It would be great if the notebook itself could specify some kind of map of template literal names -> syntax highlighting modes, with default support for `md`, `html`, `svg`, etc. templates.

**Comment by CobusT** [comment]
With the new 'cell modes' feature, we now have different syntax highlighting for different modes. 
JS
md
html
TeX

**Comment by CobusT** [comment]
@jrus would do you consider this feature request closed given the cell modes? I realize there are other feature requests asking for more flexibility and user control of cell modes (#106 ) so perhaps the remaining concerns/ideas relate more to those requests?

**Comment by CobusT** [comment]
Closing this, but feel free to re-open if you feel this is not covered by the syntax highlighting in the other cell modes.

**Comment by jrus** [comment]
Personally I don’t like using other cell types and would love it if the parser were smart enough to try to highlight inside template literals with some ability to customize the behavior. (See the TextMate editor for an example of this kind of polyglot syntax highlighting.)

But I can understand it’s trickier to implement than just highlighting one language at a time.
