### ISSUE TITLE
Console.log will throw unexpected error inside chart

### ISSUE THREAD

**Issue by jwilber** [observablehq/feedback#92]
**Describe the bug**
Console logging inside callbacks doesn't work past one layer of object keys

**To Reproduce**
1. Go to  https://observablehq.com/@jwilber/visualize-decision-trees-from-sklearn
2. Scroll down to the `// draw nodes` chunk and check out the console.logs. Currently it runs, but if you uncomment the two commented out `console.log(...)` calls, it fails as:

`chart = TypeError: Cannot read property 'data' of null`

**Expected behavior**
I would expect this to list the desired properties of what I'm trying to console.log. I'm guessing the error is because of the `chart = { ... }` wrapper, but given that it succeeded in the first console log (e.g. `console.log('parent', d.parent)`), I'm not sure why it would fail at the others.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7 
 - chrome
 - Version 90.0.4430.93

If this is expected behavior I apologize, I couldn't find documentation about it so am raising the issue just in case.

**Comment by j-f1** [comment]
The problem is that the root node has a `null` parent, so you can’t access the parent’s `data` property.

**Comment by jrus** [comment]
You can fix this by using

```js
      console.log('parent data', d.parent?.data)
      console.log('parent keys', Object.keys(d.parent ?? {}))
```
https://observablehq.com/compare/63abc1a6a5cb612f@231...c504ee748b985e83@232

**Comment by jwilber** [comment]
Ty!
