### ISSUE TITLE
Sort from various criteria results from a search

### ISSUE THREAD

**Issue by PBrockmann** [observablehq/feedback#93]
It would be nice to be able to sort by date (most recent to older) results when you search a keyword from all available notebooks.

Would be nice also to put keywords to define notebooks (technics used and meanings) ?
For exemple, I would like to find all notebooks made recently that use vega-lite or find notebooks about sankey diagram that use d3.

Also put an issue on 
https://talk.observablehq.com/t/sort-results-when-searching-notebooks/5032

Regards
Patrick

**Comment by CobusT** [comment]
Since we now have sort criteria implemented, the other idea here (tags) are already logged here: https://github.com/observablehq/feedback/issues/60
Can we close this one?
