### ISSUE TITLE
Would be easier to have a new thumbnail with links

### ISSUE THREAD

**Issue by PBrockmann** [observablehq/feedback#96]
Hi,

I would prefer new thumbnails when I click on a link.
...
target="_blank"

Patrick

**Comment by CobusT** [comment]
Patrick,
Can you expand on this a bit? I don't understand what you mean by 'new thumbnails'. Do you mean that you would prefer links to open in new tabs in your browser?

**Comment by jrus** [comment]
The suggestion is that links should be forced to always open in new browser tabs.

@PBrockmann You can do this to your own notebooks if you want, but I recommend against it. This behavior runs contrary to browser defaults, and breaks reader expectations. Speaking as a web reader, please never do this. It is incredibly frustrating when page authors try to reach down and change the basic UI behavior of my browser.

If you are browsing the web and you want a page to open in a new tab, I recommend using your browser’s existing shortcut for it. On the Mac, this is typically command-click, on Windows, control-click.

**Comment by CobusT** [comment]
After some discussion, we can safely say that we are not planning on overriding the default browser behavior for links. Thank you @jrus for your thoughts, also. And thank you @pbrockman for suggesting this. We welcome all feedback and suggestions.
